# Simple TCN

Notes:

* Only using 10 of the 30 ADL (smaller dataset plus some actions are very similar)
    * 11: "lift_suitcase_to_floor"
    * 12: "drink_from_glass"
    * 13: "answer_phone"
    * 16: "eat_apple"
    * 20: "use_key_unlock"
    * 21: "pour_water"
    * 23: "brush_teeth"
    * 24: "open_laptop"
    * 28: "open_door"
    * 29: "place_ball_in_basket"

* This version replaces the simple 1D CNN with a causal Temporal Convolutional Network (TCN).
* The TCN only uses current and past samples inside each window, which is better aligned with future live/streaming deployment.

## Imports

In [1]:
%pip install -q numpy pandas scikit-learn matplotlib torch

import os, re
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import itertools

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay, f1_score
from sklearn.model_selection import GroupShuffleSplit, LeaveOneGroupOut



# Run the mvnx_file_reader.ipynb to load MVNX files
%run mvnx_file_reader.ipynb

Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (2.2.6)
Requirement already satisfied: pandas in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (2.3.2)
Requirement already satisfied: matplotlib in /home/exb3dg/.local/lib/python3.12/site-packages (3.10.7)
Requirement already satisfied: nbformat in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (5.10.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/exb3dg/.local/lib/python3.12/site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /home/exb3dg/.local/lib/python3.12/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: fastjsonschema>=2.15 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from nbformat) (4.25.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (0.27.1)
Requirement already satisfied: platformdirs>=2.5 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.0)
Requirement already satisfied: six>=1.5 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /apps/software/standard/core/jupyterlab/4.4.6-py3.12/lib/python3.12/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
Note: you may need to restart the kernel to use updated packages.
Segment labels: ['Pelvis', 'L5', 'L3', 'T12', 'T8', 'Neck', 'Head', 'RightShoulder', 'RightUpperArm', 'RightForeArm', 'RightHand', 'LeftShoulder', 'LeftUpperArm', 'LeftForeArm', 'LeftHand', 'RightUpperLeg', 'RightLowerLeg', 'RightFoot', 'RightToe', 'LeftUpperLeg', 'LeftLowerLeg', 'LeftFoot', 'LeftToe']
Segment IDs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
RightHand positions (first 5 frames): [[0.000326, -0.7332, 1.53858], [0.007659, -0.732989, 1.535369], [0.007659, -0.732989, 1.535369], [5.256316, 1.154359, 0.728047], [5.256684, 1.155001, 0.728414]]
normal
Data types: ['time', 'index', 'tc', 'ms', 'type', 'orientation', 'position', 'velocity', 'acceleration', 'angularVelocity', 'angularAcceleration', 'contacts', 'sensorFreeAcceleration', 'sensorMagneticField', 'sensorOrientation', 'jointAngle', 'jointAngleXZY', 'centerOfMass']

### Globals

In [2]:
# 10 ADL selection
TASK_TO_LABEL = { # U-Limb dataset has 30 total, we're only using 10 of them for this project
    11: "lift_suitcase_to_floor",
    12: "drink_from_glass",
    13: "answer_phone",
    16: "eat_apple",
    20: "use_key_unlock",
    21: "pour_water",
    23: "brush_teeth",
    24: "open_laptop",
    28: "open_door",
    29: "place_ball_in_basket",
}

ALLOWED_TASKS = set(TASK_TO_LABEL.keys())

LEFT_LIMB_SEGS  = ["LeftUpperArm", "LeftForeArm", "LeftHand", "LeftShoulder"]
RIGHT_LIMB_SEGS = ["RightUpperArm", "RightForeArm", "RightHand", "RightShoulder"]

def segments_for_tested_limb(limb: str):
    limb = str(limb).upper()
    return LEFT_LIMB_SEGS if limb == "L" else RIGHT_LIMB_SEGS

# You'll have to change the DATA_ROOT variable to point to where you have the data stored on your computer.
# The notebook should be in the same folder as the data, so a relative path should work.
DATA_ROOT = "ULF_in_ADL"
# DATA_ROOT = "D:/UZH_data/ULF_in_ADL"

# Best channel set from your channel ablation study
CHANNELS = [
    "angularVelocity",
    "sensorFreeAcceleration",
]

WIN_LEN_S = 4.0  # seconds
STEP_S = 0.5     # seconds
MIN_OVERLAP_FRACTION = 0.5

# Segment ablation settings
RESULTS_BASENAME = "segment_combination_study"
RUN_FULL_SEGMENT_BASELINE_FIRST = False

# Cache settings
CACHE_DIR = "cached_datasets"
USE_DATASET_CACHE = True
FORCE_REBUILD_DATASET = False

# Result saving
RESULTS_DIR = "experiment_results"

# Training settings
BATCH_SIZE_TRAIN = 128
BATCH_SIZE_EVAL = 256
EPOCHS = 20
LR = 1e-4
WEIGHT_DECAY = 1e-4
DROPOUT = 0.2
KERNEL_SIZE = 5
TCN_CHANNELS = (64, 64, 128, 128)

# Early stopping
EARLY_STOPPING_PATIENCE = 5
EARLY_STOPPING_MIN_DELTA = 0.002
VAL_SIZE = 0.20
RANDOM_STATE = 42

# LOSO evaluation settings
LOSO_MAX_FOLDS = None  # Set to an integer like 4 for a quick pilot run, or keep None for all subjects
PLOT_FIRST_FOLD_CURVES = True
SAVE_PER_FOLD_CSV = True

### File Helpers

Helper functions to find files, parse task from filename, and extract per-segment vectors

In [3]:
# Helper functions to find and parse MVNX files
def iter_mvnx_files(root: str):
    for r, _, files in os.walk(root):
        for fn in files:
            if fn.lower().endswith(".mvnx"):
                yield os.path.join(r, fn)

# Parses participant, task, limb, and rep from filename
def parse_meta_from_filename(filepath: str):
    """
    Expected example: H01_T01_L1.mvnx OR P02_T15_R3.mvnx
    Returns dict: participant, task(int), limb('L'/'R'), rep(int)
    """
    base = os.path.basename(filepath)

    m = re.match(r"^(?P<participant>[A-Za-z]\d{2})_T(?P<task>\d{2})_(?P<limb>[LRlr])(?P<rep>\d)\.mvnx$", base)
    if not m:
        return None

    participant = m.group("participant")
    task = int(m.group("task"))
    limb = m.group("limb").upper()
    rep = int(m.group("rep"))
    return {"participant": participant, "task": task, "limb": limb, "rep": rep}


# Functions to extract frame rate and channel data from MVNX dicts
def get_frame_rate_hz(mvnx_dict) -> float:
    # MVNX stores it on subject
    fr = mvnx_dict["mvnx"]["subject"].get("frameRate", None)
    if fr is None:
        raise ValueError("frameRate not found in mvnx['mvnx']['subject']")
    return float(fr)

def _as_list(x):
    if isinstance(x, list):
        return x
    if x is None:
        return []
    return [x]

def build_segment_index_map(mvnx_dict):
    segments = _as_list(mvnx_dict["mvnx"]["subject"]["segments"]["segment"])
    return {seg["label"]: i for i, seg in enumerate(segments)}

def build_sensor_index_map(mvnx_dict):
    sensors = _as_list(mvnx_dict["mvnx"]["subject"]["sensors"]["sensor"])
    return {sensor["label"]: i for i, sensor in enumerate(sensors)}

def build_joint_index_map(mvnx_dict):
    joints = _as_list(mvnx_dict["mvnx"]["subject"]["joints"]["joint"])
    return {joint["label"]: i for i, joint in enumerate(joints)}

SEGMENT_CHANNEL_SPECS = {
    "orientation": (build_segment_index_map, 4),
    "position": (build_segment_index_map, 3),
    "velocity": (build_segment_index_map, 3),
    "acceleration": (build_segment_index_map, 3),
    "angularVelocity": (build_segment_index_map, 3),
    "angularAcceleration": (build_segment_index_map, 3),
}

SENSOR_CHANNEL_SPECS = {
    "sensorFreeAcceleration": (build_sensor_index_map, 3),
    "sensorMagneticField": (build_sensor_index_map, 3),
    "sensorOrientation": (build_sensor_index_map, 4),
}

# For joint channels we map each tested segment to the most relevant joint on that limb.
JOINT_CHANNEL_SPECS = {
    "jointAngle": 3,
    "jointAngleXZY": 3,
}

LEFT_SEGMENT_TO_JOINT = {
    "LeftShoulder": "jLeftT4Shoulder",
    "LeftUpperArm": "jLeftShoulder",
    "LeftForeArm": "jLeftElbow",
    "LeftHand": "jLeftWrist",
}

RIGHT_SEGMENT_TO_JOINT = {
    "RightShoulder": "jRightT4Shoulder",
    "RightUpperArm": "jRightShoulder",
    "RightForeArm": "jRightElbow",
    "RightHand": "jRightWrist",
}

def get_segment_joint_label(segment_label: str, limb: str) -> str:
    limb = str(limb).upper()
    mapping = LEFT_SEGMENT_TO_JOINT if limb == "L" else RIGHT_SEGMENT_TO_JOINT
    if segment_label not in mapping:
        raise KeyError(f"No joint mapping defined for segment '{segment_label}' on limb '{limb}'.")
    return mapping[segment_label]

def _slice_labeled_vector(mvnx_dict, frame_dict, channel: str, label: str, index_builder, components: int) -> np.ndarray:
    label_map = index_builder(mvnx_dict)
    if label not in label_map:
        raise KeyError(f"Label '{label}' not found for channel '{channel}'. Available labels include: {list(label_map)[:8]} ...")

    vec = frame_dict.get(channel, None)
    if vec is None:
        raise KeyError(f"Channel '{channel}' not found in this frame.")

    arr = np.asarray(vec, dtype=np.float32).ravel()
    idx = label_map[label]
    start = components * idx
    end = start + components

    if end > arr.size:
        raise ValueError(
            f"Channel '{channel}' with label '{label}' expected slice [{start}:{end}] "
            f"but frame only has {arr.size} values."
        )
    return arr[start:end]

def get_channel_vector(mvnx_dict, frame_dict, segment_label: str, channel: str, limb: str) -> np.ndarray:
    """
    Channel-aware extractor.

    Uses:
    - segment indexing for segment-level channels
    - sensor indexing for sensor-level channels
    - joint indexing for joint-angle channels
    """
    if channel in SEGMENT_CHANNEL_SPECS:
        index_builder, components = SEGMENT_CHANNEL_SPECS[channel]
        return _slice_labeled_vector(mvnx_dict, frame_dict, channel, segment_label, index_builder, components)

    if channel in SENSOR_CHANNEL_SPECS:
        index_builder, components = SENSOR_CHANNEL_SPECS[channel]
        return _slice_labeled_vector(mvnx_dict, frame_dict, channel, segment_label, index_builder, components)

    if channel in JOINT_CHANNEL_SPECS:
        joint_label = get_segment_joint_label(segment_label, limb)
        components = JOINT_CHANNEL_SPECS[channel]
        return _slice_labeled_vector(mvnx_dict, frame_dict, channel, joint_label, build_joint_index_map, components)

    raise KeyError(
        f"Unsupported channel '{channel}'. Add it to SEGMENT_CHANNEL_SPECS, "
        f"SENSOR_CHANNEL_SPECS, or JOINT_CHANNEL_SPECS."
    )

# Only keep frames where type="normal" (some files have "calibration" frames at the start that we want to ignore)
def only_normal_frames(mvnx: dict) -> list[dict]:
    frames = mvnx["mvnx"]["subject"]["frames"]["frame"]
    if isinstance(frames, dict):
        frames = [frames]
    return [fr for fr in frames if str(fr.get("type", "")).lower() == "normal"]

# Generator for start/end indices of sliding windows over N samples
def window_indices(n_samples: int, win_len: int, step: int):
    s = 0
    while s + win_len <= n_samples:
        yield s, s + win_len
        s += step

In [4]:
# quick test
sample_paths = list(iter_mvnx_files(DATA_ROOT))[:5]
print("Found files (sample):")
for p in sample_paths:
    print(" ", os.path.basename(p), parse_meta_from_filename(p))

Found files (sample):
  P17_T02_L3.mvnx {'participant': 'P17', 'task': 2, 'limb': 'L', 'rep': 3}
  P17_T24_L2.mvnx {'participant': 'P17', 'task': 24, 'limb': 'L', 'rep': 2}
  P17_T28_R3.mvnx {'participant': 'P17', 'task': 28, 'limb': 'R', 'rep': 3}
  P17_T26_L1.mvnx {'participant': 'P17', 'task': 26, 'limb': 'L', 'rep': 1}
  P17_T01_L3.mvnx {'participant': 'P17', 'task': 1, 'limb': 'L', 'rep': 3}

Helpers for mvnx frame/channel extractions

In [5]:
# Build windows for one file, returning X_win (num_windows, win_len, num_channels), y_win (num_windows,), g_win (num_windows,)
def windows_file_cnn(filepath: str, win_len_s, step_s, channels=None, selected_segments=None):

    if channels is None:
        channels = CHANNELS

    meta = parse_meta_from_filename(filepath)
    if meta is None or meta["task"] not in ALLOWED_TASKS:
        return None

    mvnx = load_mvnx(filepath)
    frames = only_normal_frames(mvnx)
    if len(frames) < 10:
        return None

    frame_rate = float(mvnx["mvnx"]["subject"].get("frameRate", 0))
    win_len = max(int(round(win_len_s * frame_rate)), 5)
    step = max(int(round(step_s * frame_rate)), 1)

    default_segments = segments_for_tested_limb(meta["limb"])
    if selected_segments is None:
        segments = default_segments
    else:
        selected_segments = [str(seg) for seg in selected_segments]
        available = set(default_segments)
        segments = [seg for seg in selected_segments if seg in available]
        if len(segments) == 0:
            raise ValueError(
                f"No valid segments selected for limb {meta['limb']}. "
                f"Requested: {selected_segments} | Available: {default_segments}"
            )

    N = len(frames)

    # Precompute channel arrays for each segment. The feature width depends on channel type:
    # xyz channels -> 3, quaternion channels -> 4.
    data = {}
    feature_dims = {}
    for seg in segments:
        for ch in channels:
            first_vec = get_channel_vector(mvnx, frames[0], seg, ch, meta["limb"])
            D = int(np.asarray(first_vec).size)
            arr = np.zeros((N, D), dtype=np.float32)
            arr[0] = first_vec
            for i in range(1, N):
                arr[i] = get_channel_vector(mvnx, frames[i], seg, ch, meta["limb"])
            data[(ch, seg)] = arr
            feature_dims[(ch, seg)] = D

    X_win, y_win, g_win = [], [], []
    for a, b in window_indices(N, win_len, step):
        cols = []
        for seg in segments:
            for ch in channels:
                cols.append(data[(ch, seg)][a:b])   # (T,D)
        Xw = np.concatenate(cols, axis=1)          # (T, C_total)
        X_win.append(Xw)
        y_win.append(TASK_TO_LABEL[meta["task"]])
        g_win.append(meta["participant"])

    if not X_win:
        return None

    return (
        np.stack(X_win, axis=0).astype(np.float32),
        np.asarray(y_win),
        np.asarray(g_win),
    )

## Building Dataset
Building a fixed post-channel-study dataset for a **segment combination study** using:

- channels: `angularVelocity`, `sensorFreeAcceleration`
- window length: **4.0 s**
- step size: **0.5 s**

Each run uses the same two channels and windowing, but changes which tested-limb arm segments are included.

In [6]:
# Dataset caching helpers
def _safe_name(txt: str):
    txt = str(txt)
    txt = re.sub(r"[^A-Za-z0-9_.-]+", "-", txt)
    return txt.strip("-") or "default"

def canonical_segment_order(selected_segments):
    if selected_segments is None:
        return None
    return [str(seg) for seg in selected_segments]

def make_dataset_cache_path(
    root: str,
    channels,
    win_len_s: float,
    step_s: float,
    selected_segments=None,
    allowed_tasks=None,
    cache_dir: str = CACHE_DIR,
):
    os.makedirs(cache_dir, exist_ok=True)

    root_name = _safe_name(os.path.basename(os.path.normpath(root)) or "dataset")
    channel_name = _safe_name("_".join(channels))
    if selected_segments is None:
        segment_name = "default-tested-limb"
    else:
        segment_name = _safe_name("_".join(canonical_segment_order(selected_segments)))
    task_name = "alltasks" if allowed_tasks is None else _safe_name("-".join(map(str, sorted(allowed_tasks))))

    filename = (
        f"dataset_{root_name}"
        f"__ch-{channel_name}"
        f"__seg-{segment_name}"
        f"__win-{win_len_s:g}s"
        f"__step-{step_s:g}s"
        f"__tasks-{task_name}.npz"
    )
    return os.path.join(cache_dir, filename)

# Build the full dataset by iterating over all files and concatenating results
def build_dataset(root: str, win_len_s, step_s, channels=None, selected_segments=None):
    if channels is None:
        channels = CHANNELS

    X_list, y_list, g_list = [], [], []
    kept = 0
    skipped = 0

    for fp in iter_mvnx_files(root):
        meta = parse_meta_from_filename(fp)
        if meta is None:
            continue
        if meta["task"] not in ALLOWED_TASKS:
            continue

        try:
            out = windows_file_cnn(
                fp,
                win_len_s=win_len_s,
                step_s=step_s,
                channels=channels,
                selected_segments=selected_segments,
            )
        except Exception as e:
            skipped += 1
            print(f"Skipping {os.path.basename(fp)} due to extraction/build error: {e}")
            continue

        if out is None:
            skipped += 1
            continue

        Xw, yw, gw = out
        X_list.append(Xw)
        y_list.append(yw)
        g_list.append(gw)
        kept += 1

    if not X_list:
        raise RuntimeError("No windows were built. Check parsing/task filters/DATA_ROOT.")

    X = np.concatenate(X_list, axis=0)   # (N, T, C)
    y = np.concatenate(y_list, axis=0)   # (N,)
    g = np.concatenate(g_list, axis=0)   # (N,)

    print(f"Kept files: {kept} | Skipped files (allowed but failed): {skipped}")
    print("X:", X.shape, "y:", y.shape, "groups:", g.shape)

    return X, y, g

def load_or_build_dataset(root: str, win_len_s, step_s, channels, selected_segments=None, use_cache=True, force_rebuild=False):
    cache_path = make_dataset_cache_path(
        root=root,
        channels=channels,
        win_len_s=win_len_s,
        step_s=step_s,
        selected_segments=selected_segments,
        allowed_tasks=ALLOWED_TASKS,
        cache_dir=CACHE_DIR,
    )

    if use_cache and os.path.exists(cache_path) and not force_rebuild:
        print(f"Loading cached dataset from: {cache_path}")
        cached = np.load(cache_path, allow_pickle=True)
        X = cached["X"]
        y = cached["y"]
        g = cached["groups"]
        return X, y, g, cache_path

    print("No cached dataset found. Building dataset from MVNX files...")
    X, y, g = build_dataset(
        root,
        win_len_s=win_len_s,
        step_s=step_s,
        channels=channels,
        selected_segments=selected_segments,
    )

    if use_cache:
        np.savez_compressed(
            cache_path,
            X=X.astype(np.float32),
            y=y,
            groups=g,
            channels=np.array(channels, dtype=object),
            selected_segments=np.array(
                canonical_segment_order(selected_segments) if selected_segments is not None else [],
                dtype=object
            ),
            win_len_s=np.array([win_len_s], dtype=np.float32),
            step_s=np.array([step_s], dtype=np.float32),
        )
        print(f"Saved dataset cache to: {cache_path}")

    return X, y, g, cache_path

def summarize_dataset(X, y, groups, prefix="Segment ablation run"):
    print(f"{prefix} dataset loaded.")
    print("Dataset shape:", X.shape)
    print("Unique subjects:", len(set(groups)))
    vals, cnts = np.unique(y, return_counts=True)
    print("Class counts:", dict(zip(vals, cnts)))
    print("Example window shape (T,C):", X[0].shape)

### Normalization

Different normalization from SVM

In [7]:
# IMPORTANT:
# Do NOT normalize before LOSO splitting. That would let the held-out subject
# influence scaling. Instead, fit normalization on the training fold only and
# apply it to val/test inside each fold.

def fit_channel_zscore(X: np.ndarray, eps: float = 1e-8):
    """
    Fit one global z-score per feature channel using TRAINING WINDOWS ONLY.

    X: (N, T, C)
    Returns:
        mu: (C,)
        sd: (C,)
    """
    pooled = X.reshape(-1, X.shape[-1]).astype(np.float32)
    mu = pooled.mean(axis=0)
    sd = pooled.std(axis=0)
    sd = np.maximum(sd, eps)
    return mu, sd

def apply_channel_zscore(X: np.ndarray, mu: np.ndarray, sd: np.ndarray) -> np.ndarray:
    """Apply pre-fit channel-wise z-score to (N, T, C)."""
    return ((X.astype(np.float32) - mu) / sd).astype(np.float32)

print("Normalization helpers defined.")
print("Dataset arrays (X, y, groups) are loaded later inside run_windowing_study()")
print("via load_or_build_dataset(...), one window/step configuration at a time.")

Normalization helpers defined.
Dataset arrays (X, y, groups) are loaded later inside run_windowing_study()
via load_or_build_dataset(...), one window/step configuration at a time.

### Note on dataset creation and caching

This notebook runs a **segment combination study** at a fixed **4.0 s** window and **0.5 s** step.

It uses only these IMU channels:

- `angularVelocity`
- `sensorFreeAcceleration`

Instead of leave-one-out, the bottom cell runs **all non-empty combinations** of the 4 tested-limb arm segments:

- UpperArm
- ForeArm
- Hand
- Shoulder

That gives **15 total segment combinations**.

The dataset cache name includes both the channel set and the selected segment set, so each segment combination gets its own `.npz` cache.

## Train and Evaluate

Train/test split by subject and encode labels

In [8]:
from sklearn.model_selection import GroupShuffleSplit, LeaveOneGroupOut
import hashlib
from collections import defaultdict
from itertools import product
from datetime import datetime

def encode_labels(y: np.ndarray):
    labels = sorted(list(set(y)))
    lab2i = {lab:i for i, lab in enumerate(labels)}
    i2lab = {i:lab for lab,i in lab2i.items()}
    y_i = np.array([lab2i[v] for v in y], dtype=np.int64)
    return labels, lab2i, i2lab, y_i

def make_grouped_train_val_split(groups_train: np.ndarray, val_size: float = VAL_SIZE, random_state: int = RANDOM_STATE):
    """
    Creates a validation split using training subjects only.
    This is used INSIDE each LOSO fold for early stopping.
    """
    unique_subjects = np.unique(groups_train)

    if len(unique_subjects) < 2:
        raise ValueError("Need at least 2 training subjects to create a validation split.")

    if len(unique_subjects) == 2:
        # Fallback: keep one subject for train and one for validation
        val_subject = unique_subjects[-1]
        val_idx = np.where(groups_train == val_subject)[0]
        train_idx = np.where(groups_train != val_subject)[0]
        return train_idx, val_idx

    gss_val = GroupShuffleSplit(n_splits=1, test_size=val_size, random_state=random_state)
    train_idx, val_idx = next(gss_val.split(np.zeros(len(groups_train)), groups=groups_train))
    return train_idx, val_idx

def hash_array(a: np.ndarray) -> str:
    h = hashlib.md5()
    h.update(a.tobytes())
    return h.hexdigest()

def report_split_integrity(name_a, X_a, g_a, idx_a, name_b, X_b, g_b, idx_b):
    overlap = set(g_a) & set(g_b)
    if overlap:
        print(f"WARNING: Subject(s) in both {name_a} and {name_b}: {overlap}")
    else:
        print(f"No subject overlap detected between {name_a} and {name_b}.")

    hashes_a = {hash_array(X_a[i]): idx_a[i] for i in range(len(X_a))}
    hashes_b = {hash_array(X_b[i]): idx_b[i] for i in range(len(X_b))}
    common = set(hashes_a.keys()) & set(hashes_b.keys())
    print(f"Identical windows in {name_a}/{name_b}: {len(common)}")
    if common:
        for h in list(common)[:5]:
            print(f"Example identical window - {name_a} idx: {hashes_a[h]} | {name_b} idx: {hashes_b[h]}")

def build_loso_splits(X, y_i, groups, max_folds=None):
    logo = LeaveOneGroupOut()
    all_loso_splits = list(logo.split(X, y_i, groups=groups))
    if max_folds is not None:
        all_loso_splits = all_loso_splits[:max_folds]
    return all_loso_splits

def window_overlap_fraction(win_len_s: float, step_s: float) -> float:
    return 1.0 - (step_s / win_len_s)

def is_valid_window_step_combo(win_len_s: float, step_s: float, min_overlap_fraction: float = MIN_OVERLAP_FRACTION) -> bool:
    if step_s <= 0 or win_len_s <= 0:
        return False
    if step_s > win_len_s:
        return False
    return window_overlap_fraction(win_len_s, step_s) >= min_overlap_fraction

def make_windowing_grid(window_lengths=None, step_sizes=None, min_overlap_fraction: float = MIN_OVERLAP_FRACTION):
    window_lengths = SWEEP_WINDOW_LENGTHS if window_lengths is None else window_lengths
    step_sizes = SWEEP_STEP_SIZES if step_sizes is None else step_sizes

    combos = []
    for win_len_s, step_s in product(window_lengths, step_sizes):
        overlap = window_overlap_fraction(win_len_s, step_s)
        if is_valid_window_step_combo(win_len_s, step_s, min_overlap_fraction=min_overlap_fraction):
            combos.append({
                "win_len_s": float(win_len_s),
                "step_s": float(step_s),
                "overlap_fraction": float(overlap),
            })
        else:
            print(f"Skipping invalid combo: win={win_len_s}, step={step_s}, overlap={overlap:.3f}")
    return combos

def ensure_results_dir(results_dir: str = RESULTS_DIR):
    os.makedirs(results_dir, exist_ok=True)
    return results_dir

def make_results_stem(study_name: str, win_len_s: float, step_s: float, results_dir: str = RESULTS_DIR):
    ensure_results_dir(results_dir)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_study_name = _safe_name(study_name)

    base = f"{safe_study_name}__win-{win_len_s:g}s__step-{step_s:g}s__{timestamp}"

    # Keep filenames short enough for Windows path limits.
    max_base_len = 110
    if len(base) > max_base_len:
        name_hash = hashlib.md5(safe_study_name.encode("utf-8")).hexdigest()[:8]
        truncated = safe_study_name[:40].rstrip("-_.")
        base = f"{truncated}__{name_hash}__win-{win_len_s:g}s__step-{step_s:g}s__{timestamp}"

    if len(base) > max_base_len:
        name_hash = hashlib.md5(safe_study_name.encode("utf-8")).hexdigest()[:8]
        base = f"run__{name_hash}__w{win_len_s:g}s__s{step_s:g}s__{timestamp}"

    return os.path.join(results_dir, base)

Simple TCN dataset and model

In [9]:
import copy
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay, f1_score
import matplotlib.pyplot as plt

class WindowDataset(Dataset):
    def __init__(self, X, y_int):
        # Convert (N, T, C) -> (N, C, T) for Conv1d
        self.X = torch.tensor(np.transpose(X, (0, 2, 1)), dtype=torch.float32)
        self.y = torch.tensor(y_int, dtype=torch.long)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

class Chomp1d(nn.Module):
    """
    Removes the extra right-side padding so the convolution is causal:
    output[t] depends only on x[:t].
    """
    def __init__(self, chomp_size):
        super().__init__()
        self.chomp_size = chomp_size

    def forward(self, x):
        if self.chomp_size == 0:
            return x
        return x[:, :, :-self.chomp_size].contiguous()

class TemporalBlock(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, dilation, dropout=0.2):
        super().__init__()
        padding = (kernel_size - 1) * dilation  # causal

        self.net = nn.Sequential(
            nn.Conv1d(in_channels, out_channels, kernel_size,
                      padding=padding, dilation=dilation),
            Chomp1d(padding),
            nn.BatchNorm1d(out_channels),
            nn.ReLU(),
            nn.Dropout(dropout),

            nn.Conv1d(out_channels, out_channels, kernel_size,
                      padding=padding, dilation=dilation),
            Chomp1d(padding),
            nn.BatchNorm1d(out_channels),
            nn.ReLU(),
            nn.Dropout(dropout),
        )

        self.downsample = nn.Conv1d(in_channels, out_channels, kernel_size=1) if in_channels != out_channels else None
        self.relu = nn.ReLU()

    def forward(self, x):
        out = self.net(x)
        res = x if self.downsample is None else self.downsample(x)
        return self.relu(out + res)

class SimpleTCN(nn.Module):
    def __init__(self, in_channels, n_classes, channels=TCN_CHANNELS, kernel_size=KERNEL_SIZE, dropout=DROPOUT):
        super().__init__()

        layers = []
        prev_channels = in_channels
        for i, out_channels in enumerate(channels):
            dilation = 2 ** i
            layers.append(
                TemporalBlock(
                    in_channels=prev_channels,
                    out_channels=out_channels,
                    kernel_size=kernel_size,
                    dilation=dilation,
                    dropout=dropout,
                )
            )
            prev_channels = out_channels

        self.tcn = nn.Sequential(*layers)
        self.pool = nn.AdaptiveAvgPool1d(1)
        self.classifier = nn.Linear(prev_channels, n_classes)

    def forward(self, x):
        z = self.tcn(x)
        z = self.pool(z).squeeze(-1)
        return self.classifier(z)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

def make_loaders(X_train, y_train_i, X_val, y_val_i, X_test, y_test_i):
    train_ds = WindowDataset(X_train, y_train_i)
    val_ds   = WindowDataset(X_val, y_val_i)
    test_ds  = WindowDataset(X_test, y_test_i)

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE_TRAIN, shuffle=True, drop_last=False)
    val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE_EVAL, shuffle=False, drop_last=False)
    test_loader  = DataLoader(test_ds, batch_size=BATCH_SIZE_EVAL, shuffle=False, drop_last=False)

    return train_ds, val_ds, test_ds, train_loader, val_loader, test_loader

def build_model_and_training_objects(in_channels: int, y_train_i: np.ndarray):
    model = SimpleTCN(
        in_channels=in_channels,
        n_classes=len(labels),
    ).to(device)

    counts = np.bincount(y_train_i, minlength=len(labels)).astype(np.float32)
    w = counts.sum() / (counts + 1e-6)
    w = w / w.mean()
    criterion = nn.CrossEntropyLoss(weight=torch.tensor(w, dtype=torch.float32).to(device))
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    return model, criterion, optimizer

def eval_model(model, loader):
    model.eval()
    ys, ps = [], []
    with torch.no_grad():
        for xb, yb in loader:
            xb = xb.to(device)
            logits = model(xb)
            pred = torch.argmax(logits, dim=1).cpu().numpy()
            ps.append(pred)
            ys.append(yb.numpy())
    y_true = np.concatenate(ys)
    y_pred = np.concatenate(ps)
    return y_true, y_pred

def run_eval_loss_acc(model, loader, criterion):
    model.eval()
    total_loss = 0.0
    ys, ps = [], []
    with torch.no_grad():
        for xb, yb in loader:
            xb = xb.to(device)
            yb = yb.to(device)
            logits = model(xb)
            loss = criterion(logits, yb)
            total_loss += loss.item() * xb.size(0)

            pred = torch.argmax(logits, dim=1)
            ys.append(yb.cpu().numpy())
            ps.append(pred.cpu().numpy())

    y_true = np.concatenate(ys)
    y_pred = np.concatenate(ps)
    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(y_true, y_pred)
    return avg_loss, acc

print("TCN classes and helper functions are ready.")

Using device: cuda
TCN classes and helper functions are ready.

### Train and evaluate

In [11]:
from sklearn.metrics import f1_score

def run_loso_experiment(
    X,
    y,
    groups,
    study_name: str,
    win_len_s: float,
    step_s: float,
    channels_used=None,
    selected_segments=None,
    plot_first_fold_curves: bool = PLOT_FIRST_FOLD_CURVES,
    loso_max_folds = LOSO_MAX_FOLDS,
    save_per_fold_csv: bool = SAVE_PER_FOLD_CSV,
    results_dir: str = RESULTS_DIR,
):
    labels, lab2i, i2lab, y_i = encode_labels(y)
    all_loso_splits = build_loso_splits(X, y_i, groups, max_folds=loso_max_folds)

    print(f"Total LOSO folds to run: {len(all_loso_splits)}")
    print("Classes:", labels)
    print("Subjects:", sorted(np.unique(groups)))

    fold_rows = []
    all_y_true = []
    all_y_pred = []
    first_fold_history = None

    for fold_idx, (trainval_idx, test_idx) in enumerate(all_loso_splits, start=1):
        held_out_subject = np.unique(groups[test_idx])
        if len(held_out_subject) != 1:
            raise RuntimeError("LOSO fold should contain exactly one held-out subject.")
        held_out_subject = held_out_subject[0]

        print("=" * 90)
        print(f"LOSO fold {fold_idx}/{len(all_loso_splits)} | test subject: {held_out_subject}")

        X_trainval_raw, X_test_raw = X[trainval_idx], X[test_idx]
        y_trainval_i, y_test_i = y_i[trainval_idx], y_i[test_idx]
        g_trainval, g_test = groups[trainval_idx], groups[test_idx]

        train_sub_idx, val_sub_idx = make_grouped_train_val_split(g_trainval, val_size=VAL_SIZE, random_state=RANDOM_STATE)

        X_train_raw, X_val_raw = X_trainval_raw[train_sub_idx], X_trainval_raw[val_sub_idx]
        y_train_i, y_val_i = y_trainval_i[train_sub_idx], y_trainval_i[val_sub_idx]
        g_train, g_val = g_trainval[train_sub_idx], g_trainval[val_sub_idx]

        print(f"Train subjects: {sorted(np.unique(g_train))}")
        print(f"Val subjects:   {sorted(np.unique(g_val))}")
        print(f"Test subject:   {sorted(np.unique(g_test))}")

        mu, sd = fit_channel_zscore(X_train_raw)
        X_train = apply_channel_zscore(X_train_raw, mu, sd)
        X_val   = apply_channel_zscore(X_val_raw, mu, sd)
        X_test  = apply_channel_zscore(X_test_raw, mu, sd)

        report_split_integrity("train", X_train, g_train, trainval_idx[train_sub_idx],
                            "val", X_val, g_val, trainval_idx[val_sub_idx])
        report_split_integrity("train", X_train, g_train, trainval_idx[train_sub_idx],
                            "test", X_test, g_test, test_idx)
        report_split_integrity("val", X_val, g_val, trainval_idx[val_sub_idx],
                            "test", X_test, g_test, test_idx)

        train_ds, val_ds, test_ds, train_loader, val_loader, test_loader = make_loaders(
            X_train, y_train_i, X_val, y_val_i, X_test, y_test_i
        )

        model, criterion, optimizer = build_model_and_training_objects(
            in_channels=train_ds.X.shape[1],
            y_train_i=y_train_i,
        )

        train_losses, val_losses, test_losses = [], [], []
        train_accs, val_accs, test_accs = [], [], []

        epochs_ran = 0
        best_val_acc = -1.0
        best_state = None
        patience_counter = 0

        for epoch in range(1, EPOCHS + 1):
            epochs_ran = epoch
            model.train()
            total_loss = 0.0
            ys, ps = [], []

            for xb, yb in train_loader:
                xb = xb.to(device)
                yb = yb.to(device)

                optimizer.zero_grad()
                logits = model(xb)
                loss = criterion(logits, yb)
                loss.backward()
                nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()

                total_loss += loss.item() * xb.size(0)
                pred = torch.argmax(logits, dim=1)
                ys.append(yb.cpu().numpy())
                ps.append(pred.detach().cpu().numpy())

            train_loss = total_loss / len(train_loader.dataset)
            train_acc = accuracy_score(np.concatenate(ys), np.concatenate(ps))

            val_loss, val_acc = run_eval_loss_acc(model, val_loader, criterion)
            test_loss, test_acc = run_eval_loss_acc(model, test_loader, criterion)

            train_losses.append(train_loss)
            val_losses.append(val_loss)
            test_losses.append(test_loss)

            train_accs.append(train_acc)
            val_accs.append(val_acc)
            test_accs.append(test_acc)

            print(
                f"Epoch {epoch:02d} | "
                f"train_loss={train_loss:.4f} train_acc={train_acc:.4f} | "
                f"val_loss={val_loss:.4f} val_acc={val_acc:.4f} | "
                f"test_loss={test_loss:.4f} test_acc={test_acc:.4f}"
            )

            improvement = val_acc - best_val_acc
            if improvement > EARLY_STOPPING_MIN_DELTA:
                best_val_acc = val_acc
                best_state = copy.deepcopy(model.state_dict())
                patience_counter = 0
            else:
                patience_counter += 1
                print(
                    f"  No validation improvement greater than {EARLY_STOPPING_MIN_DELTA:.4f}. "
                    f"Patience: {patience_counter}/{EARLY_STOPPING_PATIENCE}"
                )
                if patience_counter >= EARLY_STOPPING_PATIENCE:
                    print(f"Early stopping triggered at epoch {epoch}.")
                    break

        if best_state is not None:
            model.load_state_dict(best_state)

        y_true_fold, y_pred_fold = eval_model(model, test_loader)

        fold_acc = accuracy_score(y_true_fold, y_pred_fold)
        fold_macro_f1 = f1_score(y_true_fold, y_pred_fold, average="macro", zero_division=0)

        fold_rows.append({
            "fold": fold_idx,
            "test_subject": held_out_subject,
            "win_len_s": win_len_s,
            "step_s": step_s,
            "overlap_fraction": window_overlap_fraction(win_len_s, step_s),
            "n_train_windows": len(train_ds),
            "n_val_windows": len(val_ds),
            "n_test_windows": len(test_ds),
            "n_train_subjects": len(np.unique(g_train)),
            "n_val_subjects": len(np.unique(g_val)),
            "epochs_ran": epochs_ran,
            "best_val_acc": best_val_acc,
            "test_acc": fold_acc,
            "test_macro_f1": fold_macro_f1,
        })

        all_y_true.append(y_true_fold)
        all_y_pred.append(y_pred_fold)

        print(f"Fold {fold_idx} complete | subject={held_out_subject} | "
            f"test_acc={fold_acc:.4f} | test_macro_f1={fold_macro_f1:.4f}")

        if first_fold_history is None:
            first_fold_history = {
                "epochs_ran": epochs_ran,
                "train_losses": train_losses.copy(),
                "val_losses": val_losses.copy(),
                "test_losses": test_losses.copy(),
                "train_accs": train_accs.copy(),
                "val_accs": val_accs.copy(),
                "test_accs": test_accs.copy(),
                "subject": held_out_subject,
            }

    results_df = pd.DataFrame(fold_rows)
    display(results_df)

    all_y_true = np.concatenate(all_y_true)
    all_y_pred = np.concatenate(all_y_pred)

    overall_acc = accuracy_score(all_y_true, all_y_pred)
    overall_macro_f1 = f1_score(all_y_true, all_y_pred, average="macro", zero_division=0)
    mean_fold_acc = results_df["test_acc"].mean()
    std_fold_acc = results_df["test_acc"].std(ddof=1) if len(results_df) > 1 else 0.0
    mean_fold_macro_f1 = results_df["test_macro_f1"].mean()
    std_fold_macro_f1 = results_df["test_macro_f1"].std(ddof=1) if len(results_df) > 1 else 0.0
    mean_epochs_ran = results_df["epochs_ran"].mean()
    mean_best_val_acc = results_df["best_val_acc"].mean()

    print("\n" + "=" * 90)
    print("LOSO SUMMARY")
    print(f"Overall window-level accuracy: {overall_acc:.4f}")
    print(f"Overall window-level macro F1: {overall_macro_f1:.4f}")
    print(f"Mean fold accuracy: {mean_fold_acc:.4f} ± {std_fold_acc:.4f}")
    print(f"Mean fold macro F1: {mean_fold_macro_f1:.4f} ± {std_fold_macro_f1:.4f}")

    channels_used = CHANNELS if channels_used is None else list(channels_used)
    cache_path_for_summary = make_dataset_cache_path(
        DATA_ROOT,
        channels_used,
        win_len_s,
        step_s,
        selected_segments=selected_segments,
        allowed_tasks=ALLOWED_TASKS,
        cache_dir=CACHE_DIR,
    )

    results_stem = make_results_stem(study_name=study_name, win_len_s=win_len_s, step_s=step_s, results_dir=results_dir)
    summary_row = pd.DataFrame([{
        "study_name": study_name,
        "win_len_s": win_len_s,
        "step_s": step_s,
        "overlap_fraction": window_overlap_fraction(win_len_s, step_s),
        "channels_used": "|".join(channels_used),
        "selected_segments": "default-tested-limb" if selected_segments is None else "|".join(selected_segments),
        "n_total_windows": len(y),
        "n_subjects": len(np.unique(groups)),
        "n_classes": len(labels),
        "cache_path": cache_path_for_summary,
        "loso_folds_ran": len(results_df),
        "overall_acc": overall_acc,
        "overall_macro_f1": overall_macro_f1,
        "mean_fold_acc": mean_fold_acc,
        "std_fold_acc": std_fold_acc,
        "mean_fold_macro_f1": mean_fold_macro_f1,
        "std_fold_macro_f1": std_fold_macro_f1,
        "mean_epochs_ran": mean_epochs_ran,
        "mean_best_val_acc": mean_best_val_acc,
    }])

    summary_csv = results_stem + "__summary.csv"
    folds_csv = results_stem + "__folds.csv"
    summary_row.to_csv(summary_csv, index=False)
    if save_per_fold_csv:
        results_df.to_csv(folds_csv, index=False)

    print(f"Saved summary CSV: {summary_csv}")
    if save_per_fold_csv:
        print(f"Saved per-fold CSV: {folds_csv}")

    return {
        "summary_row": summary_row,
        "fold_results": results_df,
        "all_y_true": all_y_true,
        "all_y_pred": all_y_pred,
        "summary_csv": summary_csv,
        "folds_csv": folds_csv if save_per_fold_csv else None,
    }


def build_segment_combination_runs(canonical_segments=None):
    if canonical_segments is None:
        canonical_segments = ["UpperArm", "ForeArm", "Hand", "Shoulder"]

    canonical_to_left = {
        "UpperArm": "LeftUpperArm",
        "ForeArm": "LeftForeArm",
        "Hand": "LeftHand",
        "Shoulder": "LeftShoulder",
    }
    canonical_to_right = {
        "UpperArm": "RightUpperArm",
        "ForeArm": "RightForeArm",
        "Hand": "RightHand",
        "Shoulder": "RightShoulder",
    }

    runs = []
    for r in range(1, len(canonical_segments) + 1):
        for combo in itertools.combinations(canonical_segments, r):
            selected_segments = []
            for name in combo:
                selected_segments.extend([canonical_to_left[name], canonical_to_right[name]])
            runs.append({
                "combo_size": r,
                "canonical_combo": list(combo),
                "selected_segments": selected_segments,
            })
    return runs


def run_segment_combination_study(
    channels=None,
    canonical_segments=None,
    win_len_s: float = WIN_LEN_S,
    step_s: float = STEP_S,
    use_dataset_cache: bool = USE_DATASET_CACHE,
    force_rebuild_dataset: bool = FORCE_REBUILD_DATASET,
    loso_max_folds=LOSO_MAX_FOLDS,
    results_dir: str = RESULTS_DIR,
):
    if channels is None:
        channels = CHANNELS

    runs = build_segment_combination_runs(canonical_segments=canonical_segments)

    print("\n" + "#" * 100)
    print("RUNNING SEGMENT COMBINATION STUDY")
    print(f"Fixed window length: {win_len_s:g}s")
    print(f"Fixed step size: {step_s:g}s")
    print(f"Channels ({len(channels)}): {channels}")
    print(f"Total segment combinations: {len(runs)}")

    combo_rows = []
    combo_outputs = {}

    for run_idx, run_cfg in enumerate(runs, start=1):
        combo_name = "__".join(run_cfg["canonical_combo"])
        study_name = (
            f"{RESULTS_BASENAME}"
            f"__combo-{_safe_name(combo_name)}"
            f"__nseg-{run_cfg['combo_size']}"
        )

        print("\n" + "=" * 100)
        print(f"Combination run {run_idx}/{len(runs)}")
        print(f"Canonical combo: {run_cfg['canonical_combo']}")
        print(f"Selected segment labels: {run_cfg['selected_segments']}")

        X, y, groups, dataset_cache_path = load_or_build_dataset(
            DATA_ROOT,
            win_len_s=win_len_s,
            step_s=step_s,
            channels=channels,
            selected_segments=run_cfg["selected_segments"],
            use_cache=use_dataset_cache,
            force_rebuild=force_rebuild_dataset,
        )
        summarize_dataset(
            X, y, groups,
            prefix=f"Segment combo ({'+'.join(run_cfg['canonical_combo'])})"
        )

        run_out = run_loso_experiment(
            X=X,
            y=y,
            groups=groups,
            study_name=study_name,
            win_len_s=win_len_s,
            step_s=step_s,
            channels_used=channels,
            selected_segments=run_cfg["selected_segments"],
            plot_first_fold_curves=False,
            loso_max_folds=loso_max_folds,
            save_per_fold_csv=SAVE_PER_FOLD_CSV,
            results_dir=results_dir,
        )

        summary_row = run_out["summary_row"].iloc[0].copy()
        summary_row["combo_size"] = run_cfg["combo_size"]
        summary_row["canonical_combo"] = "|".join(run_cfg["canonical_combo"])
        summary_row["n_segment_labels_used"] = len(run_cfg["selected_segments"])
        summary_row["dataset_cache_path"] = dataset_cache_path

        combo_rows.append(summary_row)
        combo_outputs["|".join(run_cfg["canonical_combo"])] = {
            "selected_segments": run_cfg["selected_segments"],
            "dataset_cache_path": dataset_cache_path,
            "run_out": run_out,
        }

    combo_df = pd.DataFrame(combo_rows)

    if "mean_fold_macro_f1" in combo_df.columns:
        combo_df = combo_df.sort_values(
            by=["mean_fold_macro_f1", "mean_fold_acc", "combo_size"],
            ascending=[False, False, True]
        ).reset_index(drop=True)

    os.makedirs(results_dir, exist_ok=True)
    combo_csv = os.path.join(
        results_dir,
        (
            f"{RESULTS_BASENAME}"
            f"__segment_combination_summary"
            f"__win-{win_len_s:g}s"
            f"__step-{step_s:g}s.csv"
        )
    )
    combo_df.to_csv(combo_csv, index=False)

    print("\n" + "#" * 100)
    print("SEGMENT COMBINATION STUDY COMPLETE")
    print(f"Saved combination summary CSV: {combo_csv}")
    display(combo_df)

    return combo_df, combo_outputs, combo_csv


segment_combo_results_df, segment_combo_outputs, segment_combo_csv = run_segment_combination_study(
    channels=CHANNELS,
    win_len_s=WIN_LEN_S,
    step_s=STEP_S,
)

print("\nSegment combination study complete.")
display(segment_combo_results_df)

####################################################################################################
RUNNING SEGMENT COMBINATION STUDY
Fixed window length: 4s
Fixed step size: 0.5s
Channels (2): ['angularVelocity', 'sensorFreeAcceleration']
Total segment combinations: 15

====================================================================================================
Combination run 1/15
Canonical combo: ['UpperArm']
Selected segment labels: ['LeftUpperArm', 'RightUpperArm']
No cached dataset found. Building dataset from MVNX files...
Kept files: 1420 | Skipped files (allowed but failed): 88
X: (14521, 240, 6) y: (14521,) groups: (14521,)
Saved dataset cache to: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftUpperArm_RightUpperArm__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (UpperArm) dataset loaded.
Dataset shape: (14521, 240, 6)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 6)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4022 train_acc=0.3129 | val_loss=2.0105 val_acc=0.2702 | test_loss=1.9998 test_acc=0.2966
Epoch 02 | train_loss=1.5797 train_acc=0.4185 | val_loss=1.5694 val_acc=0.3582 | test_loss=1.4902 test_acc=0.3743
Epoch 03 | train_loss=1.2663 train_acc=0.5135 | val_loss=1.4316 val_acc=0.4282 | test_loss=1.4107 test_acc=0.4033
Epoch 04 | train_loss=1.0876 train_acc=0.5869 | val_loss=1.3184 val_acc=0.5169 | test_loss=1.3668 test_acc=0.4503
Epoch 05 | train_loss=0.9484 train_acc=0.6551 | val_loss=1.3325 val_acc=0.5025 | test_loss=1.3679 test_acc=0.4467
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 06 | train_loss=0.8415 train_acc=0.6938 | val_loss=1.2313 val_acc=0.5926 | test_loss=1.2415 test_acc=0.5136
Epoch 07 | train_loss=0.7551 train_acc=0.7270 | val_loss=1.2849 val_acc=0.5889 | test_loss=1.3585 test_acc=0.5118
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.6898 train_acc=0.7459 | val_loss=1.2657 val_acc=0.6160 | test_loss=1.3765 test_acc=0.5515
Epoch 09 | train_loss=0.6254 train_acc=0.7757 | val_loss=1.1212 val_acc=0.6532 | test_loss=1.0296 test_acc=0.6438
Epoch 10 | train_loss=0.5757 train_acc=0.7896 | val_loss=1.1066 val_acc=0.6468 | test_loss=0.9690 test_acc=0.6275
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.5272 train_acc=0.8045 | val_loss=1.1476 val_acc=0.6625 | test_loss=1.1356 test_acc=0.6510
Epoch 12 | train_loss=0.4897 train_acc=0.8253 | val_loss=1.0974 val_acc=0.7161 | test_loss=1.0601 test_acc=0.7215
Epoch 13 | train_loss=0.4510 train_acc=0.8325 | val_loss=1.1995 val_acc=0.6381 | test_loss=1.2289 test_acc=0.5913
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.4183 train_acc=0.8473 | val_loss=1.1858 val_acc=0.6706 | test_loss=1.2115 test_acc=0.6510
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.3887 train_acc=0.8551 | val_loss=1.2308 val_acc=0.6679 | test_loss=1.3461 test_acc=0.6474
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 16 | train_loss=0.3673 train_acc=0.8636 | val_loss=1.1721 val_acc=0.6890 | test_loss=1.1586 test_acc=0.7034
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 17 | train_loss=0.3419 train_acc=0.8709 | val_loss=1.0574 val_acc=0.7041 | test_loss=0.9423 test_acc=0.6980
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 17.
Fold 1 complete | subject=H01 | test_acc=0.7215 | test_macro_f1=0.6360
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3877 train_acc=0.2076 | val_loss=1.9986 val_acc=0.2419 | test_loss=1.8019 test_acc=0.3534
Epoch 02 | train_loss=1.5705 train_acc=0.4190 | val_loss=1.5219 val_acc=0.3852 | test_loss=1.2959 test_acc=0.5263
Epoch 03 | train_loss=1.2509 train_acc=0.5366 | val_loss=1.3762 val_acc=0.4661 | test_loss=0.9796 test_acc=0.6278
Epoch 04 | train_loss=1.0612 train_acc=0.6195 | val_loss=1.2807 val_acc=0.5565 | test_loss=0.7764 test_acc=0.7669
Epoch 05 | train_loss=0.9251 train_acc=0.6865 | val_loss=1.2910 val_acc=0.6038 | test_loss=0.7528 test_acc=0.7632
Epoch 06 | train_loss=0.8179 train_acc=0.7124 | val_loss=1.1943 val_acc=0.6188 | test_loss=0.5909 test_acc=0.8496
Epoch 07 | train_loss=0.7416 train_acc=0.7371 | val_loss=1.2226 val_acc=0.6136 | test_loss=0.4718 test_acc=0.8797
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.6751 train_acc=0.7601 | val_loss=1.2240 val_acc=0.6585 | test_loss=0.4624 test_acc=0.8985
Epoch 09 | train_loss=0.6241 train_acc=0.7795 | val_loss=1.1039 val_acc=0.6622 | test_loss=0.4500 test_acc=0.8797
Epoch 10 | train_loss=0.5808 train_acc=0.7895 | val_loss=1.1496 val_acc=0.6768 | test_loss=0.5065 test_acc=0.8797
Epoch 11 | train_loss=0.5330 train_acc=0.8063 | val_loss=1.1785 val_acc=0.6732 | test_loss=0.4228 test_acc=0.8684
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.4872 train_acc=0.8212 | val_loss=1.1303 val_acc=0.6662 | test_loss=0.3778 test_acc=0.8910
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.4556 train_acc=0.8305 | val_loss=1.1322 val_acc=0.6805 | test_loss=0.3542 test_acc=0.9436
Epoch 14 | train_loss=0.4262 train_acc=0.8465 | val_loss=1.2040 val_acc=0.6869 | test_loss=0.5182 test_acc=0.8872
Epoch 15 | train_loss=0.3946 train_acc=0.8558 | val_loss=1.1130 val_acc=0.6915 | test_loss=0.5821 test_acc=0.8835
Epoch 16 | train_loss=0.3656 train_acc=0.8664 | val_loss=1.1920 val_acc=0.6772 | test_loss=0.2756 test_acc=0.9436
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.3396 train_acc=0.8777 | val_loss=1.1141 val_acc=0.6695 | test_loss=0.2733 test_acc=0.9398
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.3167 train_acc=0.8834 | val_loss=1.1937 val_acc=0.7086 | test_loss=0.3859 test_acc=0.8910
Epoch 19 | train_loss=0.2945 train_acc=0.8934 | val_loss=1.2471 val_acc=0.6793 | test_loss=0.2417 test_acc=0.9511
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 20 | train_loss=0.2762 train_acc=0.8988 | val_loss=1.1329 val_acc=0.7123 | test_loss=0.2801 test_acc=0.9286
Fold 2 complete | subject=H02 | test_acc=0.9286 | test_macro_f1=0.8884
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4868 train_acc=0.2079 | val_loss=2.1527 val_acc=0.2101 | test_loss=1.6799 test_acc=0.3630
Epoch 02 | train_loss=1.6154 train_acc=0.4083 | val_loss=1.7505 val_acc=0.3018 | test_loss=1.1019 test_acc=0.4918
Epoch 03 | train_loss=1.2872 train_acc=0.5328 | val_loss=1.4184 val_acc=0.4750 | test_loss=0.8777 test_acc=0.6019
Epoch 04 | train_loss=1.1139 train_acc=0.6143 | val_loss=1.3676 val_acc=0.5257 | test_loss=0.7707 test_acc=0.6674
Epoch 05 | train_loss=0.9702 train_acc=0.6609 | val_loss=1.2452 val_acc=0.5583 | test_loss=0.6253 test_acc=0.7354
Epoch 06 | train_loss=0.8678 train_acc=0.6898 | val_loss=1.2844 val_acc=0.5599 | test_loss=0.5454 test_acc=0.7635
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.7778 train_acc=0.7227 | val_loss=1.2225 val_acc=0.6329 | test_loss=0.5082 test_acc=0.7869
Epoch 08 | train_loss=0.7085 train_acc=0.7480 | val_loss=1.1998 val_acc=0.6225 | test_loss=0.4300 test_acc=0.7916
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.6486 train_acc=0.7669 | val_loss=1.3706 val_acc=0.5812 | test_loss=0.5103 test_acc=0.7658
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 10 | train_loss=0.5943 train_acc=0.7835 | val_loss=1.2103 val_acc=0.6521 | test_loss=0.3783 test_acc=0.8314
Epoch 11 | train_loss=0.5433 train_acc=0.7997 | val_loss=1.2399 val_acc=0.6561 | test_loss=0.3451 test_acc=0.8290
Epoch 12 | train_loss=0.5024 train_acc=0.8206 | val_loss=1.1714 val_acc=0.6778 | test_loss=0.2752 test_acc=0.8571
Epoch 13 | train_loss=0.4606 train_acc=0.8359 | val_loss=1.3318 val_acc=0.6539 | test_loss=0.3779 test_acc=0.8361
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.4322 train_acc=0.8472 | val_loss=1.2969 val_acc=0.6643 | test_loss=0.2951 test_acc=0.8595
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.4025 train_acc=0.8533 | val_loss=1.0628 val_acc=0.7266 | test_loss=0.2978 test_acc=0.8618
Epoch 16 | train_loss=0.3765 train_acc=0.8695 | val_loss=1.2522 val_acc=0.6894 | test_loss=0.2738 test_acc=0.8782
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.3504 train_acc=0.8739 | val_loss=1.2890 val_acc=0.6869 | test_loss=0.2012 test_acc=0.8970
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.3246 train_acc=0.8844 | val_loss=1.4015 val_acc=0.6634 | test_loss=0.2615 test_acc=0.8759
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 19 | train_loss=0.3071 train_acc=0.8872 | val_loss=1.2533 val_acc=0.6991 | test_loss=0.2038 test_acc=0.8946
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 20 | train_loss=0.2827 train_acc=0.9018 | val_loss=1.3772 val_acc=0.6860 | test_loss=0.3265 test_acc=0.8595
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 20.
Fold 3 complete | subject=H03 | test_acc=0.8618 | test_macro_f1=0.8665
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3586 train_acc=0.2050 | val_loss=1.9925 val_acc=0.2349 | test_loss=1.9036 test_acc=0.3248
Epoch 02 | train_loss=1.5281 train_acc=0.4176 | val_loss=1.6752 val_acc=0.3406 | test_loss=1.2392 test_acc=0.4526
Epoch 03 | train_loss=1.2484 train_acc=0.5133 | val_loss=1.4694 val_acc=0.4246 | test_loss=1.0023 test_acc=0.5146
Epoch 04 | train_loss=1.1006 train_acc=0.5812 | val_loss=1.3437 val_acc=0.5082 | test_loss=0.8431 test_acc=0.6460
Epoch 05 | train_loss=0.9645 train_acc=0.6357 | val_loss=1.3453 val_acc=0.5296 | test_loss=0.7563 test_acc=0.6898
Epoch 06 | train_loss=0.8635 train_acc=0.6771 | val_loss=1.2728 val_acc=0.5611 | test_loss=0.6925 test_acc=0.6971
Epoch 07 | train_loss=0.7791 train_acc=0.7150 | val_loss=1.2770 val_acc=0.5525 | test_loss=0.7027 test_acc=0.6642
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.7108 train_acc=0.7420 | val_loss=1.3144 val_acc=0.5586 | test_loss=0.6470 test_acc=0.6715
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.6504 train_acc=0.7631 | val_loss=1.2017 val_acc=0.6203 | test_loss=0.5816 test_acc=0.7007
Epoch 10 | train_loss=0.6020 train_acc=0.7825 | val_loss=1.2952 val_acc=0.5831 | test_loss=0.5458 test_acc=0.7482
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.5519 train_acc=0.7986 | val_loss=1.3860 val_acc=0.5501 | test_loss=0.6511 test_acc=0.7153
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.5100 train_acc=0.8115 | val_loss=1.3266 val_acc=0.5703 | test_loss=0.6915 test_acc=0.6460
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 13 | train_loss=0.4718 train_acc=0.8327 | val_loss=1.2727 val_acc=0.6393 | test_loss=0.4857 test_acc=0.8175
Epoch 14 | train_loss=0.4370 train_acc=0.8430 | val_loss=1.3638 val_acc=0.5968 | test_loss=0.4753 test_acc=0.7628
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.4025 train_acc=0.8607 | val_loss=1.2006 val_acc=0.6781 | test_loss=0.4111 test_acc=0.8321
Epoch 16 | train_loss=0.3776 train_acc=0.8666 | val_loss=1.2345 val_acc=0.6503 | test_loss=0.3925 test_acc=0.8248
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.3438 train_acc=0.8791 | val_loss=1.2549 val_acc=0.6683 | test_loss=0.3581 test_acc=0.8504
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.3248 train_acc=0.8878 | val_loss=1.2742 val_acc=0.6637 | test_loss=0.3764 test_acc=0.8248
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 19 | train_loss=0.3011 train_acc=0.8938 | val_loss=1.2863 val_acc=0.6588 | test_loss=0.3748 test_acc=0.8540
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 20 | train_loss=0.2862 train_acc=0.9026 | val_loss=1.4508 val_acc=0.6051 | test_loss=0.5035 test_acc=0.7628
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 20.
Fold 4 complete | subject=H04 | test_acc=0.8321 | test_macro_f1=0.7999
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.5416 train_acc=0.2210 | val_loss=2.1684 val_acc=0.2034 | test_loss=1.7301 test_acc=0.3231
Epoch 02 | train_loss=1.6475 train_acc=0.3956 | val_loss=1.6284 val_acc=0.3183 | test_loss=1.3192 test_acc=0.3928
Epoch 03 | train_loss=1.2882 train_acc=0.4842 | val_loss=1.6010 val_acc=0.3937 | test_loss=1.1366 test_acc=0.4206
Epoch 04 | train_loss=1.0910 train_acc=0.5813 | val_loss=1.4782 val_acc=0.4606 | test_loss=1.0307 test_acc=0.4791
Epoch 05 | train_loss=0.9490 train_acc=0.6460 | val_loss=1.2894 val_acc=0.5119 | test_loss=0.9416 test_acc=0.5097
Epoch 06 | train_loss=0.8392 train_acc=0.7011 | val_loss=1.3207 val_acc=0.5467 | test_loss=0.9088 test_acc=0.5348
Epoch 07 | train_loss=0.7555 train_acc=0.7251 | val_loss=1.2601 val_acc=0.5831 | test_loss=0.8659 test_acc=0.5794
Epoch 08 | train_loss=0.6841 train_acc=0.7569 | val_loss=1.3327 val_acc=0.5919 | test_loss=0.7965 test_acc=0.6156
Epoch 09 | train_loss=0.6214 train_acc=0.7757 | val_loss=1.2096 val_acc=0.6069 | test_loss=0.8269 test_acc=0.6017
Epoch 10 | train_loss=0.5677 train_acc=0.8006 | val_loss=1.3815 val_acc=0.5764 | test_loss=0.8691 test_acc=0.5487
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.5194 train_acc=0.8152 | val_loss=1.2178 val_acc=0.6451 | test_loss=0.8308 test_acc=0.5905
Epoch 12 | train_loss=0.4804 train_acc=0.8286 | val_loss=1.1746 val_acc=0.6378 | test_loss=0.7795 test_acc=0.6379
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.4423 train_acc=0.8434 | val_loss=1.2750 val_acc=0.6203 | test_loss=0.9536 test_acc=0.5738
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.4056 train_acc=0.8551 | val_loss=1.2393 val_acc=0.6564 | test_loss=0.6681 test_acc=0.6908
Epoch 15 | train_loss=0.3814 train_acc=0.8618 | val_loss=1.2965 val_acc=0.6313 | test_loss=0.9565 test_acc=0.5655
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.3495 train_acc=0.8784 | val_loss=1.2004 val_acc=0.6808 | test_loss=0.7527 test_acc=0.6769
Epoch 17 | train_loss=0.3253 train_acc=0.8871 | val_loss=1.3427 val_acc=0.6362 | test_loss=0.8899 test_acc=0.6017
  No validation improvement greater than 0.0020. Patience: 1/5

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,17,0.716103,0.721519,0.635955
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,20,0.712279,0.928571,0.888440
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,20,0.726634,0.861827,0.866514
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,20,0.678070,0.832117,0.799941
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,20,0.680819,0.676880,0.661477
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,20,0.714111,0.659357,0.623524
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,18,0.700977,0.857520,0.777407
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,19,0.676848,0.781716,0.776813
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,20,0.645388,0.361437,0.390884
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,13,0.534859,0.550000,0.495396
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,20,0.622938,0.400749,0.187390
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,20,0.585418,0.624501,0.581508
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,15,0.596873,0.800481,0.838743
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,20,0.601759,0.658570,0.619257
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,19,0.586856,0.668317,0.636875
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,19,0.582458,0.617918,0.561159
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,12,0.588566,0.868852,0.648028
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,16,0.563688,0.639163,0.581098
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,18,0.575887,0.774194,0.744028
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,15,0.602993,0.667210,0.613654
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,20,0.630575,0.818636,0.754124
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,16,0.605340,0.823770,0.815422
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,13,0.595070,0.642185,0.667668
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,20,0.642312,0.850490,0.730228
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,20,0.618838,0.534579,0.428879

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.6653
Overall window-level macro F1: 0.6360
Mean fold accuracy: 0.7048 ± 0.1448
Mean fold macro F1: 0.6530 ± 0.1610
Saved summary CSV: experiment_results/segment_combination_study__combo-UpperArm__nseg-1__win-4s__step-0.5s__20260407_135729__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-UpperArm__nseg-1__win-4s__step-0.5s__20260407_135729__folds.csv

====================================================================================================
Combination run 2/15
Canonical combo: ['ForeArm']
Selected segment labels: ['LeftForeArm', 'RightForeArm']
No cached dataset found. Building dataset from MVNX files...
Kept files: 1420 | Skipped files (allowed but failed): 88
X: (14521, 240, 6) y: (14521,) groups: (14521,)
Saved dataset cache to: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftForeArm_RightForeArm__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (ForeArm) dataset loaded.
Dataset shape: (14521, 240, 6)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 6)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3210 train_acc=0.2368 | val_loss=1.8419 val_acc=0.2595 | test_loss=1.5489 test_acc=0.3165
Epoch 02 | train_loss=1.3203 train_acc=0.4568 | val_loss=1.4047 val_acc=0.3907 | test_loss=1.2407 test_acc=0.3635
Epoch 03 | train_loss=0.9895 train_acc=0.5973 | val_loss=1.2363 val_acc=0.4848 | test_loss=1.0756 test_acc=0.4647
Epoch 04 | train_loss=0.7926 train_acc=0.6962 | val_loss=1.1333 val_acc=0.5601 | test_loss=1.0164 test_acc=0.6076
Epoch 05 | train_loss=0.6613 train_acc=0.7614 | val_loss=1.0543 val_acc=0.6250 | test_loss=0.8264 test_acc=0.6311
Epoch 06 | train_loss=0.5765 train_acc=0.7939 | val_loss=1.0509 val_acc=0.6502 | test_loss=0.9350 test_acc=0.6944
Epoch 07 | train_loss=0.5072 train_acc=0.8211 | val_loss=0.9730 val_acc=0.6853 | test_loss=0.8754 test_acc=0.7233
Epoch 08 | train_loss=0.4552 train_acc=0.8384 | val_loss=0.8940 val_acc=0.6994 | test_loss=0.7487 test_acc=0.7089
Epoch 09 | train_loss=0.4151 train_acc=0.8517 | val_loss=0.9028 val_acc=0.6927 | test_loss=0.6851 test_acc=0.7034
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.3719 train_acc=0.8682 | val_loss=0.9342 val_acc=0.7158 | test_loss=0.8451 test_acc=0.7559
Epoch 11 | train_loss=0.3431 train_acc=0.8804 | val_loss=1.0338 val_acc=0.7392 | test_loss=0.8912 test_acc=0.7866
Epoch 12 | train_loss=0.3138 train_acc=0.8892 | val_loss=0.9829 val_acc=0.7195 | test_loss=0.8912 test_acc=0.7758
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.2888 train_acc=0.8999 | val_loss=0.8491 val_acc=0.7010 | test_loss=0.8097 test_acc=0.7288
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.2701 train_acc=0.9024 | val_loss=0.9207 val_acc=0.7195 | test_loss=0.8457 test_acc=0.7703
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 15 | train_loss=0.2480 train_acc=0.9128 | val_loss=0.9062 val_acc=0.7369 | test_loss=0.7810 test_acc=0.7812
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 16 | train_loss=0.2329 train_acc=0.9191 | val_loss=0.7987 val_acc=0.7439 | test_loss=0.7291 test_acc=0.7342
Epoch 17 | train_loss=0.2156 train_acc=0.9266 | val_loss=0.8616 val_acc=0.7292 | test_loss=0.9080 test_acc=0.7288
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 18 | train_loss=0.1962 train_acc=0.9317 | val_loss=0.7527 val_acc=0.7683 | test_loss=0.6992 test_acc=0.7884
Epoch 19 | train_loss=0.1818 train_acc=0.9396 | val_loss=0.8731 val_acc=0.7486 | test_loss=0.7261 test_acc=0.7613
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 20 | train_loss=0.1700 train_acc=0.9419 | val_loss=0.8389 val_acc=0.7677 | test_loss=0.7284 test_acc=0.7703
  No validation improvement greater than 0.0020. Patience: 2/5
Fold 1 complete | subject=H01 | test_acc=0.7884 | test_macro_f1=0.7444
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2102 train_acc=0.3528 | val_loss=1.7412 val_acc=0.3164 | test_loss=1.2376 test_acc=0.3609
Epoch 02 | train_loss=1.2644 train_acc=0.4913 | val_loss=1.3896 val_acc=0.4203 | test_loss=0.8574 test_acc=0.5714
Epoch 03 | train_loss=0.9614 train_acc=0.6046 | val_loss=1.2810 val_acc=0.4783 | test_loss=0.6069 test_acc=0.7256
Epoch 04 | train_loss=0.7772 train_acc=0.7068 | val_loss=1.1324 val_acc=0.5761 | test_loss=0.5046 test_acc=0.8008
Epoch 05 | train_loss=0.6413 train_acc=0.7692 | val_loss=1.0994 val_acc=0.6176 | test_loss=0.3473 test_acc=0.8609
Epoch 06 | train_loss=0.5526 train_acc=0.8081 | val_loss=0.9854 val_acc=0.6903 | test_loss=0.3489 test_acc=0.8872
Epoch 07 | train_loss=0.4778 train_acc=0.8315 | val_loss=0.9865 val_acc=0.6836 | test_loss=0.3170 test_acc=0.8759
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.4297 train_acc=0.8517 | val_loss=0.9742 val_acc=0.7065 | test_loss=0.3642 test_acc=0.8421
Epoch 09 | train_loss=0.3877 train_acc=0.8691 | val_loss=0.9522 val_acc=0.7071 | test_loss=0.3170 test_acc=0.8759
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.3516 train_acc=0.8781 | val_loss=0.9254 val_acc=0.7150 | test_loss=0.2888 test_acc=0.8835
Epoch 11 | train_loss=0.3205 train_acc=0.8894 | val_loss=0.9191 val_acc=0.7355 | test_loss=0.2742 test_acc=0.8797
Epoch 12 | train_loss=0.2908 train_acc=0.8990 | val_loss=0.9752 val_acc=0.6888 | test_loss=0.2302 test_acc=0.8835
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.2688 train_acc=0.9101 | val_loss=0.9604 val_acc=0.7276 | test_loss=0.3775 test_acc=0.8459
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.2488 train_acc=0.9150 | val_loss=0.9682 val_acc=0.7489 | test_loss=0.2472 test_acc=0.8797
Epoch 15 | train_loss=0.2274 train_acc=0.9230 | val_loss=1.0898 val_acc=0.7413 | test_loss=0.2318 test_acc=0.9060
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.2144 train_acc=0.9301 | val_loss=0.9769 val_acc=0.7358 | test_loss=0.1867 test_acc=0.9173
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 17 | train_loss=0.1984 train_acc=0.9332 | val_loss=0.8958 val_acc=0.7557 | test_loss=0.1943 test_acc=0.9060
Epoch 18 | train_loss=0.1804 train_acc=0.9385 | val_loss=0.8741 val_acc=0.7670 | test_loss=0.2689 test_acc=0.8985
Epoch 19 | train_loss=0.1643 train_acc=0.9450 | val_loss=1.0397 val_acc=0.7285 | test_loss=0.1369 test_acc=0.9248
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 20 | train_loss=0.1546 train_acc=0.9497 | val_loss=0.9074 val_acc=0.7596 | test_loss=0.2314 test_acc=0.9023
  No validation improvement greater than 0.0020. Patience: 2/5
Fold 2 complete | subject=H02 | test_acc=0.8985 | test_macro_f1=0.8885
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2112 train_acc=0.2655 | val_loss=1.7029 val_acc=0.3054 | test_loss=1.2894 test_acc=0.5082
Epoch 02 | train_loss=1.3032 train_acc=0.4809 | val_loss=1.4250 val_acc=0.3934 | test_loss=0.7857 test_acc=0.6651
Epoch 03 | train_loss=0.9790 train_acc=0.6205 | val_loss=1.2910 val_acc=0.5147 | test_loss=0.5177 test_acc=0.7447
Epoch 04 | train_loss=0.7860 train_acc=0.7047 | val_loss=1.3093 val_acc=0.5559 | test_loss=0.5024 test_acc=0.7611
Epoch 05 | train_loss=0.6611 train_acc=0.7731 | val_loss=1.1570 val_acc=0.5913 | test_loss=0.4026 test_acc=0.8407
Epoch 06 | train_loss=0.5704 train_acc=0.7970 | val_loss=1.2058 val_acc=0.6115 | test_loss=0.4025 test_acc=0.8735
Epoch 07 | train_loss=0.5048 train_acc=0.8251 | val_loss=1.0852 val_acc=0.6918 | test_loss=0.3103 test_acc=0.8735
Epoch 08 | train_loss=0.4504 train_acc=0.8426 | val_loss=0.9868 val_acc=0.7162 | test_loss=0.2074 test_acc=0.9227
Epoch 09 | train_loss=0.4078 train_acc=0.8553 | val_loss=1.0829 val_acc=0.6891 | test_loss=0.3461 test_acc=0.8829
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.3724 train_acc=0.8711 | val_loss=1.1087 val_acc=0.7147 | test_loss=0.2990 test_acc=0.9063
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.3417 train_acc=0.8812 | val_loss=1.0759 val_acc=0.7422 | test_loss=0.2492 test_acc=0.9227
Epoch 12 | train_loss=0.3109 train_acc=0.8884 | val_loss=1.1355 val_acc=0.7312 | test_loss=0.3358 test_acc=0.8782
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.2821 train_acc=0.9032 | val_loss=0.9964 val_acc=0.7294 | test_loss=0.2207 test_acc=0.9251
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.2655 train_acc=0.9079 | val_loss=1.0610 val_acc=0.7450 | test_loss=0.2399 test_acc=0.9251
Epoch 15 | train_loss=0.2405 train_acc=0.9156 | val_loss=1.0073 val_acc=0.7569 | test_loss=0.2111 test_acc=0.9415
Epoch 16 | train_loss=0.2245 train_acc=0.9236 | val_loss=0.9990 val_acc=0.7523 | test_loss=0.1786 test_acc=0.9508
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.2052 train_acc=0.9311 | val_loss=1.1122 val_acc=0.7477 | test_loss=0.2569 test_acc=0.9321
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.1933 train_acc=0.9329 | val_loss=0.9061 val_acc=0.7700 | test_loss=0.1367 test_acc=0.9508
Epoch 19 | train_loss=0.1746 train_acc=0.9407 | val_loss=1.0124 val_acc=0.7663 | test_loss=0.2179 test_acc=0.9485
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 20 | train_loss=0.1647 train_acc=0.9441 | val_loss=1.1121 val_acc=0.7474 | test_loss=0.1906 test_acc=0.9391
  No validation improvement greater than 0.0020. Patience: 2/5
Fold 3 complete | subject=H03 | test_acc=0.9508 | test_macro_f1=0.9540
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.5118 train_acc=0.1510 | val_loss=1.9149 val_acc=0.3009 | test_loss=1.7197 test_acc=0.3905
Epoch 02 | train_loss=1.3299 train_acc=0.4822 | val_loss=1.3776 val_acc=0.3980 | test_loss=1.0515 test_acc=0.6460
Epoch 03 | train_loss=0.9481 train_acc=0.6129 | val_loss=1.2783 val_acc=0.5409 | test_loss=0.7824 test_acc=0.7263
Epoch 04 | train_loss=0.7640 train_acc=0.7078 | val_loss=1.1256 val_acc=0.6188 | test_loss=0.5919 test_acc=0.8394
Epoch 05 | train_loss=0.6488 train_acc=0.7669 | val_loss=1.0899 val_acc=0.6316 | test_loss=0.4980 test_acc=0.8431
Epoch 06 | train_loss=0.5585 train_acc=0.7944 | val_loss=1.1201 val_acc=0.6717 | test_loss=0.4630 test_acc=0.9051
Epoch 07 | train_loss=0.4924 train_acc=0.8282 | val_loss=0.9417 val_acc=0.6677 | test_loss=0.4160 test_acc=0.8358
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.4392 train_acc=0.8421 | val_loss=0.8856 val_acc=0.7196 | test_loss=0.3614 test_acc=0.9124
Epoch 09 | train_loss=0.3895 train_acc=0.8618 | val_loss=0.9349 val_acc=0.7013 | test_loss=0.3345 test_acc=0.9197
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.3537 train_acc=0.8756 | val_loss=0.9218 val_acc=0.7498 | test_loss=0.3281 test_acc=0.9416
Epoch 11 | train_loss=0.3231 train_acc=0.8885 | val_loss=0.9065 val_acc=0.7453 | test_loss=0.2891 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.3011 train_acc=0.8959 | val_loss=1.0219 val_acc=0.7343 | test_loss=0.3144 test_acc=0.9416
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.2739 train_acc=0.9070 | val_loss=0.9704 val_acc=0.7129 | test_loss=0.2958 test_acc=0.9453
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 14 | train_loss=0.2517 train_acc=0.9127 | val_loss=0.8318 val_acc=0.7740 | test_loss=0.2711 test_acc=0.9453
Epoch 15 | train_loss=0.2319 train_acc=0.9193 | val_loss=0.9367 val_acc=0.7153 | test_loss=0.2515 test_acc=0.9380
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.2089 train_acc=0.9267 | val_loss=0.8346 val_acc=0.7407 | test_loss=0.2553 test_acc=0.9526
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 17 | train_loss=0.1982 train_acc=0.9327 | val_loss=0.9464 val_acc=0.7297 | test_loss=0.2613 test_acc=0.9635
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 18 | train_loss=0.1840 train_acc=0.9385 | val_loss=0.9629 val_acc=0.7309 | test_loss=0.2124 test_acc=0.9745
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 19 | train_loss=0.1708 train_acc=0.9398 | val_loss=0.8231 val_acc=0.7700 | test_loss=0.2178 test_acc=0.9562
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 19.
Fold 4 complete | subject=H04 | test_acc=0.9453 | test_macro_f1=0.8182
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2001 train_acc=0.2393 | val_loss=1.6857 val_acc=0.2618 | test_loss=1.3281 test_acc=0.2841
Epoch 02 | train_loss=1.2613 train_acc=0.4780 | val_loss=1.2634 val_acc=0.4530 | test_loss=0.9153 test_acc=0.5070
Epoch 03 | train_loss=0.9346 train_acc=0.6319 | val_loss=1.2016 val_acc=0.5156 | test_loss=0.7912 test_acc=0.5738
Epoch 04 | train_loss=0.7591 train_acc=0.7174 | val_loss=1.1107 val_acc=0.6118 | test_loss=0.7192 test_acc=0.6490
Epoch 05 | train_loss=0.6387 train_acc=0.7774 | val_loss=1.0986 val_acc=0.6616 | test_loss=0.6646 test_acc=0.6992
Epoch 06 | train_loss=0.5554 train_acc=0.8102 | val_loss=1.0364 val_acc=0.6732 | test_loss=0.6088 test_acc=0.7187
Epoch 07 | train_loss=0.4898 train_acc=0.8359 | val_loss=0.9870 val_acc=0.6701 | test_loss=0.5986 test_acc=0.7019
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.4276 train_acc=0.8565 | val_loss=1.0317 val_acc=0.6817 | test_loss=0.6462 test_acc=0.6908
Epoch 09 | train_loss=0.3919 train_acc=0.8684 | val_loss=0.9297 val_acc=0.7098 | test_loss=0.5108 test_acc=0.7131
Epoch 10 | train_loss=0.3550 train_acc=0.8836 | val_loss=1.0257 val_acc=0.6930 | test_loss=0.5285 test_acc=0.8134
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.3202 train_acc=0.8970 | val_loss=0.8734 val_acc=0.7474 | test_loss=0.4215 test_acc=0.7799
Epoch 12 | train_loss=0.2925 train_acc=0.9041 | val_loss=1.0714 val_acc=0.7010 | test_loss=0.4874 test_acc=0.7354
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.2681 train_acc=0.9139 | val_loss=0.9747 val_acc=0.7343 | test_loss=0.4092 test_acc=0.7883
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.2460 train_acc=0.9183 | val_loss=1.0371 val_acc=0.7153 | test_loss=0.3822 test_acc=0.8245
  No validation improvement greater than 0.0020. Patience: 3/5

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,20,0.768329,0.788427,0.744433
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,20,0.766952,0.898496,0.888543
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,20,0.770006,0.950820,0.953961
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,19,0.773977,0.945255,0.818151
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,16,0.747404,0.779944,0.790416
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,20,0.721136,0.783626,0.790745
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,20,0.769395,0.957784,0.939951
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,20,0.755956,0.910448,0.901780
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,20,0.792608,0.464076,0.436141
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,20,0.663119,0.769318,0.721632
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,14,0.647153,0.456929,0.275432
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,20,0.672432,0.668442,0.697690
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,20,0.660396,0.985577,0.985315
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,20,0.669924,0.827260,0.797248
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,14,0.653311,0.818482,0.779840
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,20,0.657220,0.739130,0.749243
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,20,0.646714,0.967213,0.829979
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,20,0.661277,0.676108,0.640969
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,20,0.695887,0.919355,0.932465
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,20,0.718016,0.773246,0.748320
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,20,0.713028,0.926789,0.901366
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,17,0.709214,0.911885,0.930597
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,19,0.705692,0.650659,0.685810
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,20,0.727406,0.965686,0.958613
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,20,0.724178,0.813084,0.741355

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.7753
Overall window-level macro F1: 0.7623
Mean fold accuracy: 0.8139 ± 0.1460
Mean fold macro F1: 0.7856 ± 0.1629
Saved summary CSV: experiment_results/segment_combination_study__combo-ForeArm__nseg-1__win-4s__step-0.5s__20260407_141642__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-ForeArm__nseg-1__win-4s__step-0.5s__20260407_141642__folds.csv

====================================================================================================
Combination run 3/15
Canonical combo: ['Hand']
Selected segment labels: ['LeftHand', 'RightHand']
No cached dataset found. Building dataset from MVNX files...
Kept files: 1420 | Skipped files (allowed but failed): 88
X: (14521, 240, 6) y: (14521,) groups: (14521,)
Saved dataset cache to: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftHand_RightHand__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (Hand) dataset loaded.
Dataset shape: (14521, 240, 6)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 6)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2137 train_acc=0.2613 | val_loss=1.6510 val_acc=0.3217 | test_loss=1.3895 test_acc=0.3382
Epoch 02 | train_loss=1.3065 train_acc=0.5052 | val_loss=1.3397 val_acc=0.4801 | test_loss=0.9490 test_acc=0.4250
Epoch 03 | train_loss=0.9522 train_acc=0.6845 | val_loss=1.0627 val_acc=0.6260 | test_loss=0.6703 test_acc=0.6148
Epoch 04 | train_loss=0.7546 train_acc=0.7559 | val_loss=1.0399 val_acc=0.7061 | test_loss=0.4828 test_acc=0.7523
Epoch 05 | train_loss=0.6254 train_acc=0.8023 | val_loss=0.9702 val_acc=0.7134 | test_loss=0.4039 test_acc=0.7396
Epoch 06 | train_loss=0.5315 train_acc=0.8353 | val_loss=0.8987 val_acc=0.7503 | test_loss=0.3844 test_acc=0.7595
Epoch 07 | train_loss=0.4607 train_acc=0.8537 | val_loss=0.9766 val_acc=0.7288 | test_loss=0.3525 test_acc=0.7613
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.4131 train_acc=0.8633 | val_loss=0.8861 val_acc=0.7456 | test_loss=0.3413 test_acc=0.7649
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.3653 train_acc=0.8838 | val_loss=0.9359 val_acc=0.7523 | test_loss=0.3018 test_acc=0.8373
Epoch 10 | train_loss=0.3294 train_acc=0.8925 | val_loss=0.9177 val_acc=0.7489 | test_loss=0.2962 test_acc=0.7939
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.3026 train_acc=0.9022 | val_loss=0.9537 val_acc=0.7707 | test_loss=0.2492 test_acc=0.8463
Epoch 12 | train_loss=0.2692 train_acc=0.9137 | val_loss=0.9840 val_acc=0.7606 | test_loss=0.2752 test_acc=0.8553
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.2511 train_acc=0.9155 | val_loss=0.8837 val_acc=0.7683 | test_loss=0.2349 test_acc=0.8517
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.2274 train_acc=0.9273 | val_loss=0.9774 val_acc=0.7630 | test_loss=0.2527 test_acc=0.8318
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 15 | train_loss=0.2091 train_acc=0.9287 | val_loss=0.9270 val_acc=0.7697 | test_loss=0.2265 test_acc=0.8770
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 16 | train_loss=0.1899 train_acc=0.9419 | val_loss=0.7642 val_acc=0.7918 | test_loss=0.2556 test_acc=0.8535
Epoch 17 | train_loss=0.1752 train_acc=0.9426 | val_loss=0.9548 val_acc=0.7814 | test_loss=0.1736 test_acc=0.9132
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 18 | train_loss=0.1608 train_acc=0.9481 | val_loss=0.9062 val_acc=0.7777 | test_loss=0.2064 test_acc=0.8734
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 19 | train_loss=0.1496 train_acc=0.9524 | val_loss=0.8830 val_acc=0.7646 | test_loss=0.2618 test_acc=0.8445
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 20 | train_loss=0.1347 train_acc=0.9564 | val_loss=0.8613 val_acc=0.7841 | test_loss=0.1792 test_acc=0.8951
  No validation improvement greater than 0.0020. Patience: 4/5
Fold 1 complete | subject=H01 | test_acc=0.8535 | test_macro_f1=0.8319
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2036 train_acc=0.2493 | val_loss=1.7091 val_acc=0.3409 | test_loss=1.1847 test_acc=0.4023
Epoch 02 | train_loss=1.3112 train_acc=0.5010 | val_loss=1.4477 val_acc=0.4322 | test_loss=0.8014 test_acc=0.6128
Epoch 03 | train_loss=0.9555 train_acc=0.6710 | val_loss=1.1650 val_acc=0.6173 | test_loss=0.5206 test_acc=0.7707
Epoch 04 | train_loss=0.7628 train_acc=0.7505 | val_loss=1.1348 val_acc=0.6506 | test_loss=0.4051 test_acc=0.8346
Epoch 05 | train_loss=0.6523 train_acc=0.7929 | val_loss=0.9516 val_acc=0.7108 | test_loss=0.3885 test_acc=0.8571
Epoch 06 | train_loss=0.5540 train_acc=0.8238 | val_loss=0.8914 val_acc=0.7511 | test_loss=0.3103 test_acc=0.9098
Epoch 07 | train_loss=0.4838 train_acc=0.8460 | val_loss=0.8836 val_acc=0.7462 | test_loss=0.2608 test_acc=0.9211
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.4301 train_acc=0.8640 | val_loss=0.9576 val_acc=0.7230 | test_loss=0.2472 test_acc=0.9173
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.3860 train_acc=0.8733 | val_loss=0.8742 val_acc=0.7392 | test_loss=0.2220 test_acc=0.9361
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 10 | train_loss=0.3532 train_acc=0.8848 | val_loss=0.8353 val_acc=0.7584 | test_loss=0.2064 test_acc=0.9248
Epoch 11 | train_loss=0.3175 train_acc=0.8972 | val_loss=0.8110 val_acc=0.7816 | test_loss=0.2380 test_acc=0.9248
Epoch 12 | train_loss=0.2915 train_acc=0.9046 | val_loss=0.8693 val_acc=0.7630 | test_loss=0.2587 test_acc=0.9361
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.2620 train_acc=0.9140 | val_loss=0.7998 val_acc=0.7874 | test_loss=0.2053 test_acc=0.9286
Epoch 14 | train_loss=0.2410 train_acc=0.9238 | val_loss=0.7512 val_acc=0.7859 | test_loss=0.1660 test_acc=0.9286
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.2209 train_acc=0.9265 | val_loss=0.8331 val_acc=0.7642 | test_loss=0.1598 test_acc=0.9361
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 16 | train_loss=0.2052 train_acc=0.9314 | val_loss=0.7677 val_acc=0.7868 | test_loss=0.2268 test_acc=0.9211
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 17 | train_loss=0.1886 train_acc=0.9374 | val_loss=0.8411 val_acc=0.7654 | test_loss=0.2156 test_acc=0.9286
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 18 | train_loss=0.1718 train_acc=0.9427 | val_loss=0.8826 val_acc=0.7502 | test_loss=0.1562 test_acc=0.9549
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 18.
Fold 2 complete | subject=H02 | test_acc=0.9286 | test_macro_f1=0.9117
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3880 train_acc=0.2314 | val_loss=1.8794 val_acc=0.2300 | test_loss=1.4524 test_acc=0.3489
Epoch 02 | train_loss=1.3598 train_acc=0.4359 | val_loss=1.3931 val_acc=0.3952 | test_loss=0.9213 test_acc=0.4965
Epoch 03 | train_loss=1.0276 train_acc=0.5997 | val_loss=1.1875 val_acc=0.5483 | test_loss=0.6219 test_acc=0.7705
Epoch 04 | train_loss=0.8381 train_acc=0.6991 | val_loss=1.0420 val_acc=0.6567 | test_loss=0.4501 test_acc=0.8384
Epoch 05 | train_loss=0.7002 train_acc=0.7667 | val_loss=1.0224 val_acc=0.6674 | test_loss=0.3688 test_acc=0.8735
Epoch 06 | train_loss=0.5995 train_acc=0.8055 | val_loss=1.0728 val_acc=0.6643 | test_loss=0.4152 test_acc=0.8689
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.5181 train_acc=0.8348 | val_loss=1.0415 val_acc=0.6936 | test_loss=0.3759 test_acc=0.8595
Epoch 08 | train_loss=0.4569 train_acc=0.8514 | val_loss=1.0264 val_acc=0.7043 | test_loss=0.2988 test_acc=0.9110
Epoch 09 | train_loss=0.4060 train_acc=0.8704 | val_loss=0.9471 val_acc=0.7199 | test_loss=0.2701 test_acc=0.9063
Epoch 10 | train_loss=0.3609 train_acc=0.8820 | val_loss=0.9626 val_acc=0.7217 | test_loss=0.2382 test_acc=0.9204
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.3265 train_acc=0.8926 | val_loss=0.8942 val_acc=0.7523 | test_loss=0.2224 test_acc=0.9321
Epoch 12 | train_loss=0.2977 train_acc=0.9015 | val_loss=0.9811 val_acc=0.7330 | test_loss=0.2388 test_acc=0.8970
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.2708 train_acc=0.9113 | val_loss=1.0228 val_acc=0.7077 | test_loss=0.2491 test_acc=0.8852
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.2478 train_acc=0.9171 | val_loss=0.9812 val_acc=0.7169 | test_loss=0.2190 test_acc=0.8993
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 15 | train_loss=0.2306 train_acc=0.9210 | val_loss=0.8211 val_acc=0.7682 | test_loss=0.1023 test_acc=0.9555
Epoch 16 | train_loss=0.2052 train_acc=0.9350 | val_loss=0.9613 val_acc=0.7511 | test_loss=0.1644 test_acc=0.9344
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.1958 train_acc=0.9348 | val_loss=0.9787 val_acc=0.7456 | test_loss=0.1857 test_acc=0.9204
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.1744 train_acc=0.9423 | val_loss=0.9158 val_acc=0.7489 | test_loss=0.1504 test_acc=0.9508
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 19 | train_loss=0.1609 train_acc=0.9467 | val_loss=0.9798 val_acc=0.7807 | test_loss=0.1634 test_acc=0.9508
Epoch 20 | train_loss=0.1544 train_acc=0.9485 | val_loss=0.9543 val_acc=0.7523 | test_loss=0.1621 test_acc=0.9415
  No validation improvement greater than 0.0020. Patience: 1/5
Fold 3 complete | subject=H03 | test_acc=0.9508 | test_macro_f1=0.9309
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3352 train_acc=0.2608 | val_loss=1.8329 val_acc=0.2538 | test_loss=1.5360 test_acc=0.3467
Epoch 02 | train_loss=1.3220 train_acc=0.5018 | val_loss=1.3028 val_acc=0.5122 | test_loss=0.7938 test_acc=0.7226
Epoch 03 | train_loss=0.9508 train_acc=0.6894 | val_loss=1.0425 val_acc=0.6820 | test_loss=0.5029 test_acc=0.8832
Epoch 04 | train_loss=0.7323 train_acc=0.7738 | val_loss=1.0614 val_acc=0.6976 | test_loss=0.5439 test_acc=0.8759
Epoch 05 | train_loss=0.6160 train_acc=0.8100 | val_loss=1.0683 val_acc=0.7022 | test_loss=0.3975 test_acc=0.8796
Epoch 06 | train_loss=0.5305 train_acc=0.8355 | val_loss=0.9816 val_acc=0.7025 | test_loss=0.2584 test_acc=0.9489
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.4647 train_acc=0.8546 | val_loss=0.9294 val_acc=0.7431 | test_loss=0.2198 test_acc=0.9453
Epoch 08 | train_loss=0.4167 train_acc=0.8670 | val_loss=1.0193 val_acc=0.7162 | test_loss=0.2768 test_acc=0.9234
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.3764 train_acc=0.8799 | val_loss=0.9123 val_acc=0.7523 | test_loss=0.1771 test_acc=0.9489
Epoch 10 | train_loss=0.3379 train_acc=0.8905 | val_loss=0.9133 val_acc=0.7233 | test_loss=0.2632 test_acc=0.9453
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.3047 train_acc=0.9016 | val_loss=0.8650 val_acc=0.7529 | test_loss=0.1855 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.2777 train_acc=0.9087 | val_loss=0.9692 val_acc=0.7495 | test_loss=0.1587 test_acc=0.9599
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 13 | train_loss=0.2504 train_acc=0.9177 | val_loss=0.8447 val_acc=0.7776 | test_loss=0.1035 test_acc=0.9854
Epoch 14 | train_loss=0.2331 train_acc=0.9253 | val_loss=0.9454 val_acc=0.7660 | test_loss=0.1362 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.2137 train_acc=0.9297 | val_loss=0.8539 val_acc=0.7786 | test_loss=0.1062 test_acc=0.9818
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 16 | train_loss=0.1932 train_acc=0.9343 | val_loss=0.8993 val_acc=0.7624 | test_loss=0.1742 test_acc=0.9635
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 17 | train_loss=0.1786 train_acc=0.9425 | val_loss=0.9490 val_acc=0.7285 | test_loss=0.2825 test_acc=0.9270
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 18 | train_loss=0.1635 train_acc=0.9460 | val_loss=0.9357 val_acc=0.7740 | test_loss=0.0901 test_acc=0.9818
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 18.
Fold 4 complete | subject=H04 | test_acc=0.9854 | test_macro_f1=0.9748
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4328 train_acc=0.2029 | val_loss=2.0263 val_acc=0.2272 | test_loss=1.6781 test_acc=0.2563
Epoch 02 | train_loss=1.4006 train_acc=0.4837 | val_loss=1.3454 val_acc=0.4456 | test_loss=1.0639 test_acc=0.5014
Epoch 03 | train_loss=0.9962 train_acc=0.6406 | val_loss=1.0647 val_acc=0.6145 | test_loss=0.7954 test_acc=0.6462
Epoch 04 | train_loss=0.7718 train_acc=0.7495 | val_loss=0.9681 val_acc=0.6973 | test_loss=0.6995 test_acc=0.6992
Epoch 05 | train_loss=0.6296 train_acc=0.8094 | val_loss=1.0251 val_acc=0.7257 | test_loss=0.7034 test_acc=0.7632
Epoch 06 | train_loss=0.5418 train_acc=0.8328 | val_loss=0.9361 val_acc=0.7184 | test_loss=0.5991 test_acc=0.7298
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.4750 train_acc=0.8553 | val_loss=0.7985 val_acc=0.7358 | test_loss=0.5467 test_acc=0.7493
Epoch 08 | train_loss=0.4177 train_acc=0.8694 | val_loss=0.9097 val_acc=0.7544 | test_loss=0.5981 test_acc=0.7716
Epoch 09 | train_loss=0.3755 train_acc=0.8801 | val_loss=0.8844 val_acc=0.7535 | test_loss=0.5597 test_acc=0.7716
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.3370 train_acc=0.8908 | val_loss=0.8246 val_acc=0.7740 | test_loss=0.4440 test_acc=0.8022
Epoch 11 | train_loss=0.3061 train_acc=0.8993 | val_loss=0.7640 val_acc=0.7889 | test_loss=0.4968 test_acc=0.8078
Epoch 12 | train_loss=0.2803 train_acc=0.9102 | val_loss=0.9391 val_acc=0.7581 | test_loss=0.6014 test_acc=0.7744
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.2555 train_acc=0.9140 | val_loss=0.8459 val_acc=0.7639 | test_loss=0.5045 test_acc=0.7549
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.2361 train_acc=0.9226 | val_loss=0.7407 val_acc=0.7834 | test_loss=0.4570 test_acc=0.7827
  No validation improvement greater than 0.0020. Patience: 3/5

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,20,0.791764,0.853526,0.831893
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,18,0.787416,0.928571,0.911725
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,20,0.780696,0.950820,0.930947
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,18,0.777642,0.985401,0.974831
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,16,0.788943,0.807799,0.823147
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,16,0.770312,0.828947,0.829889
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,20,0.813073,0.968338,0.962478
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,14,0.769395,0.934701,0.939070
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,13,0.769090,0.483871,0.510771
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,19,0.665247,0.769318,0.688729
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,20,0.718999,0.333333,0.222218
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,20,0.711549,0.731025,0.778830
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,13,0.666504,0.975962,0.976979
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,20,0.687760,0.732794,0.706685
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,20,0.691180,0.856436,0.754636
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,20,0.680430,0.802372,0.741716
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,17,0.663572,0.979508,0.947713
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,20,0.732482,0.693350,0.648006
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,20,0.696454,0.961694,0.953858
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,20,0.761444,0.814029,0.772882
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,20,0.741491,0.923461,0.894095
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,20,0.702171,0.926230,0.943921
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,19,0.734155,0.722222,0.747947
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,20,0.741197,0.980392,0.968703
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,20,0.765258,0.781308,0.726761

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.7948
Overall window-level macro F1: 0.7782
Mean fold accuracy: 0.8290 ± 0.1588
Mean fold macro F1: 0.8075 ± 0.1730
Saved summary CSV: experiment_results/segment_combination_study__combo-Hand__nseg-1__win-4s__step-0.5s__20260407_143540__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-Hand__nseg-1__win-4s__step-0.5s__20260407_143540__folds.csv

====================================================================================================
Combination run 4/15
Canonical combo: ['Shoulder']
Selected segment labels: ['LeftShoulder', 'RightShoulder']
No cached dataset found. Building dataset from MVNX files...
Kept files: 1420 | Skipped files (allowed but failed): 88
X: (14521, 240, 6) y: (14521,) groups: (14521,)
Saved dataset cache to: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftShoulder_RightShoulder__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (Shoulder) dataset loaded.
Dataset shape: (14521, 240, 6)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 6)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4739 train_acc=0.2987 | val_loss=2.2322 val_acc=0.2896 | test_loss=2.1534 test_acc=0.2640
Epoch 02 | train_loss=1.6733 train_acc=0.4486 | val_loss=1.7996 val_acc=0.3261 | test_loss=1.7821 test_acc=0.3255
Epoch 03 | train_loss=1.3694 train_acc=0.5011 | val_loss=1.6591 val_acc=0.4074 | test_loss=1.5452 test_acc=0.3978
Epoch 04 | train_loss=1.2037 train_acc=0.5556 | val_loss=1.6321 val_acc=0.4339 | test_loss=1.4861 test_acc=0.4467
Epoch 05 | train_loss=1.0915 train_acc=0.5943 | val_loss=1.4875 val_acc=0.4888 | test_loss=1.3368 test_acc=0.4756
Epoch 06 | train_loss=1.0083 train_acc=0.6358 | val_loss=1.4657 val_acc=0.4955 | test_loss=1.2789 test_acc=0.4864
Epoch 07 | train_loss=0.9351 train_acc=0.6555 | val_loss=1.4832 val_acc=0.5112 | test_loss=1.2595 test_acc=0.5027
Epoch 08 | train_loss=0.8784 train_acc=0.6849 | val_loss=1.5460 val_acc=0.4945 | test_loss=1.4176 test_acc=0.4756
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.8239 train_acc=0.7040 | val_loss=1.4679 val_acc=0.5504 | test_loss=1.3520 test_acc=0.5190
Epoch 10 | train_loss=0.7717 train_acc=0.7157 | val_loss=1.4701 val_acc=0.5588 | test_loss=1.2745 test_acc=0.5172
Epoch 11 | train_loss=0.7252 train_acc=0.7363 | val_loss=1.5483 val_acc=0.5206 | test_loss=1.3489 test_acc=0.4901
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.6826 train_acc=0.7450 | val_loss=1.5321 val_acc=0.5280 | test_loss=1.2261 test_acc=0.5154
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.6427 train_acc=0.7620 | val_loss=1.4817 val_acc=0.5634 | test_loss=1.2144 test_acc=0.5533
Epoch 14 | train_loss=0.6031 train_acc=0.7759 | val_loss=1.6919 val_acc=0.5280 | test_loss=1.4051 test_acc=0.5154
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.5688 train_acc=0.7896 | val_loss=1.5816 val_acc=0.5206 | test_loss=1.3133 test_acc=0.5118
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 16 | train_loss=0.5435 train_acc=0.7954 | val_loss=1.6072 val_acc=0.5598 | test_loss=1.3545 test_acc=0.5371
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 17 | train_loss=0.5115 train_acc=0.8037 | val_loss=1.5878 val_acc=0.5691 | test_loss=1.2881 test_acc=0.5389
Epoch 18 | train_loss=0.4871 train_acc=0.8183 | val_loss=1.5258 val_acc=0.5963 | test_loss=1.2986 test_acc=0.5533
Epoch 19 | train_loss=0.4642 train_acc=0.8221 | val_loss=1.6869 val_acc=0.5440 | test_loss=1.3623 test_acc=0.5353
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 20 | train_loss=0.4424 train_acc=0.8318 | val_loss=1.7046 val_acc=0.5246 | test_loss=1.3095 test_acc=0.5208
  No validation improvement greater than 0.0020. Patience: 2/5
Fold 1 complete | subject=H01 | test_acc=0.5533 | test_macro_f1=0.5090
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4545 train_acc=0.2812 | val_loss=2.1995 val_acc=0.3262 | test_loss=1.6741 test_acc=0.3985
Epoch 02 | train_loss=1.6710 train_acc=0.4195 | val_loss=1.7810 val_acc=0.3681 | test_loss=1.3776 test_acc=0.4586
Epoch 03 | train_loss=1.3769 train_acc=0.4918 | val_loss=1.7633 val_acc=0.3781 | test_loss=1.3574 test_acc=0.4850
Epoch 04 | train_loss=1.2066 train_acc=0.5597 | val_loss=1.5901 val_acc=0.4157 | test_loss=1.0870 test_acc=0.6316
Epoch 05 | train_loss=1.0927 train_acc=0.6063 | val_loss=1.5606 val_acc=0.4569 | test_loss=1.1341 test_acc=0.6729
Epoch 06 | train_loss=1.0083 train_acc=0.6356 | val_loss=1.4923 val_acc=0.4918 | test_loss=1.0231 test_acc=0.7218
Epoch 07 | train_loss=0.9297 train_acc=0.6676 | val_loss=1.4984 val_acc=0.4979 | test_loss=1.0657 test_acc=0.6805
Epoch 08 | train_loss=0.8720 train_acc=0.6775 | val_loss=1.5475 val_acc=0.5079 | test_loss=1.0518 test_acc=0.6805
Epoch 09 | train_loss=0.8157 train_acc=0.7006 | val_loss=1.4612 val_acc=0.5128 | test_loss=1.0143 test_acc=0.6992
Epoch 10 | train_loss=0.7614 train_acc=0.7200 | val_loss=1.5059 val_acc=0.5241 | test_loss=0.9125 test_acc=0.7519
Epoch 11 | train_loss=0.7176 train_acc=0.7391 | val_loss=1.4489 val_acc=0.5333 | test_loss=0.9653 test_acc=0.6917
Epoch 12 | train_loss=0.6796 train_acc=0.7519 | val_loss=1.4770 val_acc=0.5379 | test_loss=1.1100 test_acc=0.6805
Epoch 13 | train_loss=0.6361 train_acc=0.7639 | val_loss=1.4740 val_acc=0.5541 | test_loss=0.9625 test_acc=0.7481
Epoch 14 | train_loss=0.6010 train_acc=0.7792 | val_loss=1.6710 val_acc=0.5290 | test_loss=1.0148 test_acc=0.7030
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.5704 train_acc=0.7945 | val_loss=1.4226 val_acc=0.5516 | test_loss=0.9919 test_acc=0.6917
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 16 | train_loss=0.5343 train_acc=0.8048 | val_loss=1.7714 val_acc=0.5034 | test_loss=0.9160 test_acc=0.7368
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 17 | train_loss=0.5084 train_acc=0.8107 | val_loss=1.6231 val_acc=0.5107 | test_loss=0.9615 test_acc=0.6880
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 18 | train_loss=0.4832 train_acc=0.8257 | val_loss=1.5196 val_acc=0.5791 | test_loss=0.8480 test_acc=0.7820
Epoch 19 | train_loss=0.4500 train_acc=0.8345 | val_loss=1.5893 val_acc=0.5858 | test_loss=0.9583 test_acc=0.7331
Epoch 20 | train_loss=0.4252 train_acc=0.8393 | val_loss=1.6273 val_acc=0.5785 | test_loss=0.9628 test_acc=0.7293
  No validation improvement greater than 0.0020. Patience: 1/5
Fold 2 complete | subject=H02 | test_acc=0.7331 | test_macro_f1=0.6086
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4723 train_acc=0.3713 | val_loss=2.3246 val_acc=0.3864 | test_loss=1.9520 test_acc=0.5152
Epoch 02 | train_loss=1.7249 train_acc=0.4169 | val_loss=1.8108 val_acc=0.3366 | test_loss=1.3078 test_acc=0.4660
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 03 | train_loss=1.4145 train_acc=0.4673 | val_loss=1.6431 val_acc=0.3772 | test_loss=1.1215 test_acc=0.5621
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 04 | train_loss=1.2415 train_acc=0.5323 | val_loss=1.5996 val_acc=0.4181 | test_loss=1.0958 test_acc=0.5199
Epoch 05 | train_loss=1.1185 train_acc=0.5802 | val_loss=1.5697 val_acc=0.4560 | test_loss=0.9593 test_acc=0.6112
Epoch 06 | train_loss=1.0287 train_acc=0.6176 | val_loss=1.5937 val_acc=0.4569 | test_loss=0.9504 test_acc=0.6112
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.9580 train_acc=0.6437 | val_loss=1.5885 val_acc=0.4795 | test_loss=0.9474 test_acc=0.6487
Epoch 08 | train_loss=0.8933 train_acc=0.6640 | val_loss=1.5684 val_acc=0.5058 | test_loss=1.1712 test_acc=0.5785
Epoch 09 | train_loss=0.8350 train_acc=0.6909 | val_loss=1.6294 val_acc=0.4890 | test_loss=1.0942 test_acc=0.6511
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.7923 train_acc=0.7105 | val_loss=1.7440 val_acc=0.4695 | test_loss=0.9355 test_acc=0.6768
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.7420 train_acc=0.7264 | val_loss=1.6222 val_acc=0.5021 | test_loss=0.8486 test_acc=0.7260
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 12 | train_loss=0.7011 train_acc=0.7400 | val_loss=1.5674 val_acc=0.5137 | test_loss=1.0212 test_acc=0.6815
Epoch 13 | train_loss=0.6608 train_acc=0.7540 | val_loss=1.6126 val_acc=0.4899 | test_loss=0.9285 test_acc=0.6838
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.6272 train_acc=0.7710 | val_loss=1.5786 val_acc=0.5156 | test_loss=0.8567 test_acc=0.7330
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.5822 train_acc=0.7825 | val_loss=1.5925 val_acc=0.5272 | test_loss=0.6531 test_acc=0.7799
Epoch 16 | train_loss=0.5516 train_acc=0.7890 | val_loss=1.6306 val_acc=0.5174 | test_loss=0.7717 test_acc=0.7400
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.5243 train_acc=0.8045 | val_loss=1.7173 val_acc=0.5189 | test_loss=1.1021 test_acc=0.6628
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.4923 train_acc=0.8166 | val_loss=1.8503 val_acc=0.4982 | test_loss=1.0565 test_acc=0.6932
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 19 | train_loss=0.4683 train_acc=0.8274 | val_loss=1.7710 val_acc=0.5238 | test_loss=1.0408 test_acc=0.6932
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 20 | train_loss=0.4432 train_acc=0.8280 | val_loss=1.7606 val_acc=0.5336 | test_loss=0.9810 test_acc=0.6956
Fold 3 complete | subject=H03 | test_acc=0.6956 | test_macro_f1=0.6396
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.5340 train_acc=0.1588 | val_loss=2.2785 val_acc=0.2926 | test_loss=2.0692 test_acc=0.3431
Epoch 02 | train_loss=1.6963 train_acc=0.3851 | val_loss=1.8300 val_acc=0.3803 | test_loss=1.5326 test_acc=0.5365
Epoch 03 | train_loss=1.4041 train_acc=0.4959 | val_loss=1.7017 val_acc=0.4160 | test_loss=1.3386 test_acc=0.5803
Epoch 04 | train_loss=1.2451 train_acc=0.5351 | val_loss=1.5920 val_acc=0.4661 | test_loss=1.1709 test_acc=0.6314
Epoch 05 | train_loss=1.1276 train_acc=0.5828 | val_loss=1.5213 val_acc=0.4346 | test_loss=1.0943 test_acc=0.6131
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 06 | train_loss=1.0288 train_acc=0.6194 | val_loss=1.5921 val_acc=0.4734 | test_loss=1.0726 test_acc=0.6423
Epoch 07 | train_loss=0.9513 train_acc=0.6534 | val_loss=1.4474 val_acc=0.5134 | test_loss=0.9905 test_acc=0.6825
Epoch 08 | train_loss=0.8931 train_acc=0.6751 | val_loss=1.4858 val_acc=0.4948 | test_loss=0.9283 test_acc=0.6825
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.8332 train_acc=0.6953 | val_loss=1.4975 val_acc=0.5290 | test_loss=0.9151 test_acc=0.7628
Epoch 10 | train_loss=0.7808 train_acc=0.7166 | val_loss=1.4013 val_acc=0.5250 | test_loss=0.9119 test_acc=0.7044
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.7355 train_acc=0.7354 | val_loss=1.5275 val_acc=0.5345 | test_loss=0.8873 test_acc=0.7445
Epoch 12 | train_loss=0.6945 train_acc=0.7461 | val_loss=1.4749 val_acc=0.5403 | test_loss=0.8573 test_acc=0.7591
Epoch 13 | train_loss=0.6640 train_acc=0.7567 | val_loss=1.5070 val_acc=0.5101 | test_loss=0.8466 test_acc=0.6533
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.6136 train_acc=0.7766 | val_loss=1.4624 val_acc=0.5544 | test_loss=0.9742 test_acc=0.6971
Epoch 15 | train_loss=0.5825 train_acc=0.7877 | val_loss=1.3951 val_acc=0.5782 | test_loss=0.9788 test_acc=0.6715
Epoch 16 | train_loss=0.5514 train_acc=0.7957 | val_loss=1.5324 val_acc=0.5342 | test_loss=0.9229 test_acc=0.7226
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.5176 train_acc=0.8105 | val_loss=1.5174 val_acc=0.5666 | test_loss=1.0931 test_acc=0.6825
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.4940 train_acc=0.8143 | val_loss=1.6323 val_acc=0.5336 | test_loss=0.8806 test_acc=0.7445
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 19 | train_loss=0.4635 train_acc=0.8274 | val_loss=1.6048 val_acc=0.5507 | test_loss=1.1258 test_acc=0.6861
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 20 | train_loss=0.4461 train_acc=0.8341 | val_loss=1.5377 val_acc=0.5709 | test_loss=1.1448 test_acc=0.6314
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 20.
Fold 4 complete | subject=H04 | test_acc=0.6715 | test_macro_f1=0.5751
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4274 train_acc=0.1953 | val_loss=2.1460 val_acc=0.2871 | test_loss=1.7744 test_acc=0.2563
Epoch 02 | train_loss=1.6854 train_acc=0.3846 | val_loss=1.7753 val_acc=0.3531 | test_loss=1.4238 test_acc=0.4652
Epoch 03 | train_loss=1.4062 train_acc=0.4529 | val_loss=1.6246 val_acc=0.4157 | test_loss=1.2294 test_acc=0.4735
Epoch 04 | train_loss=1.2430 train_acc=0.5115 | val_loss=1.5711 val_acc=0.4142 | test_loss=1.1156 test_acc=0.6295
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 05 | train_loss=1.1216 train_acc=0.5540 | val_loss=1.5032 val_acc=0.4362 | test_loss=1.1424 test_acc=0.5822
Epoch 06 | train_loss=1.0295 train_acc=0.5968 | val_loss=1.7092 val_acc=0.4123 | test_loss=1.2220 test_acc=0.5014
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.9555 train_acc=0.6254 | val_loss=1.5234 val_acc=0.4560 | test_loss=1.0191 test_acc=0.6212
Epoch 08 | train_loss=0.8865 train_acc=0.6624 | val_loss=1.6441 val_acc=0.4575 | test_loss=1.0846 test_acc=0.6212
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.8286 train_acc=0.6880 | val_loss=1.5386 val_acc=0.4670 | test_loss=0.9727 test_acc=0.6546
Epoch 10 | train_loss=0.7814 train_acc=0.7067 | val_loss=1.6804 val_acc=0.4594 | test_loss=1.1067 test_acc=0.6295
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.7400 train_acc=0.7227 | val_loss=1.4796 val_acc=0.5055 | test_loss=1.0089 test_acc=0.6212
Epoch 12 | train_loss=0.6897 train_acc=0.7419 | val_loss=1.5143 val_acc=0.5067 | test_loss=0.8656 test_acc=0.6964
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.6511 train_acc=0.7568 | val_loss=1.4395 val_acc=0.5360 | test_loss=0.8131 test_acc=0.6992

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,20,0.596250,0.553345,0.509038
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,20,0.585828,0.733083,0.608631
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,20,0.533598,0.695550,0.639636
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,20,0.578192,0.671533,0.575050
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,20,0.557422,0.735376,0.635998
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,18,0.502749,0.416667,0.321838
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,15,0.540012,0.606860,0.503425
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,20,0.565363,0.779851,0.749633
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,20,0.569029,0.435484,0.380945
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,12,0.460085,0.393182,0.325925
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,20,0.509313,0.318352,0.223833
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,13,0.520756,0.524634,0.442001
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,11,0.479111,0.620192,0.715840
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,15,0.486685,0.632928,0.625998
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,11,0.461764,0.483498,0.386911
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,20,0.519179,0.555995,0.474908
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,13,0.483508,0.643443,0.532209
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,19,0.532482,0.566502,0.557413
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,20,0.533333,0.733871,0.691389
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,20,0.563087,0.525285,0.418412
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,20,0.551350,0.692180,0.637362
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,20,0.550763,0.643443,0.580882
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,16,0.526995,0.638418,0.626901
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,20,0.553110,0.634804,0.498270
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,19,0.521714,0.433645,0.362652

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.5676
Overall window-level macro F1: 0.5190
Mean fold accuracy: 0.5867 ± 0.1213
Mean fold macro F1: 0.5210 ± 0.1364
Saved summary CSV: experiment_results/segment_combination_study__combo-Shoulder__nseg-1__win-4s__step-0.5s__20260407_145413__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-Shoulder__nseg-1__win-4s__step-0.5s__20260407_145413__folds.csv

====================================================================================================
Combination run 5/15
Canonical combo: ['UpperArm', 'ForeArm']
Selected segment labels: ['LeftUpperArm', 'RightUpperArm', 'LeftForeArm', 'RightForeArm']
No cached dataset found. Building dataset from MVNX files...
Kept files: 1420 | Skipped files (allowed but failed): 88
X: (14521, 240, 12) y: (14521,) groups: (14521,)
Saved dataset cache to: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftUpperArm_RightUpperArm_LeftForeArm_RightForeArm__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (UpperArm+ForeArm) dataset loaded.
Dataset shape: (14521, 240, 12)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 12)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2075 train_acc=0.2421 | val_loss=1.6287 val_acc=0.3164 | test_loss=1.5473 test_acc=0.3273
Epoch 02 | train_loss=1.1410 train_acc=0.5349 | val_loss=1.2138 val_acc=0.4828 | test_loss=1.2335 test_acc=0.4539
Epoch 03 | train_loss=0.8168 train_acc=0.6764 | val_loss=1.0198 val_acc=0.5922 | test_loss=1.0290 test_acc=0.5298
Epoch 04 | train_loss=0.6497 train_acc=0.7661 | val_loss=1.0125 val_acc=0.6337 | test_loss=1.1034 test_acc=0.5298
Epoch 05 | train_loss=0.5333 train_acc=0.8252 | val_loss=0.8381 val_acc=0.6866 | test_loss=0.8833 test_acc=0.5986
Epoch 06 | train_loss=0.4454 train_acc=0.8598 | val_loss=0.8470 val_acc=0.7305 | test_loss=0.8892 test_acc=0.6854
Epoch 07 | train_loss=0.3756 train_acc=0.8838 | val_loss=0.8101 val_acc=0.6957 | test_loss=0.9335 test_acc=0.6293
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.3282 train_acc=0.9001 | val_loss=0.8762 val_acc=0.6967 | test_loss=0.9985 test_acc=0.5823
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.2859 train_acc=0.9108 | val_loss=0.8831 val_acc=0.7138 | test_loss=0.9056 test_acc=0.6383
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 10 | train_loss=0.2530 train_acc=0.9230 | val_loss=0.8486 val_acc=0.7569 | test_loss=0.7603 test_acc=0.7179
Epoch 11 | train_loss=0.2263 train_acc=0.9292 | val_loss=0.7533 val_acc=0.7744 | test_loss=0.8456 test_acc=0.7288
Epoch 12 | train_loss=0.2044 train_acc=0.9349 | val_loss=0.8180 val_acc=0.7546 | test_loss=0.8738 test_acc=0.6872
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.1874 train_acc=0.9427 | val_loss=0.8514 val_acc=0.7469 | test_loss=0.9174 test_acc=0.6492
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.1704 train_acc=0.9488 | val_loss=0.8593 val_acc=0.7546 | test_loss=0.9744 test_acc=0.7197
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 15 | train_loss=0.1498 train_acc=0.9543 | val_loss=0.8061 val_acc=0.7693 | test_loss=0.8258 test_acc=0.6926
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 16 | train_loss=0.1338 train_acc=0.9570 | val_loss=0.7954 val_acc=0.7827 | test_loss=0.9155 test_acc=0.7722
Epoch 17 | train_loss=0.1233 train_acc=0.9625 | val_loss=0.8781 val_acc=0.7693 | test_loss=0.9454 test_acc=0.6854
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 18 | train_loss=0.1118 train_acc=0.9680 | val_loss=0.8735 val_acc=0.7700 | test_loss=1.0848 test_acc=0.6835
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 19 | train_loss=0.1058 train_acc=0.9709 | val_loss=0.8205 val_acc=0.7965 | test_loss=0.8648 test_acc=0.7740
Epoch 20 | train_loss=0.0943 train_acc=0.9743 | val_loss=0.8500 val_acc=0.7944 | test_loss=0.9126 test_acc=0.7595
  No validation improvement greater than 0.0020. Patience: 1/5
Fold 1 complete | subject=H01 | test_acc=0.7740 | test_macro_f1=0.7453
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3449 train_acc=0.2485 | val_loss=1.6840 val_acc=0.3525 | test_loss=1.2439 test_acc=0.4812
Epoch 02 | train_loss=1.1847 train_acc=0.5510 | val_loss=1.2485 val_acc=0.4853 | test_loss=0.7296 test_acc=0.5865
Epoch 03 | train_loss=0.8242 train_acc=0.7017 | val_loss=0.9505 val_acc=0.6466 | test_loss=0.4387 test_acc=0.7895
Epoch 04 | train_loss=0.6396 train_acc=0.7850 | val_loss=0.9026 val_acc=0.7001 | test_loss=0.3536 test_acc=0.8647
Epoch 05 | train_loss=0.5175 train_acc=0.8345 | val_loss=0.8924 val_acc=0.6903 | test_loss=0.2427 test_acc=0.9023
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 06 | train_loss=0.4310 train_acc=0.8664 | val_loss=0.8993 val_acc=0.6967 | test_loss=0.2166 test_acc=0.9023
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 07 | train_loss=0.3665 train_acc=0.8894 | val_loss=0.9607 val_acc=0.6622 | test_loss=0.2023 test_acc=0.9098
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 08 | train_loss=0.3175 train_acc=0.9035 | val_loss=0.7621 val_acc=0.7376 | test_loss=0.2342 test_acc=0.8985
Epoch 09 | train_loss=0.2825 train_acc=0.9136 | val_loss=0.9241 val_acc=0.7129 | test_loss=0.1360 test_acc=0.9398
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2465 train_acc=0.9253 | val_loss=0.8978 val_acc=0.7288 | test_loss=0.1863 test_acc=0.9211
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.2207 train_acc=0.9322 | val_loss=0.9192 val_acc=0.7217 | test_loss=0.1500 test_acc=0.9323
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 12 | train_loss=0.1972 train_acc=0.9414 | val_loss=0.9484 val_acc=0.7053 | test_loss=0.1955 test_acc=0.9211
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 13 | train_loss=0.1774 train_acc=0.9455 | val_loss=0.9130 val_acc=0.7016 | test_loss=0.1561 test_acc=0.9361
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 13.
Fold 2 complete | subject=H02 | test_acc=0.8985 | test_macro_f1=0.9082
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2848 train_acc=0.3132 | val_loss=1.7089 val_acc=0.3485 | test_loss=1.1579 test_acc=0.5597
Epoch 02 | train_loss=1.1629 train_acc=0.5462 | val_loss=1.2311 val_acc=0.4847 | test_loss=0.5136 test_acc=0.7518
Epoch 03 | train_loss=0.8170 train_acc=0.6647 | val_loss=1.0341 val_acc=0.6060 | test_loss=0.4029 test_acc=0.8173
Epoch 04 | train_loss=0.6604 train_acc=0.7420 | val_loss=1.0469 val_acc=0.6145 | test_loss=0.2969 test_acc=0.8806
Epoch 05 | train_loss=0.5454 train_acc=0.8039 | val_loss=0.9090 val_acc=0.6787 | test_loss=0.3115 test_acc=0.8782
Epoch 06 | train_loss=0.4560 train_acc=0.8441 | val_loss=0.9350 val_acc=0.7043 | test_loss=0.2265 test_acc=0.9110
Epoch 07 | train_loss=0.3856 train_acc=0.8726 | val_loss=0.9702 val_acc=0.6790 | test_loss=0.2639 test_acc=0.9087
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.3334 train_acc=0.8909 | val_loss=0.9944 val_acc=0.6707 | test_loss=0.3301 test_acc=0.9180
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.2848 train_acc=0.9080 | val_loss=0.9898 val_acc=0.6622 | test_loss=0.2706 test_acc=0.8946
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 10 | train_loss=0.2566 train_acc=0.9186 | val_loss=0.8114 val_acc=0.7557 | test_loss=0.1439 test_acc=0.9578
Epoch 11 | train_loss=0.2251 train_acc=0.9272 | val_loss=0.9442 val_acc=0.7019 | test_loss=0.2935 test_acc=0.9087
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.2016 train_acc=0.9335 | val_loss=0.8088 val_acc=0.7642 | test_loss=0.1656 test_acc=0.9602
Epoch 13 | train_loss=0.1806 train_acc=0.9435 | val_loss=0.8149 val_acc=0.7495 | test_loss=0.1447 test_acc=0.9696
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.1585 train_acc=0.9496 | val_loss=0.8583 val_acc=0.7376 | test_loss=0.2574 test_acc=0.9321
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.1454 train_acc=0.9552 | val_loss=0.8530 val_acc=0.7660 | test_loss=0.1510 test_acc=0.9625
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 16 | train_loss=0.1291 train_acc=0.9626 | val_loss=0.9324 val_acc=0.7330 | test_loss=0.2312 test_acc=0.9485
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 17 | train_loss=0.1180 train_acc=0.9652 | val_loss=0.8900 val_acc=0.7456 | test_loss=0.1496 test_acc=0.9532
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 17.
Fold 3 complete | subject=H03 | test_acc=0.9602 | test_macro_f1=0.9432
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4388 train_acc=0.2122 | val_loss=1.7696 val_acc=0.2899 | test_loss=1.6319 test_acc=0.3650
Epoch 02 | train_loss=1.1942 train_acc=0.5220 | val_loss=1.2170 val_acc=0.4731 | test_loss=0.9350 test_acc=0.5949
Epoch 03 | train_loss=0.8461 train_acc=0.6720 | val_loss=1.1089 val_acc=0.5406 | test_loss=0.6645 test_acc=0.6752
Epoch 04 | train_loss=0.6629 train_acc=0.7589 | val_loss=1.0026 val_acc=0.6436 | test_loss=0.4448 test_acc=0.7555
Epoch 05 | train_loss=0.5365 train_acc=0.8142 | val_loss=0.8995 val_acc=0.6952 | test_loss=0.3079 test_acc=0.8869
Epoch 06 | train_loss=0.4475 train_acc=0.8517 | val_loss=0.8584 val_acc=0.6891 | test_loss=0.2899 test_acc=0.9051
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.3781 train_acc=0.8748 | val_loss=0.8875 val_acc=0.7443 | test_loss=0.2954 test_acc=0.9380
Epoch 08 | train_loss=0.3261 train_acc=0.8932 | val_loss=0.7945 val_acc=0.7468 | test_loss=0.1995 test_acc=0.9708
Epoch 09 | train_loss=0.2833 train_acc=0.9040 | val_loss=0.8184 val_acc=0.7288 | test_loss=0.1773 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2497 train_acc=0.9185 | val_loss=0.8552 val_acc=0.7630 | test_loss=0.1291 test_acc=0.9745
Epoch 11 | train_loss=0.2228 train_acc=0.9298 | val_loss=0.9025 val_acc=0.7416 | test_loss=0.1480 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.1961 train_acc=0.9364 | val_loss=0.7889 val_acc=0.7492 | test_loss=0.1245 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.1743 train_acc=0.9451 | val_loss=0.8187 val_acc=0.7816 | test_loss=0.1047 test_acc=0.9854
Epoch 14 | train_loss=0.1572 train_acc=0.9492 | val_loss=0.8142 val_acc=0.7627 | test_loss=0.1196 test_acc=0.9854
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.1439 train_acc=0.9549 | val_loss=0.7786 val_acc=0.7755 | test_loss=0.1235 test_acc=0.9818
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 16 | train_loss=0.1309 train_acc=0.9626 | val_loss=1.0102 val_acc=0.7257 | test_loss=0.1546 test_acc=0.9562
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 17 | train_loss=0.1210 train_acc=0.9635 | val_loss=0.8198 val_acc=0.7828 | test_loss=0.1020 test_acc=0.9854
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 18 | train_loss=0.1086 train_acc=0.9686 | val_loss=0.7891 val_acc=0.7880 | test_loss=0.0987 test_acc=0.9818
Epoch 19 | train_loss=0.0962 train_acc=0.9715 | val_loss=0.8114 val_acc=0.7801 | test_loss=0.1187 test_acc=0.9854
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 20 | train_loss=0.0875 train_acc=0.9740 | val_loss=0.7393 val_acc=0.8012 | test_loss=0.1014 test_acc=0.9891
Fold 4 complete | subject=H04 | test_acc=0.9891 | test_macro_f1=0.9627
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3350 train_acc=0.2481 | val_loss=1.6955 val_acc=0.2917 | test_loss=1.1890 test_acc=0.3259
Epoch 02 | train_loss=1.1549 train_acc=0.5490 | val_loss=1.3289 val_acc=0.4392 | test_loss=0.8436 test_acc=0.5599
Epoch 03 | train_loss=0.8121 train_acc=0.7018 | val_loss=1.2081 val_acc=0.5651 | test_loss=0.7122 test_acc=0.6964
Epoch 04 | train_loss=0.6382 train_acc=0.7922 | val_loss=0.9257 val_acc=0.6539 | test_loss=0.7075 test_acc=0.6797
Epoch 05 | train_loss=0.5138 train_acc=0.8371 | val_loss=0.9631 val_acc=0.7043 | test_loss=0.6350 test_acc=0.7187
Epoch 06 | train_loss=0.4253 train_acc=0.8702 | val_loss=1.0431 val_acc=0.6817 | test_loss=0.6623 test_acc=0.7187
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.3591 train_acc=0.8916 | val_loss=0.8945 val_acc=0.7147 | test_loss=0.6509 test_acc=0.7019
Epoch 08 | train_loss=0.3217 train_acc=0.9042 | val_loss=0.9537 val_acc=0.7053 | test_loss=0.6008 test_acc=0.7019
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2771 train_acc=0.9171 | val_loss=0.9469 val_acc=0.7318 | test_loss=0.5005 test_acc=0.7465
Epoch 10 | train_loss=0.2451 train_acc=0.9279 | val_loss=0.9412 val_acc=0.6912 | test_loss=0.5697 test_acc=0.6825
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.2172 train_acc=0.9347 | val_loss=0.9516 val_acc=0.7309 | test_loss=0.5382 test_acc=0.7075
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.1952 train_acc=0.9434 | val_loss=0.7744 val_acc=0.7648 | test_loss=0.5199 test_acc=0.7549
Epoch 13 | train_loss=0.1700 train_acc=0.9528 | val_loss=0.9272 val_acc=0.7379 | test_loss=0.5668 test_acc=0.7214
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.1561 train_acc=0.9538 | val_loss=0.9984 val_acc=0.7007 | test_loss=0.5877 test_acc=0.7214
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.1431 train_acc=0.9557 | val_loss=0.9274 val_acc=0.7300 | test_loss=0.4608 test_acc=0.7270
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 16 | train_loss=0.1258 train_acc=0.9656 | val_loss=0.6721 val_acc=0.8103 | test_loss=0.3588 test_acc=0.7939
Epoch 17 | train_loss=0.1204 train_acc=0.9639 | val_loss=0.7328 val_acc=0.7660 | test_loss=0.4918 test_acc=0.7326
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 18 | train_loss=0.1032 train_acc=0.9703 | val_loss=0.8512 val_acc=0.7648 | test_loss=0.4518 test_acc=0.7577
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 19 | train_loss=0.0965 train_acc=0.9737 | val_loss=1.0225 val_acc=0.7544 | test_loss=0.4504 test_acc=0.7521

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,20,0.796451,0.773960,0.745258
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,13,0.737630,0.898496,0.908173
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,17,0.764203,0.960187,0.943183
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,20,0.801161,0.989051,0.962678
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,20,0.810324,0.793872,0.851972
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,20,0.774893,0.795322,0.807239
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,17,0.789859,0.963061,0.954284
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,12,0.728772,0.912313,0.916367
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,20,0.756872,0.446481,0.490804
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,11,0.633049,0.742045,0.729927
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,12,0.661788,0.494382,0.260252
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,20,0.691591,0.756325,0.784304
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,18,0.692157,0.978365,0.972999
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,16,0.655998,0.832659,0.809143
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,14,0.674078,0.869637,0.845177
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,20,0.666015,0.791831,0.790027
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,16,0.669924,0.942623,0.932125
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,20,0.663262,0.710591,0.662775
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,14,0.686241,0.872984,0.872245
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,18,0.694836,0.817292,0.792685
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,13,0.675469,0.851913,0.813370
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,15,0.715376,0.952869,0.954479
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,17,0.706573,0.711864,0.757183
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,19,0.729460,0.977941,0.983894
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,16,0.757042,0.751402,0.685710

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.7864
Overall window-level macro F1: 0.7828
Mean fold accuracy: 0.8235 ± 0.1385
Mean fold macro F1: 0.8091 ± 0.1631
Saved summary CSV: experiment_results/segment_combination_study__combo-UpperArm__ForeArm__nseg-2__win-4s__step-0.5s__20260407_151240__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-UpperArm__ForeArm__nseg-2__win-4s__step-0.5s__20260407_151240__folds.csv

====================================================================================================
Combination run 6/15
Canonical combo: ['UpperArm', 'Hand']
Selected segment labels: ['LeftUpperArm', 'RightUpperArm', 'LeftHand', 'RightHand']
No cached dataset found. Building dataset from MVNX files...
Kept files: 1420 | Skipped files (allowed but failed): 88
X: (14521, 240, 12) y: (14521,) groups: (14521,)
Saved dataset cache to: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftUpperArm_RightUpperArm_LeftHand_RightHand__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (UpperArm+Hand) dataset loaded.
Dataset shape: (14521, 240, 12)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 12)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3603 train_acc=0.2689 | val_loss=1.6745 val_acc=0.3900 | test_loss=1.3987 test_acc=0.4394
Epoch 02 | train_loss=1.2042 train_acc=0.5698 | val_loss=1.1306 val_acc=0.5296 | test_loss=0.7682 test_acc=0.5823
Epoch 03 | train_loss=0.8124 train_acc=0.7182 | val_loss=0.8818 val_acc=0.6907 | test_loss=0.5805 test_acc=0.6926
Epoch 04 | train_loss=0.6202 train_acc=0.7966 | val_loss=0.8267 val_acc=0.7041 | test_loss=0.5483 test_acc=0.6980
Epoch 05 | train_loss=0.5019 train_acc=0.8463 | val_loss=0.7872 val_acc=0.7476 | test_loss=0.4232 test_acc=0.7685
Epoch 06 | train_loss=0.4153 train_acc=0.8754 | val_loss=0.7752 val_acc=0.7449 | test_loss=0.3900 test_acc=0.7541
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.3510 train_acc=0.8944 | val_loss=0.7487 val_acc=0.7650 | test_loss=0.4127 test_acc=0.7957
Epoch 08 | train_loss=0.3009 train_acc=0.9061 | val_loss=0.8090 val_acc=0.7442 | test_loss=0.4812 test_acc=0.7541
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2638 train_acc=0.9197 | val_loss=0.8828 val_acc=0.7342 | test_loss=0.4790 test_acc=0.7378
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 10 | train_loss=0.2327 train_acc=0.9292 | val_loss=0.7760 val_acc=0.7583 | test_loss=0.3871 test_acc=0.7577
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 11 | train_loss=0.2059 train_acc=0.9375 | val_loss=0.7240 val_acc=0.7948 | test_loss=0.2301 test_acc=0.8752
Epoch 12 | train_loss=0.1905 train_acc=0.9436 | val_loss=0.6389 val_acc=0.8142 | test_loss=0.2671 test_acc=0.8590
Epoch 13 | train_loss=0.1669 train_acc=0.9502 | val_loss=0.7589 val_acc=0.7730 | test_loss=0.2803 test_acc=0.8373
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.1506 train_acc=0.9552 | val_loss=0.7171 val_acc=0.7961 | test_loss=0.2860 test_acc=0.8590
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.1375 train_acc=0.9565 | val_loss=0.6291 val_acc=0.8209 | test_loss=0.2712 test_acc=0.8879
Epoch 16 | train_loss=0.1242 train_acc=0.9623 | val_loss=0.7680 val_acc=0.7877 | test_loss=0.3437 test_acc=0.8427
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.1084 train_acc=0.9682 | val_loss=0.7603 val_acc=0.8048 | test_loss=0.2674 test_acc=0.8608
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.1022 train_acc=0.9724 | val_loss=0.7960 val_acc=0.7794 | test_loss=0.3136 test_acc=0.8336
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 19 | train_loss=0.0894 train_acc=0.9749 | val_loss=0.7959 val_acc=0.7941 | test_loss=0.3762 test_acc=0.8300
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 20 | train_loss=0.0837 train_acc=0.9783 | val_loss=0.7324 val_acc=0.8102 | test_loss=0.3238 test_acc=0.8463
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 20.
Fold 1 complete | subject=H01 | test_acc=0.8879 | test_macro_f1=0.8480
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4123 train_acc=0.2607 | val_loss=1.8983 val_acc=0.2746 | test_loss=1.2907 test_acc=0.4398
Epoch 02 | train_loss=1.1814 train_acc=0.5653 | val_loss=1.3169 val_acc=0.4988 | test_loss=0.5929 test_acc=0.6767
Epoch 03 | train_loss=0.7767 train_acc=0.7300 | val_loss=0.9723 val_acc=0.6655 | test_loss=0.3872 test_acc=0.7895
Epoch 04 | train_loss=0.5938 train_acc=0.8157 | val_loss=0.9582 val_acc=0.6872 | test_loss=0.3121 test_acc=0.8195
Epoch 05 | train_loss=0.4767 train_acc=0.8529 | val_loss=0.7798 val_acc=0.7557 | test_loss=0.2769 test_acc=0.8609
Epoch 06 | train_loss=0.3994 train_acc=0.8764 | val_loss=0.9253 val_acc=0.7083 | test_loss=0.2735 test_acc=0.8759
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.3421 train_acc=0.8945 | val_loss=0.9851 val_acc=0.7190 | test_loss=0.2520 test_acc=0.8835
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 08 | train_loss=0.3000 train_acc=0.9047 | val_loss=0.8559 val_acc=0.7379 | test_loss=0.2329 test_acc=0.8985
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 09 | train_loss=0.2688 train_acc=0.9103 | val_loss=0.8045 val_acc=0.7563 | test_loss=0.2524 test_acc=0.8872
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 10 | train_loss=0.2395 train_acc=0.9226 | val_loss=0.8541 val_acc=0.7712 | test_loss=0.3583 test_acc=0.8684
Epoch 11 | train_loss=0.2098 train_acc=0.9309 | val_loss=0.8037 val_acc=0.7502 | test_loss=0.3226 test_acc=0.8647
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.1902 train_acc=0.9394 | val_loss=0.8726 val_acc=0.7410 | test_loss=0.1699 test_acc=0.9248
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.1693 train_acc=0.9454 | val_loss=0.8463 val_acc=0.7807 | test_loss=0.3717 test_acc=0.8872
Epoch 14 | train_loss=0.1507 train_acc=0.9534 | val_loss=0.7492 val_acc=0.8045 | test_loss=0.3239 test_acc=0.8872
Epoch 15 | train_loss=0.1430 train_acc=0.9556 | val_loss=0.8784 val_acc=0.7779 | test_loss=0.2076 test_acc=0.9173
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.1265 train_acc=0.9632 | val_loss=0.8250 val_acc=0.7987 | test_loss=0.2595 test_acc=0.9098
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 17 | train_loss=0.1116 train_acc=0.9662 | val_loss=0.7796 val_acc=0.7969 | test_loss=0.2547 test_acc=0.8985
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 18 | train_loss=0.1032 train_acc=0.9679 | val_loss=1.0593 val_acc=0.7508 | test_loss=0.1897 test_acc=0.9173
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 19 | train_loss=0.0934 train_acc=0.9728 | val_loss=0.8935 val_acc=0.7825 | test_loss=0.2175 test_acc=0.9398
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 19.
Fold 2 complete | subject=H02 | test_acc=0.8872 | test_macro_f1=0.8998
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3479 train_acc=0.2211 | val_loss=1.7958 val_acc=0.3143 | test_loss=1.2810 test_acc=0.4356
Epoch 02 | train_loss=1.2345 train_acc=0.5907 | val_loss=1.1049 val_acc=0.6338 | test_loss=0.5706 test_acc=0.7377
Epoch 03 | train_loss=0.8301 train_acc=0.7419 | val_loss=0.9873 val_acc=0.7361 | test_loss=0.4346 test_acc=0.8290
Epoch 04 | train_loss=0.6227 train_acc=0.8155 | val_loss=0.7987 val_acc=0.7621 | test_loss=0.3354 test_acc=0.8454
Epoch 05 | train_loss=0.5009 train_acc=0.8438 | val_loss=0.8679 val_acc=0.7324 | test_loss=0.2759 test_acc=0.8618
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 06 | train_loss=0.4179 train_acc=0.8688 | val_loss=0.8344 val_acc=0.7526 | test_loss=0.2767 test_acc=0.8618
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 07 | train_loss=0.3589 train_acc=0.8859 | val_loss=0.8067 val_acc=0.7578 | test_loss=0.2371 test_acc=0.8642
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 08 | train_loss=0.3107 train_acc=0.9012 | val_loss=0.8252 val_acc=0.7731 | test_loss=0.2402 test_acc=0.8712
Epoch 09 | train_loss=0.2734 train_acc=0.9128 | val_loss=0.7627 val_acc=0.7779 | test_loss=0.2142 test_acc=0.8899
Epoch 10 | train_loss=0.2396 train_acc=0.9234 | val_loss=0.8248 val_acc=0.7227 | test_loss=0.2645 test_acc=0.8782
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.2127 train_acc=0.9325 | val_loss=0.7746 val_acc=0.7666 | test_loss=0.1960 test_acc=0.9040
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.1863 train_acc=0.9396 | val_loss=0.7933 val_acc=0.7764 | test_loss=0.2314 test_acc=0.9063
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 13 | train_loss=0.1693 train_acc=0.9445 | val_loss=0.7827 val_acc=0.7621 | test_loss=0.1745 test_acc=0.8970
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 14 | train_loss=0.1491 train_acc=0.9534 | val_loss=0.8837 val_acc=0.7813 | test_loss=0.1667 test_acc=0.9040
Epoch 15 | train_loss=0.1369 train_acc=0.9572 | val_loss=0.7741 val_acc=0.7700 | test_loss=0.1448 test_acc=0.9180
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.1267 train_acc=0.9575 | val_loss=0.7592 val_acc=0.8067 | test_loss=0.1406 test_acc=0.9204
Epoch 17 | train_loss=0.1136 train_acc=0.9677 | val_loss=0.8160 val_acc=0.7749 | test_loss=0.1489 test_acc=0.9133
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 18 | train_loss=0.1033 train_acc=0.9685 | val_loss=0.7998 val_acc=0.7935 | test_loss=0.1318 test_acc=0.9274
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 19 | train_loss=0.0960 train_acc=0.9717 | val_loss=0.8044 val_acc=0.8161 | test_loss=0.1186 test_acc=0.9368
Epoch 20 | train_loss=0.0858 train_acc=0.9768 | val_loss=0.7242 val_acc=0.7902 | test_loss=0.1463 test_acc=0.9227
  No validation improvement greater than 0.0020. Patience: 1/5
Fold 3 complete | subject=H03 | test_acc=0.9368 | test_macro_f1=0.9378
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3297 train_acc=0.2324 | val_loss=1.8910 val_acc=0.2724 | test_loss=1.5260 test_acc=0.3248
Epoch 02 | train_loss=1.1531 train_acc=0.5781 | val_loss=1.3948 val_acc=0.4786 | test_loss=0.6639 test_acc=0.7007
Epoch 03 | train_loss=0.7897 train_acc=0.7372 | val_loss=1.0419 val_acc=0.6549 | test_loss=0.3784 test_acc=0.8686
Epoch 04 | train_loss=0.5999 train_acc=0.8114 | val_loss=0.9081 val_acc=0.7111 | test_loss=0.2864 test_acc=0.9197
Epoch 05 | train_loss=0.4868 train_acc=0.8510 | val_loss=0.8791 val_acc=0.7132 | test_loss=0.2242 test_acc=0.9343
Epoch 06 | train_loss=0.4054 train_acc=0.8772 | val_loss=0.7775 val_acc=0.7508 | test_loss=0.1664 test_acc=0.9745
Epoch 07 | train_loss=0.3403 train_acc=0.8975 | val_loss=0.7776 val_acc=0.7685 | test_loss=0.1353 test_acc=0.9745
Epoch 08 | train_loss=0.2975 train_acc=0.9082 | val_loss=0.8281 val_acc=0.7407 | test_loss=0.1565 test_acc=0.9307
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2620 train_acc=0.9201 | val_loss=0.8312 val_acc=0.7538 | test_loss=0.1300 test_acc=0.9745
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 10 | train_loss=0.2291 train_acc=0.9299 | val_loss=0.7214 val_acc=0.7813 | test_loss=0.1032 test_acc=0.9854
Epoch 11 | train_loss=0.2037 train_acc=0.9387 | val_loss=0.7391 val_acc=0.8036 | test_loss=0.1009 test_acc=0.9891
Epoch 12 | train_loss=0.1859 train_acc=0.9425 | val_loss=0.7714 val_acc=0.7590 | test_loss=0.1150 test_acc=0.9854
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.1625 train_acc=0.9533 | val_loss=0.7872 val_acc=0.7679 | test_loss=0.0912 test_acc=0.9891
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.1447 train_acc=0.9551 | val_loss=0.8699 val_acc=0.7398 | test_loss=0.1233 test_acc=0.9745
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 15 | train_loss=0.1309 train_acc=0.9622 | val_loss=0.7135 val_acc=0.8244 | test_loss=0.1049 test_acc=0.9891
Epoch 16 | train_loss=0.1160 train_acc=0.9670 | val_loss=0.7757 val_acc=0.7993 | test_loss=0.0818 test_acc=0.9927
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.1055 train_acc=0.9715 | val_loss=0.7067 val_acc=0.8103 | test_loss=0.0777 test_acc=0.9891
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.0942 train_acc=0.9745 | val_loss=0.7142 val_acc=0.8225 | test_loss=0.0708 test_acc=0.9891
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 19 | train_loss=0.0873 train_acc=0.9772 | val_loss=0.7128 val_acc=0.8177 | test_loss=0.0750 test_acc=0.9927
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 20 | train_loss=0.0794 train_acc=0.9789 | val_loss=0.8110 val_acc=0.8210 | test_loss=0.0595 test_acc=0.9964
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 20.
Fold 4 complete | subject=H04 | test_acc=0.9891 | test_macro_f1=0.8600
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4205 train_acc=0.2337 | val_loss=1.7932 val_acc=0.3256 | test_loss=1.4416 test_acc=0.4708
Epoch 02 | train_loss=1.2488 train_acc=0.5575 | val_loss=1.1190 val_acc=0.5586 | test_loss=0.7511 test_acc=0.6323
Epoch 03 | train_loss=0.8274 train_acc=0.7119 | val_loss=0.9996 val_acc=0.6549 | test_loss=0.6957 test_acc=0.6797
Epoch 04 | train_loss=0.6311 train_acc=0.8042 | val_loss=0.8871 val_acc=0.7153 | test_loss=0.5809 test_acc=0.7326
Epoch 05 | train_loss=0.5119 train_acc=0.8475 | val_loss=0.8612 val_acc=0.7297 | test_loss=0.5653 test_acc=0.7326
Epoch 06 | train_loss=0.4303 train_acc=0.8702 | val_loss=0.8321 val_acc=0.7538 | test_loss=0.5245 test_acc=0.7855
Epoch 07 | train_loss=0.3657 train_acc=0.8934 | val_loss=0.9018 val_acc=0.7321 | test_loss=0.4876 test_acc=0.7967
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.3127 train_acc=0.9085 | val_loss=0.9431 val_acc=0.7544 | test_loss=0.4795 test_acc=0.7827
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.2736 train_acc=0.9186 | val_loss=0.8382 val_acc=0.7492 | test_loss=0.5530 test_acc=0.7716
  No validation improvement greater than 0.0020. Patience: 3/5

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,20,0.820891,0.887884,0.847959
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,19,0.804520,0.887218,0.899754
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,20,0.816127,0.936768,0.937798
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,20,0.824374,0.989051,0.860018
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,20,0.804520,0.838440,0.844745
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,20,0.797801,0.903509,0.912851
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,20,0.831093,0.970976,0.967965
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,20,0.803299,0.932836,0.926681
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,15,0.789554,0.481672,0.522652
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,20,0.695051,0.811364,0.775965
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,20,0.726450,0.531835,0.316716
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,15,0.710750,0.744341,0.758133
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,20,0.675788,0.987981,0.984096
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,13,0.653799,0.777328,0.792409
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,20,0.688981,0.858086,0.775013
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,20,0.699976,0.805007,0.798409
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,20,0.712925,0.995902,0.975414
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,20,0.742128,0.676108,0.653455
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,16,0.729645,0.953629,0.955695
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,20,0.732394,0.856444,0.829376
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,17,0.758803,0.876872,0.835225
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,19,0.737676,0.946721,0.950947
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,20,0.730927,0.738230,0.784451
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,20,0.742958,0.950980,0.967274
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,20,0.753815,0.807477,0.787765

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.8097
Overall window-level macro F1: 0.8066
Mean fold accuracy: 0.8459 ± 0.1333
Mean fold macro F1: 0.8264 ± 0.1519
Saved summary CSV: experiment_results/segment_combination_study__combo-UpperArm__Hand__nseg-2__win-4s__step-0.5s__20260407_153215__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-UpperArm__Hand__nseg-2__win-4s__step-0.5s__20260407_153215__folds.csv

====================================================================================================
Combination run 7/15
Canonical combo: ['UpperArm', 'Shoulder']
Selected segment labels: ['LeftUpperArm', 'RightUpperArm', 'LeftShoulder', 'RightShoulder']
No cached dataset found. Building dataset from MVNX files...
Kept files: 1420 | Skipped files (allowed but failed): 88
X: (14521, 240, 12) y: (14521,) groups: (14521,)
Saved dataset cache to: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftUpperArm_RightUpperArm_LeftShoulder_RightShoulder__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (UpperArm+Shoulder) dataset loaded.
Dataset shape: (14521, 240, 12)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 12)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2743 train_acc=0.2328 | val_loss=1.9187 val_acc=0.2745 | test_loss=2.0085 test_acc=0.2278
Epoch 02 | train_loss=1.4816 train_acc=0.4623 | val_loss=1.6246 val_acc=0.3498 | test_loss=1.5447 test_acc=0.2857
Epoch 03 | train_loss=1.1503 train_acc=0.5742 | val_loss=1.3499 val_acc=0.4523 | test_loss=1.2353 test_acc=0.4087
Epoch 04 | train_loss=0.9554 train_acc=0.6519 | val_loss=1.2584 val_acc=0.5340 | test_loss=1.0264 test_acc=0.5606
Epoch 05 | train_loss=0.8202 train_acc=0.7129 | val_loss=1.2174 val_acc=0.6083 | test_loss=1.0414 test_acc=0.5570
Epoch 06 | train_loss=0.7110 train_acc=0.7671 | val_loss=1.1388 val_acc=0.6532 | test_loss=0.8971 test_acc=0.6709
Epoch 07 | train_loss=0.6333 train_acc=0.7872 | val_loss=1.2077 val_acc=0.6418 | test_loss=0.9381 test_acc=0.6004
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.5565 train_acc=0.8155 | val_loss=1.0808 val_acc=0.7007 | test_loss=0.7826 test_acc=0.7197
Epoch 09 | train_loss=0.4984 train_acc=0.8334 | val_loss=1.2426 val_acc=0.6234 | test_loss=1.0282 test_acc=0.5642
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.4451 train_acc=0.8496 | val_loss=1.0515 val_acc=0.7064 | test_loss=0.7169 test_acc=0.7089
Epoch 11 | train_loss=0.4027 train_acc=0.8621 | val_loss=1.1340 val_acc=0.7017 | test_loss=0.8505 test_acc=0.6926
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.3633 train_acc=0.8749 | val_loss=0.9972 val_acc=0.7285 | test_loss=0.7682 test_acc=0.7215
Epoch 13 | train_loss=0.3352 train_acc=0.8838 | val_loss=1.2153 val_acc=0.6887 | test_loss=0.8952 test_acc=0.6817
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.3025 train_acc=0.8961 | val_loss=1.1941 val_acc=0.6756 | test_loss=0.7813 test_acc=0.6980
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.2789 train_acc=0.9029 | val_loss=1.2593 val_acc=0.6803 | test_loss=0.8263 test_acc=0.6854
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 16 | train_loss=0.2517 train_acc=0.9118 | val_loss=1.1527 val_acc=0.7064 | test_loss=0.8581 test_acc=0.6745
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 17 | train_loss=0.2346 train_acc=0.9177 | val_loss=1.2401 val_acc=0.6642 | test_loss=0.9052 test_acc=0.6275
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 17.
Fold 1 complete | subject=H01 | test_acc=0.7215 | test_macro_f1=0.6948
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3737 train_acc=0.2321 | val_loss=2.0998 val_acc=0.2227 | test_loss=1.7244 test_acc=0.4135
Epoch 02 | train_loss=1.5072 train_acc=0.4519 | val_loss=1.6194 val_acc=0.3396 | test_loss=1.2082 test_acc=0.5075
Epoch 03 | train_loss=1.1794 train_acc=0.5553 | val_loss=1.4240 val_acc=0.4084 | test_loss=0.9445 test_acc=0.6053
Epoch 04 | train_loss=0.9920 train_acc=0.6319 | val_loss=1.3719 val_acc=0.4756 | test_loss=0.8218 test_acc=0.7368
Epoch 05 | train_loss=0.8520 train_acc=0.7012 | val_loss=1.4730 val_acc=0.4484 | test_loss=0.6880 test_acc=0.7632
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 06 | train_loss=0.7342 train_acc=0.7510 | val_loss=1.4181 val_acc=0.5235 | test_loss=0.5319 test_acc=0.8534
Epoch 07 | train_loss=0.6505 train_acc=0.7793 | val_loss=1.3116 val_acc=0.5638 | test_loss=0.4808 test_acc=0.8459
Epoch 08 | train_loss=0.5749 train_acc=0.8046 | val_loss=1.2291 val_acc=0.6155 | test_loss=0.4907 test_acc=0.8383
Epoch 09 | train_loss=0.5176 train_acc=0.8244 | val_loss=1.3312 val_acc=0.6063 | test_loss=0.5397 test_acc=0.8421
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.4632 train_acc=0.8419 | val_loss=1.0886 val_acc=0.6591 | test_loss=0.3623 test_acc=0.8872
Epoch 11 | train_loss=0.4205 train_acc=0.8540 | val_loss=1.1268 val_acc=0.6552 | test_loss=0.3819 test_acc=0.9023
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.3765 train_acc=0.8684 | val_loss=1.0533 val_acc=0.6542 | test_loss=0.3750 test_acc=0.8647
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.3462 train_acc=0.8773 | val_loss=1.2607 val_acc=0.6497 | test_loss=0.3673 test_acc=0.8684
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 14 | train_loss=0.3084 train_acc=0.8946 | val_loss=1.2318 val_acc=0.6790 | test_loss=0.3992 test_acc=0.8684
Epoch 15 | train_loss=0.2837 train_acc=0.9005 | val_loss=1.2131 val_acc=0.6750 | test_loss=0.2926 test_acc=0.9023
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.2580 train_acc=0.9080 | val_loss=1.3021 val_acc=0.6405 | test_loss=0.3223 test_acc=0.8797
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 17 | train_loss=0.2356 train_acc=0.9191 | val_loss=1.3674 val_acc=0.6619 | test_loss=0.3891 test_acc=0.8684
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 18 | train_loss=0.2166 train_acc=0.9221 | val_loss=1.2807 val_acc=0.6637 | test_loss=0.3880 test_acc=0.8759
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 19 | train_loss=0.1931 train_acc=0.9322 | val_loss=1.2531 val_acc=0.6793 | test_loss=0.3410 test_acc=0.8835
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 19.
Fold 2 complete | subject=H02 | test_acc=0.8684 | test_macro_f1=0.8463
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4209 train_acc=0.3733 | val_loss=2.1912 val_acc=0.1930 | test_loss=1.6692 test_acc=0.4262
Epoch 02 | train_loss=1.5680 train_acc=0.4276 | val_loss=1.6241 val_acc=0.3235 | test_loss=1.0008 test_acc=0.5714
Epoch 03 | train_loss=1.2054 train_acc=0.5465 | val_loss=1.4374 val_acc=0.4016 | test_loss=0.7505 test_acc=0.6159
Epoch 04 | train_loss=0.9980 train_acc=0.6366 | val_loss=1.3695 val_acc=0.4756 | test_loss=0.6165 test_acc=0.7728
Epoch 05 | train_loss=0.8504 train_acc=0.7058 | val_loss=1.3786 val_acc=0.5037 | test_loss=0.4705 test_acc=0.8361
Epoch 06 | train_loss=0.7402 train_acc=0.7402 | val_loss=1.2724 val_acc=0.5513 | test_loss=0.3851 test_acc=0.8290
Epoch 07 | train_loss=0.6586 train_acc=0.7726 | val_loss=1.2591 val_acc=0.5492 | test_loss=0.3422 test_acc=0.8595
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.5846 train_acc=0.7984 | val_loss=1.1978 val_acc=0.5846 | test_loss=0.3157 test_acc=0.8595
Epoch 09 | train_loss=0.5162 train_acc=0.8213 | val_loss=1.1188 val_acc=0.6109 | test_loss=0.2553 test_acc=0.8712
Epoch 10 | train_loss=0.4681 train_acc=0.8354 | val_loss=1.3125 val_acc=0.5739 | test_loss=0.2477 test_acc=0.9016
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.4217 train_acc=0.8518 | val_loss=1.3882 val_acc=0.5602 | test_loss=0.2300 test_acc=0.9087
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.3802 train_acc=0.8710 | val_loss=1.1993 val_acc=0.5974 | test_loss=0.1869 test_acc=0.9274
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 13 | train_loss=0.3438 train_acc=0.8808 | val_loss=1.2542 val_acc=0.6069 | test_loss=0.1890 test_acc=0.9180
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 14 | train_loss=0.3139 train_acc=0.8891 | val_loss=1.2911 val_acc=0.6286 | test_loss=0.1785 test_acc=0.9321
Epoch 15 | train_loss=0.2835 train_acc=0.9034 | val_loss=1.2846 val_acc=0.6133 | test_loss=0.1448 test_acc=0.9321
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.2618 train_acc=0.9086 | val_loss=1.2524 val_acc=0.6371 | test_loss=0.1401 test_acc=0.9297
Epoch 17 | train_loss=0.2365 train_acc=0.9183 | val_loss=1.4623 val_acc=0.5864 | test_loss=0.1503 test_acc=0.9274
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 18 | train_loss=0.2168 train_acc=0.9282 | val_loss=1.3750 val_acc=0.6109 | test_loss=0.1365 test_acc=0.9157
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 19 | train_loss=0.2015 train_acc=0.9300 | val_loss=1.4977 val_acc=0.6133 | test_loss=0.1307 test_acc=0.9391
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 20 | train_loss=0.1827 train_acc=0.9384 | val_loss=1.3948 val_acc=0.6301 | test_loss=0.1421 test_acc=0.9157
  No validation improvement greater than 0.0020. Patience: 4/5
Fold 3 complete | subject=H03 | test_acc=0.9297 | test_macro_f1=0.9155
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3748 train_acc=0.2152 | val_loss=2.0629 val_acc=0.2718 | test_loss=1.7021 test_acc=0.2993
Epoch 02 | train_loss=1.5089 train_acc=0.4699 | val_loss=1.5540 val_acc=0.4496 | test_loss=1.1283 test_acc=0.5474
Epoch 03 | train_loss=1.1493 train_acc=0.5950 | val_loss=1.2867 val_acc=0.5229 | test_loss=0.8960 test_acc=0.6423
Epoch 04 | train_loss=0.9465 train_acc=0.6720 | val_loss=1.2808 val_acc=0.5651 | test_loss=0.7686 test_acc=0.7190
Epoch 05 | train_loss=0.8089 train_acc=0.7256 | val_loss=1.1775 val_acc=0.5965 | test_loss=0.7239 test_acc=0.7007
Epoch 06 | train_loss=0.7051 train_acc=0.7649 | val_loss=1.1618 val_acc=0.6356 | test_loss=0.7510 test_acc=0.7336
Epoch 07 | train_loss=0.6154 train_acc=0.7939 | val_loss=1.1332 val_acc=0.6362 | test_loss=0.7173 test_acc=0.7044
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.5435 train_acc=0.8184 | val_loss=1.1511 val_acc=0.6029 | test_loss=0.6890 test_acc=0.6423
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.4846 train_acc=0.8355 | val_loss=1.1466 val_acc=0.6216 | test_loss=0.6935 test_acc=0.6971
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 10 | train_loss=0.4345 train_acc=0.8504 | val_loss=1.1646 val_acc=0.6597 | test_loss=0.6280 test_acc=0.7409
Epoch 11 | train_loss=0.3875 train_acc=0.8652 | val_loss=1.3095 val_acc=0.6200 | test_loss=0.6365 test_acc=0.7263
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.3533 train_acc=0.8823 | val_loss=1.2560 val_acc=0.6594 | test_loss=0.6070 test_acc=0.8467
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.3209 train_acc=0.8875 | val_loss=1.0902 val_acc=0.6674 | test_loss=0.7986 test_acc=0.7044
Epoch 14 | train_loss=0.2954 train_acc=0.8926 | val_loss=1.1428 val_acc=0.6674 | test_loss=0.5598 test_acc=0.7774
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.2701 train_acc=0.9057 | val_loss=1.0873 val_acc=0.6796 | test_loss=0.5959 test_acc=0.7701
Epoch 16 | train_loss=0.2440 train_acc=0.9173 | val_loss=1.2427 val_acc=0.6756 | test_loss=0.5642 test_acc=0.7847
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.2227 train_acc=0.9249 | val_loss=1.1435 val_acc=0.6814 | test_loss=0.5988 test_acc=0.8066
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.2071 train_acc=0.9282 | val_loss=1.3294 val_acc=0.6625 | test_loss=0.5796 test_acc=0.7920
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 19 | train_loss=0.1897 train_acc=0.9385 | val_loss=1.0840 val_acc=0.6927 | test_loss=0.8296 test_acc=0.8139
Epoch 20 | train_loss=0.1680 train_acc=0.9430 | val_loss=1.2572 val_acc=0.6839 | test_loss=0.4934 test_acc=0.8723
  No validation improvement greater than 0.0020. Patience: 1/5
Fold 4 complete | subject=H04 | test_acc=0.8139 | test_macro_f1=0.6945
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4275 train_acc=0.2382 | val_loss=2.0242 val_acc=0.3598 | test_loss=1.5987 test_acc=0.4011
Epoch 02 | train_loss=1.5788 train_acc=0.4699 | val_loss=1.5679 val_acc=0.3580 | test_loss=1.2289 test_acc=0.4847
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 03 | train_loss=1.2132 train_acc=0.5617 | val_loss=1.2952 val_acc=0.5278 | test_loss=0.9872 test_acc=0.6407
Epoch 04 | train_loss=0.9798 train_acc=0.6662 | val_loss=1.2305 val_acc=0.5846 | test_loss=0.9080 test_acc=0.6713
Epoch 05 | train_loss=0.8421 train_acc=0.7173 | val_loss=1.2173 val_acc=0.5693 | test_loss=0.8469 test_acc=0.6323
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 06 | train_loss=0.7369 train_acc=0.7566 | val_loss=1.2797 val_acc=0.5919 | test_loss=0.8762 test_acc=0.6490
Epoch 07 | train_loss=0.6495 train_acc=0.7820 | val_loss=1.2458 val_acc=0.5938 | test_loss=0.6983 test_acc=0.7075
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.5760 train_acc=0.8136 | val_loss=1.2319 val_acc=0.5843 | test_loss=0.7775 test_acc=0.6685
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.5166 train_acc=0.8242 | val_loss=1.1842 val_acc=0.6225 | test_loss=0.6777 test_acc=0.6880
Epoch 10 | train_loss=0.4648 train_acc=0.8491 | val_loss=1.1830 val_acc=0.6112 | test_loss=0.6336 test_acc=0.7131
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.4141 train_acc=0.8598 | val_loss=1.1224 val_acc=0.6484 | test_loss=0.6330 test_acc=0.6964
Epoch 12 | train_loss=0.3783 train_acc=0.8729 | val_loss=1.0965 val_acc=0.6289 | test_loss=0.7566 test_acc=0.6769
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.3346 train_acc=0.8880 | val_loss=1.1272 val_acc=0.6582 | test_loss=0.5440 test_acc=0.7298

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,17,0.728490,0.721519,0.694811
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,19,0.678986,0.868421,0.846278
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,20,0.637141,0.929742,0.915527
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,20,0.692731,0.813869,0.694525
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,20,0.700061,0.791086,0.772461
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,20,0.715944,0.616959,0.590539
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,17,0.690287,0.799472,0.689752
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,20,0.695480,0.798507,0.766410
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,17,0.688149,0.401760,0.420768
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,20,0.602714,0.693182,0.561751
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,20,0.626397,0.232210,0.131041
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,18,0.608302,0.688415,0.672415
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,20,0.609089,0.875000,0.861118
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,20,0.587100,0.709852,0.661400
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,19,0.611776,0.701320,0.584829
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,16,0.599805,0.658762,0.613062
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,20,0.599316,0.897541,0.730955
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,18,0.623262,0.646552,0.509111
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,15,0.587518,0.832661,0.839269
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,16,0.590376,0.662316,0.544050
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,18,0.613850,0.820300,0.762015
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,20,0.635563,0.825820,0.819914
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,18,0.638791,0.665725,0.619883
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,15,0.601819,0.828431,0.742226
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,20,0.634683,0.600000,0.485637

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.6931
Overall window-level macro F1: 0.6472
Mean fold accuracy: 0.7232 ± 0.1548
Mean fold macro F1: 0.6612 ± 0.1677
Saved summary CSV: experiment_results/segment_combination_study__combo-UpperArm__Shoulder__nseg-2__win-4s__step-0.5s__20260407_155147__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-UpperArm__Shoulder__nseg-2__win-4s__step-0.5s__20260407_155147__folds.csv

====================================================================================================
Combination run 8/15
Canonical combo: ['ForeArm', 'Hand']
Selected segment labels: ['LeftForeArm', 'RightForeArm', 'LeftHand', 'RightHand']
No cached dataset found. Building dataset from MVNX files...
Kept files: 1420 | Skipped files (allowed but failed): 88
X: (14521, 240, 12) y: (14521,) groups: (14521,)
Saved dataset cache to: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftForeArm_RightForeArm_LeftHand_RightHand__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (ForeArm+Hand) dataset loaded.
Dataset shape: (14521, 240, 12)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 12)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.1588 train_acc=0.2719 | val_loss=1.6958 val_acc=0.2872 | test_loss=1.4428 test_acc=0.3291
Epoch 02 | train_loss=1.2180 train_acc=0.5048 | val_loss=1.2634 val_acc=0.4697 | test_loss=0.9914 test_acc=0.4937
Epoch 03 | train_loss=0.8505 train_acc=0.6925 | val_loss=1.1163 val_acc=0.6029 | test_loss=0.8708 test_acc=0.6040
Epoch 04 | train_loss=0.6422 train_acc=0.7998 | val_loss=0.8937 val_acc=0.7111 | test_loss=0.5914 test_acc=0.7541
Epoch 05 | train_loss=0.5157 train_acc=0.8432 | val_loss=0.9207 val_acc=0.7154 | test_loss=0.5187 test_acc=0.7360
Epoch 06 | train_loss=0.4345 train_acc=0.8715 | val_loss=0.9608 val_acc=0.7449 | test_loss=0.4860 test_acc=0.7920
Epoch 07 | train_loss=0.3654 train_acc=0.8925 | val_loss=0.9337 val_acc=0.7345 | test_loss=0.4150 test_acc=0.7848
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.3206 train_acc=0.9063 | val_loss=0.8857 val_acc=0.7563 | test_loss=0.3817 test_acc=0.8282
Epoch 09 | train_loss=0.2820 train_acc=0.9149 | val_loss=0.7915 val_acc=0.7800 | test_loss=0.3503 test_acc=0.8517
Epoch 10 | train_loss=0.2496 train_acc=0.9249 | val_loss=0.8143 val_acc=0.7894 | test_loss=0.3048 test_acc=0.8843
Epoch 11 | train_loss=0.2241 train_acc=0.9332 | val_loss=0.8811 val_acc=0.7797 | test_loss=0.2999 test_acc=0.8987
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.2066 train_acc=0.9356 | val_loss=0.9772 val_acc=0.7643 | test_loss=0.3196 test_acc=0.8716
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.1805 train_acc=0.9450 | val_loss=0.8190 val_acc=0.8108 | test_loss=0.2270 test_acc=0.9385
Epoch 14 | train_loss=0.1685 train_acc=0.9503 | val_loss=0.7711 val_acc=0.8169 | test_loss=0.2356 test_acc=0.9078
Epoch 15 | train_loss=0.1548 train_acc=0.9511 | val_loss=0.9018 val_acc=0.7911 | test_loss=0.2620 test_acc=0.9005
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.1392 train_acc=0.9573 | val_loss=0.9310 val_acc=0.7831 | test_loss=0.2594 test_acc=0.8987
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 17 | train_loss=0.1269 train_acc=0.9597 | val_loss=1.2249 val_acc=0.7419 | test_loss=0.4056 test_acc=0.8264
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 18 | train_loss=0.1157 train_acc=0.9648 | val_loss=0.8561 val_acc=0.8045 | test_loss=0.1975 test_acc=0.9367
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 19 | train_loss=0.1034 train_acc=0.9716 | val_loss=0.9988 val_acc=0.7877 | test_loss=0.2510 test_acc=0.9132
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 19.
Fold 1 complete | subject=H01 | test_acc=0.9078 | test_macro_f1=0.8895
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2729 train_acc=0.2737 | val_loss=1.6854 val_acc=0.3506 | test_loss=1.2205 test_acc=0.3872
Epoch 02 | train_loss=1.2662 train_acc=0.5142 | val_loss=1.3178 val_acc=0.4572 | test_loss=0.7023 test_acc=0.6654
Epoch 03 | train_loss=0.8956 train_acc=0.6794 | val_loss=1.1663 val_acc=0.5742 | test_loss=0.4419 test_acc=0.7857
Epoch 04 | train_loss=0.6656 train_acc=0.7817 | val_loss=1.0695 val_acc=0.6546 | test_loss=0.3332 test_acc=0.8684
Epoch 05 | train_loss=0.5437 train_acc=0.8367 | val_loss=0.9943 val_acc=0.6915 | test_loss=0.2960 test_acc=0.8985
Epoch 06 | train_loss=0.4534 train_acc=0.8609 | val_loss=1.0000 val_acc=0.6936 | test_loss=0.2271 test_acc=0.9098
Epoch 07 | train_loss=0.3932 train_acc=0.8777 | val_loss=0.9120 val_acc=0.7379 | test_loss=0.2387 test_acc=0.9248
Epoch 08 | train_loss=0.3466 train_acc=0.8905 | val_loss=0.8319 val_acc=0.7611 | test_loss=0.2686 test_acc=0.9173
Epoch 09 | train_loss=0.3041 train_acc=0.9063 | val_loss=0.9820 val_acc=0.7276 | test_loss=0.1507 test_acc=0.9436
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2724 train_acc=0.9139 | val_loss=0.9247 val_acc=0.7563 | test_loss=0.1590 test_acc=0.9398
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.2461 train_acc=0.9238 | val_loss=0.9193 val_acc=0.7535 | test_loss=0.1355 test_acc=0.9474
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 12 | train_loss=0.2244 train_acc=0.9282 | val_loss=0.7762 val_acc=0.7752 | test_loss=0.1974 test_acc=0.9398
Epoch 13 | train_loss=0.2063 train_acc=0.9334 | val_loss=0.8629 val_acc=0.7752 | test_loss=0.1693 test_acc=0.9398
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.1909 train_acc=0.9408 | val_loss=0.8933 val_acc=0.7673 | test_loss=0.1534 test_acc=0.9323
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.1710 train_acc=0.9450 | val_loss=0.8844 val_acc=0.7810 | test_loss=0.1452 test_acc=0.9436
Epoch 16 | train_loss=0.1566 train_acc=0.9487 | val_loss=0.8558 val_acc=0.8070 | test_loss=0.1792 test_acc=0.9361
Epoch 17 | train_loss=0.1417 train_acc=0.9566 | val_loss=1.0274 val_acc=0.7670 | test_loss=0.1012 test_acc=0.9699
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 18 | train_loss=0.1335 train_acc=0.9582 | val_loss=1.0624 val_acc=0.7572 | test_loss=0.1065 test_acc=0.9586
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 19 | train_loss=0.1181 train_acc=0.9647 | val_loss=0.9629 val_acc=0.7889 | test_loss=0.1413 test_acc=0.9436
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 20 | train_loss=0.1105 train_acc=0.9668 | val_loss=0.8061 val_acc=0.8021 | test_loss=0.1236 test_acc=0.9662
  No validation improvement greater than 0.0020. Patience: 4/5
Fold 2 complete | subject=H02 | test_acc=0.9361 | test_macro_f1=0.9623
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3472 train_acc=0.2391 | val_loss=1.7700 val_acc=0.2382 | test_loss=1.3882 test_acc=0.3349
Epoch 02 | train_loss=1.2775 train_acc=0.4669 | val_loss=1.2943 val_acc=0.4038 | test_loss=0.8039 test_acc=0.6393
Epoch 03 | train_loss=0.9291 train_acc=0.6239 | val_loss=1.1289 val_acc=0.5541 | test_loss=0.5395 test_acc=0.7377
Epoch 04 | train_loss=0.7171 train_acc=0.7443 | val_loss=1.0411 val_acc=0.6814 | test_loss=0.4532 test_acc=0.8361
Epoch 05 | train_loss=0.5791 train_acc=0.8066 | val_loss=0.8661 val_acc=0.7532 | test_loss=0.2563 test_acc=0.9110
Epoch 06 | train_loss=0.4787 train_acc=0.8468 | val_loss=0.9513 val_acc=0.7266 | test_loss=0.3178 test_acc=0.8548
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.4142 train_acc=0.8677 | val_loss=0.9767 val_acc=0.7288 | test_loss=0.2456 test_acc=0.9063
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 08 | train_loss=0.3536 train_acc=0.8827 | val_loss=0.7535 val_acc=0.8005 | test_loss=0.1650 test_acc=0.9391
Epoch 09 | train_loss=0.3097 train_acc=0.8973 | val_loss=0.7539 val_acc=0.8073 | test_loss=0.1420 test_acc=0.9578
Epoch 10 | train_loss=0.2723 train_acc=0.9130 | val_loss=0.8165 val_acc=0.7801 | test_loss=0.1846 test_acc=0.9297
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.2421 train_acc=0.9182 | val_loss=0.8277 val_acc=0.7981 | test_loss=0.2237 test_acc=0.9415
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.2204 train_acc=0.9253 | val_loss=0.6381 val_acc=0.8314 | test_loss=0.1024 test_acc=0.9625
Epoch 13 | train_loss=0.1973 train_acc=0.9377 | val_loss=0.7623 val_acc=0.7825 | test_loss=0.2266 test_acc=0.9227
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.1785 train_acc=0.9405 | val_loss=0.7488 val_acc=0.8241 | test_loss=0.1386 test_acc=0.9508
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.1619 train_acc=0.9470 | val_loss=0.7758 val_acc=0.8210 | test_loss=0.1311 test_acc=0.9485
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 16 | train_loss=0.1466 train_acc=0.9535 | val_loss=0.8340 val_acc=0.8018 | test_loss=0.1356 test_acc=0.9719
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 17 | train_loss=0.1328 train_acc=0.9569 | val_loss=0.8012 val_acc=0.8232 | test_loss=0.1587 test_acc=0.9485
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 17.
Fold 3 complete | subject=H03 | test_acc=0.9625 | test_macro_f1=0.9660
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3346 train_acc=0.2248 | val_loss=1.7392 val_acc=0.3125 | test_loss=1.5842 test_acc=0.4197
Epoch 02 | train_loss=1.2280 train_acc=0.5369 | val_loss=1.2064 val_acc=0.4838 | test_loss=0.8410 test_acc=0.7445
Epoch 03 | train_loss=0.8704 train_acc=0.6938 | val_loss=1.0557 val_acc=0.6478 | test_loss=0.5638 test_acc=0.8321
Epoch 04 | train_loss=0.6822 train_acc=0.7785 | val_loss=1.0882 val_acc=0.7098 | test_loss=0.4486 test_acc=0.9051
Epoch 05 | train_loss=0.5613 train_acc=0.8189 | val_loss=0.9657 val_acc=0.7462 | test_loss=0.3865 test_acc=0.8869
Epoch 06 | train_loss=0.4748 train_acc=0.8483 | val_loss=1.0065 val_acc=0.7489 | test_loss=0.3600 test_acc=0.9270
Epoch 07 | train_loss=0.4064 train_acc=0.8693 | val_loss=0.9647 val_acc=0.7535 | test_loss=0.3392 test_acc=0.9197
Epoch 08 | train_loss=0.3528 train_acc=0.8860 | val_loss=0.7635 val_acc=0.7892 | test_loss=0.2674 test_acc=0.9343
Epoch 09 | train_loss=0.3169 train_acc=0.8959 | val_loss=0.8834 val_acc=0.7651 | test_loss=0.3105 test_acc=0.9197
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2840 train_acc=0.9024 | val_loss=0.8603 val_acc=0.7688 | test_loss=0.3152 test_acc=0.8978
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.2521 train_acc=0.9142 | val_loss=0.8806 val_acc=0.7654 | test_loss=0.2766 test_acc=0.9380
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 12 | train_loss=0.2270 train_acc=0.9207 | val_loss=0.8950 val_acc=0.7810 | test_loss=0.2444 test_acc=0.9453
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 13 | train_loss=0.2129 train_acc=0.9272 | val_loss=0.7754 val_acc=0.7957 | test_loss=0.1993 test_acc=0.9453
Epoch 14 | train_loss=0.1912 train_acc=0.9354 | val_loss=0.7758 val_acc=0.8134 | test_loss=0.1982 test_acc=0.9745
Epoch 15 | train_loss=0.1717 train_acc=0.9426 | val_loss=0.8779 val_acc=0.7951 | test_loss=0.2515 test_acc=0.9599
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.1564 train_acc=0.9484 | val_loss=0.7893 val_acc=0.8057 | test_loss=0.2068 test_acc=0.9307
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 17 | train_loss=0.1423 train_acc=0.9527 | val_loss=0.7981 val_acc=0.8112 | test_loss=0.2015 test_acc=0.9453
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 18 | train_loss=0.1294 train_acc=0.9590 | val_loss=0.8213 val_acc=0.8015 | test_loss=0.2504 test_acc=0.9453
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 19 | train_loss=0.1200 train_acc=0.9612 | val_loss=0.8655 val_acc=0.7920 | test_loss=0.1838 test_acc=0.9489
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 19.
Fold 4 complete | subject=H04 | test_acc=0.9745 | test_macro_f1=0.8698
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4484 train_acc=0.1995 | val_loss=1.8922 val_acc=0.2440 | test_loss=1.5370 test_acc=0.2591
Epoch 02 | train_loss=1.2446 train_acc=0.5519 | val_loss=1.2893 val_acc=0.4609 | test_loss=1.0236 test_acc=0.5265
Epoch 03 | train_loss=0.8364 train_acc=0.7404 | val_loss=1.0647 val_acc=0.6570 | test_loss=0.7267 test_acc=0.7382
Epoch 04 | train_loss=0.6431 train_acc=0.8078 | val_loss=1.0660 val_acc=0.7254 | test_loss=0.6480 test_acc=0.7604
Epoch 05 | train_loss=0.5225 train_acc=0.8485 | val_loss=0.9720 val_acc=0.7376 | test_loss=0.6266 test_acc=0.7688
Epoch 06 | train_loss=0.4356 train_acc=0.8719 | val_loss=0.9922 val_acc=0.7031 | test_loss=0.5880 test_acc=0.7660
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.3792 train_acc=0.8864 | val_loss=1.0792 val_acc=0.7007 | test_loss=0.6525 test_acc=0.7744
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 08 | train_loss=0.3327 train_acc=0.8945 | val_loss=1.1434 val_acc=0.7392 | test_loss=0.4752 test_acc=0.8357
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 09 | train_loss=0.2923 train_acc=0.9109 | val_loss=0.9364 val_acc=0.7489 | test_loss=0.5794 test_acc=0.7827
Epoch 10 | train_loss=0.2653 train_acc=0.9190 | val_loss=0.8073 val_acc=0.7926 | test_loss=0.4866 test_acc=0.8217
Epoch 11 | train_loss=0.2353 train_acc=0.9259 | val_loss=0.9079 val_acc=0.7740 | test_loss=0.5478 test_acc=0.7883
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.2158 train_acc=0.9310 | val_loss=0.9622 val_acc=0.7529 | test_loss=0.5097 test_acc=0.8022
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.1928 train_acc=0.9405 | val_loss=0.8838 val_acc=0.7731 | test_loss=0.5283 test_acc=0.7799
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 14 | train_loss=0.1794 train_acc=0.9438 | val_loss=0.9487 val_acc=0.7743 | test_loss=0.5652 test_acc=0.7660
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 15 | train_loss=0.1596 train_acc=0.9501 | val_loss=0.8096 val_acc=0.8070 | test_loss=0.4937 test_acc=0.7967

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,19,0.816873,0.907776,0.889508
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,20,0.806964,0.936090,0.962316
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,17,0.831399,0.962529,0.965966
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,19,0.813378,0.974453,0.869826
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,20,0.806964,0.796657,0.830614
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,14,0.804520,0.865497,0.884448
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,20,0.811546,0.934037,0.950605
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,20,0.794746,0.955224,0.959545
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,20,0.808186,0.527859,0.539040
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,17,0.716605,0.756818,0.680755
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,13,0.702501,0.584270,0.399070
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,18,0.712613,0.804261,0.826949
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,13,0.673833,0.990385,0.993639
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,18,0.647935,0.815115,0.785930
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,15,0.683850,0.834983,0.794312
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,15,0.656731,0.740448,0.732595
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,20,0.720254,0.995902,0.981658
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,20,0.724823,0.644089,0.655614
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,19,0.741560,0.959677,0.963141
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,14,0.744718,0.833605,0.798123
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,20,0.770540,0.953411,0.935651
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,15,0.759096,0.926230,0.943796
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,18,0.755575,0.711864,0.716269
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,20,0.761444,0.955882,0.953004
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,20,0.766138,0.839252,0.789757

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.8110
Overall window-level macro F1: 0.8041
Mean fold accuracy: 0.8483 ± 0.1293
Mean fold macro F1: 0.8321 ± 0.1491
Saved summary CSV: experiment_results/segment_combination_study__combo-ForeArm__Hand__nseg-2__win-4s__step-0.5s__20260407_161056__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-ForeArm__Hand__nseg-2__win-4s__step-0.5s__20260407_161056__folds.csv

====================================================================================================
Combination run 9/15
Canonical combo: ['ForeArm', 'Shoulder']
Selected segment labels: ['LeftForeArm', 'RightForeArm', 'LeftShoulder', 'RightShoulder']
No cached dataset found. Building dataset from MVNX files...
Kept files: 1420 | Skipped files (allowed but failed): 88
X: (14521, 240, 12) y: (14521,) groups: (14521,)
Saved dataset cache to: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftForeArm_RightForeArm_LeftShoulder_RightShoulder__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (ForeArm+Shoulder) dataset loaded.
Dataset shape: (14521, 240, 12)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 12)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3355 train_acc=0.2400 | val_loss=1.8534 val_acc=0.2564 | test_loss=1.7745 test_acc=0.2893
Epoch 02 | train_loss=1.2065 train_acc=0.5080 | val_loss=1.3241 val_acc=0.3960 | test_loss=1.3262 test_acc=0.3526
Epoch 03 | train_loss=0.8426 train_acc=0.6543 | val_loss=1.1943 val_acc=0.4593 | test_loss=1.0836 test_acc=0.4521
Epoch 04 | train_loss=0.6768 train_acc=0.7448 | val_loss=1.2364 val_acc=0.5008 | test_loss=1.0982 test_acc=0.4485
Epoch 05 | train_loss=0.5505 train_acc=0.8056 | val_loss=1.0433 val_acc=0.6428 | test_loss=0.8959 test_acc=0.6203
Epoch 06 | train_loss=0.4600 train_acc=0.8456 | val_loss=1.0239 val_acc=0.6632 | test_loss=0.8581 test_acc=0.6347
Epoch 07 | train_loss=0.3924 train_acc=0.8720 | val_loss=1.0662 val_acc=0.6699 | test_loss=0.8838 test_acc=0.6655
Epoch 08 | train_loss=0.3364 train_acc=0.8903 | val_loss=1.2254 val_acc=0.6545 | test_loss=1.0902 test_acc=0.6004
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.3023 train_acc=0.9007 | val_loss=1.0573 val_acc=0.6994 | test_loss=0.8603 test_acc=0.6944
Epoch 10 | train_loss=0.2644 train_acc=0.9164 | val_loss=1.0992 val_acc=0.6900 | test_loss=0.9817 test_acc=0.6781
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.2337 train_acc=0.9268 | val_loss=1.0817 val_acc=0.7071 | test_loss=0.8967 test_acc=0.6926
Epoch 12 | train_loss=0.2060 train_acc=0.9329 | val_loss=1.1156 val_acc=0.7101 | test_loss=0.9393 test_acc=0.6763
Epoch 13 | train_loss=0.1868 train_acc=0.9402 | val_loss=1.0750 val_acc=0.7322 | test_loss=0.9597 test_acc=0.7107
Epoch 14 | train_loss=0.1700 train_acc=0.9494 | val_loss=1.1557 val_acc=0.7251 | test_loss=0.8512 test_acc=0.7541
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.1558 train_acc=0.9532 | val_loss=1.1141 val_acc=0.7228 | test_loss=0.8208 test_acc=0.7089
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 16 | train_loss=0.1357 train_acc=0.9601 | val_loss=1.0034 val_acc=0.7549 | test_loss=0.6349 test_acc=0.8083
Epoch 17 | train_loss=0.1219 train_acc=0.9647 | val_loss=1.0231 val_acc=0.7482 | test_loss=0.8220 test_acc=0.7595
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 18 | train_loss=0.1114 train_acc=0.9681 | val_loss=1.0374 val_acc=0.7238 | test_loss=0.8846 test_acc=0.7125
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 19 | train_loss=0.1024 train_acc=0.9713 | val_loss=1.0625 val_acc=0.7369 | test_loss=0.7427 test_acc=0.7559
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 20 | train_loss=0.0951 train_acc=0.9740 | val_loss=1.1634 val_acc=0.7265 | test_loss=0.8966 test_acc=0.7016
  No validation improvement greater than 0.0020. Patience: 4/5
Fold 1 complete | subject=H01 | test_acc=0.8083 | test_macro_f1=0.7683
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3225 train_acc=0.2515 | val_loss=1.9011 val_acc=0.2639 | test_loss=1.5185 test_acc=0.3120
Epoch 02 | train_loss=1.2167 train_acc=0.4860 | val_loss=1.3316 val_acc=0.3910 | test_loss=0.9772 test_acc=0.4925
Epoch 03 | train_loss=0.8599 train_acc=0.6545 | val_loss=1.1717 val_acc=0.4939 | test_loss=0.6500 test_acc=0.6429
Epoch 04 | train_loss=0.6695 train_acc=0.7395 | val_loss=1.0897 val_acc=0.5773 | test_loss=0.5322 test_acc=0.7519
Epoch 05 | train_loss=0.5468 train_acc=0.7962 | val_loss=1.1033 val_acc=0.6579 | test_loss=0.5151 test_acc=0.8158
Epoch 06 | train_loss=0.4608 train_acc=0.8354 | val_loss=0.9386 val_acc=0.6451 | test_loss=0.3928 test_acc=0.8534
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.3945 train_acc=0.8631 | val_loss=1.0899 val_acc=0.6497 | test_loss=0.2443 test_acc=0.9511
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 08 | train_loss=0.3450 train_acc=0.8794 | val_loss=0.8461 val_acc=0.7169 | test_loss=0.2663 test_acc=0.9023
Epoch 09 | train_loss=0.2987 train_acc=0.8980 | val_loss=0.9118 val_acc=0.7175 | test_loss=0.2576 test_acc=0.9211
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2702 train_acc=0.9087 | val_loss=1.0287 val_acc=0.7086 | test_loss=0.2521 test_acc=0.9211
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.2341 train_acc=0.9214 | val_loss=0.9235 val_acc=0.7312 | test_loss=0.2621 test_acc=0.9248
Epoch 12 | train_loss=0.2135 train_acc=0.9294 | val_loss=0.8735 val_acc=0.7288 | test_loss=0.2415 test_acc=0.9211
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.1872 train_acc=0.9378 | val_loss=0.9829 val_acc=0.7306 | test_loss=0.2229 test_acc=0.9286
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.1709 train_acc=0.9475 | val_loss=0.9210 val_acc=0.7379 | test_loss=0.2809 test_acc=0.9060
Epoch 15 | train_loss=0.1540 train_acc=0.9510 | val_loss=0.9690 val_acc=0.7370 | test_loss=0.1911 test_acc=0.9361
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.1372 train_acc=0.9573 | val_loss=0.8641 val_acc=0.7587 | test_loss=0.2722 test_acc=0.9060
Epoch 17 | train_loss=0.1241 train_acc=0.9618 | val_loss=0.8336 val_acc=0.7666 | test_loss=0.3983 test_acc=0.8647
Epoch 18 | train_loss=0.1137 train_acc=0.9652 | val_loss=1.0720 val_acc=0.7334 | test_loss=0.2136 test_acc=0.9361
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 19 | train_loss=0.1009 train_acc=0.9723 | val_loss=0.8994 val_acc=0.7679 | test_loss=0.2314 test_acc=0.9361
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 20 | train_loss=0.0958 train_acc=0.9730 | val_loss=1.0208 val_acc=0.7611 | test_loss=0.2837 test_acc=0.9248
  No validation improvement greater than 0.0020. Patience: 3/5
Fold 2 complete | subject=H02 | test_acc=0.8647 | test_macro_f1=0.8154
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4179 train_acc=0.2767 | val_loss=2.0434 val_acc=0.2422 | test_loss=1.5225 test_acc=0.3349
Epoch 02 | train_loss=1.2473 train_acc=0.5107 | val_loss=1.2956 val_acc=0.4013 | test_loss=0.7284 test_acc=0.6300
Epoch 03 | train_loss=0.8718 train_acc=0.6517 | val_loss=1.2010 val_acc=0.5147 | test_loss=0.4727 test_acc=0.7073
Epoch 04 | train_loss=0.6963 train_acc=0.7481 | val_loss=1.2244 val_acc=0.5220 | test_loss=0.4387 test_acc=0.7681
Epoch 05 | train_loss=0.5689 train_acc=0.8105 | val_loss=1.0402 val_acc=0.6347 | test_loss=0.4187 test_acc=0.7986
Epoch 06 | train_loss=0.4723 train_acc=0.8460 | val_loss=1.1300 val_acc=0.6258 | test_loss=0.4169 test_acc=0.8361
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.4042 train_acc=0.8675 | val_loss=1.1323 val_acc=0.6597 | test_loss=0.3791 test_acc=0.8735
Epoch 08 | train_loss=0.3483 train_acc=0.8866 | val_loss=1.0207 val_acc=0.6830 | test_loss=0.3308 test_acc=0.8642
Epoch 09 | train_loss=0.3086 train_acc=0.8972 | val_loss=1.2713 val_acc=0.6500 | test_loss=0.4304 test_acc=0.8501
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2705 train_acc=0.9095 | val_loss=1.0116 val_acc=0.6720 | test_loss=0.2342 test_acc=0.9133
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.2441 train_acc=0.9235 | val_loss=1.1700 val_acc=0.6454 | test_loss=0.3127 test_acc=0.8946
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 12 | train_loss=0.2185 train_acc=0.9293 | val_loss=1.0957 val_acc=0.6591 | test_loss=0.2503 test_acc=0.9133
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 13 | train_loss=0.1971 train_acc=0.9358 | val_loss=0.9775 val_acc=0.7337 | test_loss=0.2555 test_acc=0.9063
Epoch 14 | train_loss=0.1746 train_acc=0.9445 | val_loss=1.0193 val_acc=0.7144 | test_loss=0.2028 test_acc=0.9251
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.1615 train_acc=0.9500 | val_loss=1.0172 val_acc=0.7443 | test_loss=0.1547 test_acc=0.9438
Epoch 16 | train_loss=0.1465 train_acc=0.9540 | val_loss=0.9395 val_acc=0.7358 | test_loss=0.1720 test_acc=0.9344
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.1321 train_acc=0.9591 | val_loss=1.0081 val_acc=0.7358 | test_loss=0.2428 test_acc=0.9087
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.1183 train_acc=0.9648 | val_loss=1.0348 val_acc=0.7398 | test_loss=0.1801 test_acc=0.9297
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 19 | train_loss=0.1123 train_acc=0.9646 | val_loss=1.0428 val_acc=0.7260 | test_loss=0.3232 test_acc=0.8946
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 20 | train_loss=0.0988 train_acc=0.9728 | val_loss=1.1213 val_acc=0.6998 | test_loss=0.1971 test_acc=0.9110
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 20.
Fold 3 complete | subject=H03 | test_acc=0.9438 | test_macro_f1=0.9375
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3177 train_acc=0.3582 | val_loss=1.8143 val_acc=0.2547 | test_loss=1.6300 test_acc=0.3467
Epoch 02 | train_loss=1.2321 train_acc=0.5040 | val_loss=1.3116 val_acc=0.4331 | test_loss=1.0383 test_acc=0.5474
Epoch 03 | train_loss=0.8951 train_acc=0.6401 | val_loss=1.2273 val_acc=0.5070 | test_loss=0.7946 test_acc=0.6168
Epoch 04 | train_loss=0.7055 train_acc=0.7326 | val_loss=1.1988 val_acc=0.5828 | test_loss=0.5829 test_acc=0.8358
Epoch 05 | train_loss=0.5749 train_acc=0.8077 | val_loss=1.0402 val_acc=0.6411 | test_loss=0.4148 test_acc=0.8723
Epoch 06 | train_loss=0.4691 train_acc=0.8470 | val_loss=1.0291 val_acc=0.6619 | test_loss=0.3467 test_acc=0.9197
Epoch 07 | train_loss=0.3993 train_acc=0.8670 | val_loss=0.9243 val_acc=0.7162 | test_loss=0.3018 test_acc=0.9161
Epoch 08 | train_loss=0.3427 train_acc=0.8866 | val_loss=0.9766 val_acc=0.6796 | test_loss=0.3367 test_acc=0.8686
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2987 train_acc=0.9029 | val_loss=0.9115 val_acc=0.7217 | test_loss=0.2385 test_acc=0.9307
Epoch 10 | train_loss=0.2639 train_acc=0.9130 | val_loss=0.9074 val_acc=0.7260 | test_loss=0.2410 test_acc=0.9161
Epoch 11 | train_loss=0.2365 train_acc=0.9243 | val_loss=0.9907 val_acc=0.7352 | test_loss=0.2798 test_acc=0.9270
Epoch 12 | train_loss=0.2069 train_acc=0.9330 | val_loss=0.8903 val_acc=0.7514 | test_loss=0.2049 test_acc=0.9489
Epoch 13 | train_loss=0.1848 train_acc=0.9403 | val_loss=1.0851 val_acc=0.7251 | test_loss=0.2462 test_acc=0.9453
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.1653 train_acc=0.9454 | val_loss=0.9858 val_acc=0.7272 | test_loss=0.2967 test_acc=0.8978
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.1480 train_acc=0.9543 | val_loss=1.0197 val_acc=0.7193 | test_loss=0.2333 test_acc=0.9343
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 16 | train_loss=0.1347 train_acc=0.9598 | val_loss=0.9859 val_acc=0.7315 | test_loss=0.1914 test_acc=0.9489
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 17 | train_loss=0.1231 train_acc=0.9652 | val_loss=0.9698 val_acc=0.7550 | test_loss=0.2264 test_acc=0.9343
Epoch 18 | train_loss=0.1118 train_acc=0.9679 | val_loss=1.1180 val_acc=0.7114 | test_loss=0.2255 test_acc=0.9416
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 19 | train_loss=0.1025 train_acc=0.9717 | val_loss=1.0956 val_acc=0.7343 | test_loss=0.2668 test_acc=0.9270
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 20 | train_loss=0.0915 train_acc=0.9734 | val_loss=1.0348 val_acc=0.7523 | test_loss=0.2646 test_acc=0.9453
  No validation improvement greater than 0.0020. Patience: 3/5
Fold 4 complete | subject=H04 | test_acc=0.9343 | test_macro_f1=0.9063
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2767 train_acc=0.3384 | val_loss=1.8403 val_acc=0.3164 | test_loss=1.3568 test_acc=0.4318
Epoch 02 | train_loss=1.1841 train_acc=0.5393 | val_loss=1.3470 val_acc=0.4676 | test_loss=0.9321 test_acc=0.5627
Epoch 03 | train_loss=0.8390 train_acc=0.6755 | val_loss=1.0854 val_acc=0.5596 | test_loss=0.7170 test_acc=0.6128
Epoch 04 | train_loss=0.6658 train_acc=0.7604 | val_loss=1.1207 val_acc=0.6081 | test_loss=0.6899 test_acc=0.6964
Epoch 05 | train_loss=0.5426 train_acc=0.8225 | val_loss=1.0269 val_acc=0.6506 | test_loss=0.5348 test_acc=0.7911
Epoch 06 | train_loss=0.4537 train_acc=0.8501 | val_loss=1.0242 val_acc=0.6692 | test_loss=0.5560 test_acc=0.7632
Epoch 07 | train_loss=0.3918 train_acc=0.8700 | val_loss=1.0544 val_acc=0.6878 | test_loss=0.5796 test_acc=0.7716
Epoch 08 | train_loss=0.3337 train_acc=0.8870 | val_loss=1.0332 val_acc=0.6680 | test_loss=0.5245 test_acc=0.7521
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2951 train_acc=0.9037 | val_loss=1.1583 val_acc=0.6729 | test_loss=0.5805 test_acc=0.8050
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 10 | train_loss=0.2601 train_acc=0.9149 | val_loss=1.0460 val_acc=0.7022 | test_loss=0.5017 test_acc=0.8106
Epoch 11 | train_loss=0.2266 train_acc=0.9267 | val_loss=0.9748 val_acc=0.7224 | test_loss=0.3954 test_acc=0.8384
Epoch 12 | train_loss=0.2048 train_acc=0.9325 | val_loss=1.1372 val_acc=0.6988 | test_loss=0.4729 test_acc=0.8329
  No validation improvement greater than 0.0020. Patience: 1/5

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,20,0.754938,0.808318,0.768283
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,20,0.766646,0.864662,0.815369
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,20,0.744349,0.943794,0.937451
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,20,0.755040,0.934307,0.906285
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,18,0.730605,0.788301,0.803085
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,16,0.724801,0.798246,0.815768
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,20,0.752291,0.912929,0.889454
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,14,0.740073,0.906716,0.892238
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,20,0.759621,0.450147,0.452471
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,15,0.661788,0.631818,0.643033
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,20,0.683608,0.464419,0.284669
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,20,0.674827,0.776298,0.799418
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,19,0.665771,0.985577,0.985730
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,20,0.677742,0.871795,0.849250
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,20,0.662595,0.907591,0.882883
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,19,0.659174,0.787879,0.777582
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,20,0.674811,0.971311,0.959912
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,17,0.672908,0.689655,0.655501
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,12,0.670638,0.923387,0.930016
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,20,0.706866,0.833605,0.782537
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,20,0.720657,0.891847,0.855879
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,20,0.706573,0.934426,0.949176
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,20,0.707453,0.749529,0.757487
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,20,0.718603,0.909314,0.937206
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,18,0.701878,0.704673,0.632985

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.7837
Overall window-level macro F1: 0.7783
Mean fold accuracy: 0.8176 ± 0.1418
Mean fold macro F1: 0.7985 ± 0.1634
Saved summary CSV: experiment_results/segment_combination_study__combo-ForeArm__Shoulder__nseg-2__win-4s__step-0.5s__20260407_163041__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-ForeArm__Shoulder__nseg-2__win-4s__step-0.5s__20260407_163041__folds.csv

====================================================================================================
Combination run 10/15
Canonical combo: ['Hand', 'Shoulder']
Selected segment labels: ['LeftHand', 'RightHand', 'LeftShoulder', 'RightShoulder']
No cached dataset found. Building dataset from MVNX files...
Kept files: 1420 | Skipped files (allowed but failed): 88
X: (14521, 240, 12) y: (14521,) groups: (14521,)
Saved dataset cache to: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftHand_RightHand_LeftShoulder_RightShoulder__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (Hand+Shoulder) dataset loaded.
Dataset shape: (14521, 240, 12)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 12)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3481 train_acc=0.3260 | val_loss=2.0062 val_acc=0.2444 | test_loss=1.8350 test_acc=0.2369
Epoch 02 | train_loss=1.2438 train_acc=0.5839 | val_loss=1.2859 val_acc=0.5149 | test_loss=1.0367 test_acc=0.5009
Epoch 03 | train_loss=0.8587 train_acc=0.7238 | val_loss=1.2218 val_acc=0.5862 | test_loss=0.9298 test_acc=0.5244
Epoch 04 | train_loss=0.6725 train_acc=0.7833 | val_loss=0.9607 val_acc=0.6937 | test_loss=0.6645 test_acc=0.6203
Epoch 05 | train_loss=0.5416 train_acc=0.8236 | val_loss=0.9534 val_acc=0.7097 | test_loss=0.6476 test_acc=0.6130
Epoch 06 | train_loss=0.4526 train_acc=0.8566 | val_loss=0.9356 val_acc=0.7218 | test_loss=0.5831 test_acc=0.6655
Epoch 07 | train_loss=0.3866 train_acc=0.8772 | val_loss=0.9138 val_acc=0.7365 | test_loss=0.6028 test_acc=0.6691
Epoch 08 | train_loss=0.3347 train_acc=0.8879 | val_loss=0.9156 val_acc=0.7415 | test_loss=0.5864 test_acc=0.6691
Epoch 09 | train_loss=0.2913 train_acc=0.9077 | val_loss=0.8401 val_acc=0.7613 | test_loss=0.4252 test_acc=0.7541
Epoch 10 | train_loss=0.2572 train_acc=0.9167 | val_loss=0.8502 val_acc=0.7576 | test_loss=0.4490 test_acc=0.7360
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.2228 train_acc=0.9292 | val_loss=0.9319 val_acc=0.7412 | test_loss=0.4895 test_acc=0.7143
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.2033 train_acc=0.9343 | val_loss=0.7826 val_acc=0.7747 | test_loss=0.3727 test_acc=0.8047
Epoch 13 | train_loss=0.1780 train_acc=0.9422 | val_loss=0.9606 val_acc=0.7553 | test_loss=0.5313 test_acc=0.7233
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.1634 train_acc=0.9482 | val_loss=0.9364 val_acc=0.7610 | test_loss=0.4642 test_acc=0.7324
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.1425 train_acc=0.9550 | val_loss=0.9855 val_acc=0.7385 | test_loss=0.6465 test_acc=0.6474
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 16 | train_loss=0.1308 train_acc=0.9607 | val_loss=1.0655 val_acc=0.7225 | test_loss=0.5863 test_acc=0.6637
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 17 | train_loss=0.1179 train_acc=0.9646 | val_loss=0.8979 val_acc=0.7757 | test_loss=0.3210 test_acc=0.8300
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 17.
Fold 1 complete | subject=H01 | test_acc=0.8047 | test_macro_f1=0.8024
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3382 train_acc=0.2666 | val_loss=1.8806 val_acc=0.2712 | test_loss=1.4323 test_acc=0.3534
Epoch 02 | train_loss=1.2541 train_acc=0.5460 | val_loss=1.2905 val_acc=0.4991 | test_loss=0.7508 test_acc=0.6429
Epoch 03 | train_loss=0.8516 train_acc=0.7231 | val_loss=1.0565 val_acc=0.6521 | test_loss=0.5718 test_acc=0.7594
Epoch 04 | train_loss=0.6632 train_acc=0.7863 | val_loss=1.0209 val_acc=0.6878 | test_loss=0.4882 test_acc=0.7594
Epoch 05 | train_loss=0.5281 train_acc=0.8333 | val_loss=0.9432 val_acc=0.7208 | test_loss=0.4198 test_acc=0.8271
Epoch 06 | train_loss=0.4355 train_acc=0.8621 | val_loss=0.8335 val_acc=0.7401 | test_loss=0.3172 test_acc=0.8910
Epoch 07 | train_loss=0.3711 train_acc=0.8827 | val_loss=0.8046 val_acc=0.7560 | test_loss=0.2532 test_acc=0.9286
Epoch 08 | train_loss=0.3177 train_acc=0.8977 | val_loss=0.8510 val_acc=0.7416 | test_loss=0.2812 test_acc=0.9023
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2809 train_acc=0.9052 | val_loss=0.7997 val_acc=0.7611 | test_loss=0.2882 test_acc=0.8797
Epoch 10 | train_loss=0.2451 train_acc=0.9199 | val_loss=0.8192 val_acc=0.7596 | test_loss=0.2738 test_acc=0.9023
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.2192 train_acc=0.9288 | val_loss=0.7963 val_acc=0.7566 | test_loss=0.2349 test_acc=0.8985
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.1941 train_acc=0.9356 | val_loss=0.7746 val_acc=0.7767 | test_loss=0.2439 test_acc=0.9173
Epoch 13 | train_loss=0.1739 train_acc=0.9460 | val_loss=0.8957 val_acc=0.7581 | test_loss=0.3250 test_acc=0.8797
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.1548 train_acc=0.9494 | val_loss=0.7739 val_acc=0.7740 | test_loss=0.4057 test_acc=0.8609
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.1416 train_acc=0.9550 | val_loss=0.8631 val_acc=0.7611 | test_loss=0.2031 test_acc=0.9211
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 16 | train_loss=0.1258 train_acc=0.9591 | val_loss=0.8565 val_acc=0.7776 | test_loss=0.2768 test_acc=0.9135
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 17 | train_loss=0.1152 train_acc=0.9634 | val_loss=0.8087 val_acc=0.7828 | test_loss=0.4234 test_acc=0.8684
Epoch 18 | train_loss=0.1046 train_acc=0.9684 | val_loss=0.9601 val_acc=0.7599 | test_loss=0.3194 test_acc=0.8684
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 19 | train_loss=0.0919 train_acc=0.9749 | val_loss=0.8423 val_acc=0.7743 | test_loss=0.3750 test_acc=0.8835
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 20 | train_loss=0.0817 train_acc=0.9770 | val_loss=0.7665 val_acc=0.7917 | test_loss=0.3681 test_acc=0.9023
Fold 2 complete | subject=H02 | test_acc=0.9023 | test_macro_f1=0.8730
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.5144 train_acc=0.1933 | val_loss=2.1449 val_acc=0.2166 | test_loss=1.7385 test_acc=0.3372
Epoch 02 | train_loss=1.3528 train_acc=0.4723 | val_loss=1.3279 val_acc=0.4319 | test_loss=0.7603 test_acc=0.6042
Epoch 03 | train_loss=0.9143 train_acc=0.6724 | val_loss=1.2033 val_acc=0.5977 | test_loss=0.6000 test_acc=0.6979
Epoch 04 | train_loss=0.7116 train_acc=0.7616 | val_loss=1.0075 val_acc=0.6710 | test_loss=0.4840 test_acc=0.8103
Epoch 05 | train_loss=0.5877 train_acc=0.8017 | val_loss=0.9595 val_acc=0.7049 | test_loss=0.4272 test_acc=0.8337
Epoch 06 | train_loss=0.4947 train_acc=0.8355 | val_loss=0.9345 val_acc=0.7193 | test_loss=0.3202 test_acc=0.8712
Epoch 07 | train_loss=0.4182 train_acc=0.8555 | val_loss=0.9171 val_acc=0.7025 | test_loss=0.2848 test_acc=0.8806
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.3561 train_acc=0.8844 | val_loss=0.8555 val_acc=0.7462 | test_loss=0.2462 test_acc=0.9157
Epoch 09 | train_loss=0.3129 train_acc=0.8996 | val_loss=0.8753 val_acc=0.7520 | test_loss=0.1948 test_acc=0.9321
Epoch 10 | train_loss=0.2726 train_acc=0.9073 | val_loss=1.0312 val_acc=0.7279 | test_loss=0.2212 test_acc=0.9297
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.2419 train_acc=0.9226 | val_loss=0.9718 val_acc=0.7330 | test_loss=0.1844 test_acc=0.9297
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.2155 train_acc=0.9311 | val_loss=1.0314 val_acc=0.7187 | test_loss=0.2303 test_acc=0.9274
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 13 | train_loss=0.1868 train_acc=0.9395 | val_loss=0.9874 val_acc=0.7532 | test_loss=0.1214 test_acc=0.9578
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 14 | train_loss=0.1738 train_acc=0.9459 | val_loss=0.9068 val_acc=0.7544 | test_loss=0.1303 test_acc=0.9508
Epoch 15 | train_loss=0.1560 train_acc=0.9505 | val_loss=0.9884 val_acc=0.7434 | test_loss=0.1378 test_acc=0.9532
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.1392 train_acc=0.9569 | val_loss=1.0523 val_acc=0.7251 | test_loss=0.1383 test_acc=0.9461
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 17 | train_loss=0.1253 train_acc=0.9614 | val_loss=1.0211 val_acc=0.7419 | test_loss=0.0866 test_acc=0.9602
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 18 | train_loss=0.1119 train_acc=0.9673 | val_loss=1.0146 val_acc=0.7431 | test_loss=0.0888 test_acc=0.9602
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 19 | train_loss=0.1029 train_acc=0.9693 | val_loss=0.8301 val_acc=0.7639 | test_loss=0.0938 test_acc=0.9625
Epoch 20 | train_loss=0.0913 train_acc=0.9730 | val_loss=0.9428 val_acc=0.7694 | test_loss=0.0742 test_acc=0.9696
Fold 3 complete | subject=H03 | test_acc=0.9696 | test_macro_f1=0.9731
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3371 train_acc=0.2328 | val_loss=1.8581 val_acc=0.2731 | test_loss=1.6501 test_acc=0.3686
Epoch 02 | train_loss=1.2527 train_acc=0.5202 | val_loss=1.3095 val_acc=0.4896 | test_loss=0.9661 test_acc=0.7409
Epoch 03 | train_loss=0.8558 train_acc=0.7155 | val_loss=1.0222 val_acc=0.6503 | test_loss=0.6616 test_acc=0.8212
Epoch 04 | train_loss=0.6699 train_acc=0.7827 | val_loss=1.0020 val_acc=0.6588 | test_loss=0.4661 test_acc=0.8759
Epoch 05 | train_loss=0.5363 train_acc=0.8282 | val_loss=0.8240 val_acc=0.7404 | test_loss=0.3821 test_acc=0.8978
Epoch 06 | train_loss=0.4430 train_acc=0.8596 | val_loss=0.7635 val_acc=0.7624 | test_loss=0.3334 test_acc=0.9088
Epoch 07 | train_loss=0.3738 train_acc=0.8811 | val_loss=0.7466 val_acc=0.7801 | test_loss=0.3042 test_acc=0.9124
Epoch 08 | train_loss=0.3204 train_acc=0.8957 | val_loss=0.8155 val_acc=0.7544 | test_loss=0.3255 test_acc=0.9270
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2825 train_acc=0.9059 | val_loss=0.8603 val_acc=0.7437 | test_loss=0.2798 test_acc=0.9051
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 10 | train_loss=0.2425 train_acc=0.9205 | val_loss=0.7697 val_acc=0.7752 | test_loss=0.3080 test_acc=0.9307
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 11 | train_loss=0.2168 train_acc=0.9295 | val_loss=0.9604 val_acc=0.7398 | test_loss=0.3819 test_acc=0.9416
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 12 | train_loss=0.1920 train_acc=0.9353 | val_loss=0.7268 val_acc=0.7987 | test_loss=0.2460 test_acc=0.9562
Epoch 13 | train_loss=0.1731 train_acc=0.9430 | val_loss=0.7000 val_acc=0.8115 | test_loss=0.2244 test_acc=0.9380
Epoch 14 | train_loss=0.1528 train_acc=0.9521 | val_loss=0.7787 val_acc=0.7755 | test_loss=0.3625 test_acc=0.9416
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.1402 train_acc=0.9535 | val_loss=0.9042 val_acc=0.7532 | test_loss=0.4483 test_acc=0.9489
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 16 | train_loss=0.1276 train_acc=0.9595 | val_loss=0.7837 val_acc=0.7700 | test_loss=0.2522 test_acc=0.9745
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 17 | train_loss=0.1173 train_acc=0.9626 | val_loss=1.1250 val_acc=0.7132 | test_loss=0.4212 test_acc=0.9562
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 18 | train_loss=0.1006 train_acc=0.9697 | val_loss=0.9367 val_acc=0.7642 | test_loss=0.3150 test_acc=0.9526
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 18.
Fold 4 complete | subject=H04 | test_acc=0.9380 | test_macro_f1=0.8077
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3011 train_acc=0.2183 | val_loss=1.7915 val_acc=0.2795 | test_loss=1.5689 test_acc=0.2813
Epoch 02 | train_loss=1.2239 train_acc=0.5406 | val_loss=1.2873 val_acc=0.4701 | test_loss=1.0957 test_acc=0.4875
Epoch 03 | train_loss=0.8494 train_acc=0.7151 | val_loss=1.0486 val_acc=0.6381 | test_loss=0.7403 test_acc=0.7883
Epoch 04 | train_loss=0.6653 train_acc=0.7830 | val_loss=1.0245 val_acc=0.6558 | test_loss=0.7073 test_acc=0.7354
Epoch 05 | train_loss=0.5295 train_acc=0.8267 | val_loss=0.9315 val_acc=0.6915 | test_loss=0.6340 test_acc=0.7688
Epoch 06 | train_loss=0.4345 train_acc=0.8579 | val_loss=1.0011 val_acc=0.7089 | test_loss=0.5854 test_acc=0.8329
Epoch 07 | train_loss=0.3628 train_acc=0.8812 | val_loss=0.9412 val_acc=0.7065 | test_loss=0.5857 test_acc=0.7688
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.3175 train_acc=0.8954 | val_loss=0.8387 val_acc=0.7440 | test_loss=0.4926 test_acc=0.7883
Epoch 09 | train_loss=0.2737 train_acc=0.9086 | val_loss=0.9975 val_acc=0.7190 | test_loss=0.5757 test_acc=0.8022
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2377 train_acc=0.9232 | val_loss=0.8518 val_acc=0.7553 | test_loss=0.4479 test_acc=0.8802
Epoch 11 | train_loss=0.2117 train_acc=0.9324 | val_loss=0.8901 val_acc=0.7590 | test_loss=0.4303 test_acc=0.8886
Epoch 12 | train_loss=0.1881 train_acc=0.9365 | val_loss=0.9034 val_acc=0.7532 | test_loss=0.4142 test_acc=0.8942
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.1704 train_acc=0.9443 | val_loss=0.9124 val_acc=0.7532 | test_loss=0.4002 test_acc=0.9081
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.1509 train_acc=0.9507 | val_loss=0.9561 val_acc=0.7596 | test_loss=0.4319 test_acc=0.8301
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 15 | train_loss=0.1370 train_acc=0.9568 | val_loss=1.0065 val_acc=0.7410 | test_loss=0.5048 test_acc=0.7939
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 16 | train_loss=0.1246 train_acc=0.9599 | val_loss=1.0002 val_acc=0.7505 | test_loss=0.4465 test_acc=0.8942
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 16.

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,17,0.774690,0.804702,0.802412
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,20,0.791692,0.902256,0.872989
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,20,0.769395,0.969555,0.973118
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,18,0.811546,0.937956,0.807659
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,16,0.759010,0.888579,0.872559
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,20,0.790470,0.815789,0.824702
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,14,0.755345,0.926121,0.936467
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,20,0.799328,0.929104,0.930579
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,17,0.766035,0.503666,0.546751
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,14,0.655402,0.760227,0.753476
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,10,0.652741,0.430712,0.247305
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,20,0.723257,0.798935,0.811052
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,20,0.676765,0.971154,0.973232
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,14,0.655509,0.808367,0.793329
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,20,0.687271,0.912541,0.826571
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,20,0.689958,0.812912,0.808058
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,18,0.669680,0.971311,0.913748
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,14,0.699858,0.625616,0.587498
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,20,0.727660,0.989919,0.988212
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,17,0.737383,0.845024,0.808538
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,17,0.713028,0.883527,0.854683
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,20,0.747066,0.940574,0.953590
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,12,0.697477,0.722222,0.764954
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,20,0.747359,0.941176,0.950871
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,17,0.723592,0.732710,0.692045

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.7997
Overall window-level macro F1: 0.7995
Mean fold accuracy: 0.8330 ± 0.1436
Mean fold macro F1: 0.8118 ± 0.1623
Saved summary CSV: experiment_results/segment_combination_study__combo-Hand__Shoulder__nseg-2__win-4s__step-0.5s__20260407_164949__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-Hand__Shoulder__nseg-2__win-4s__step-0.5s__20260407_164949__folds.csv

====================================================================================================
Combination run 11/15
Canonical combo: ['UpperArm', 'ForeArm', 'Hand']
Selected segment labels: ['LeftUpperArm', 'RightUpperArm', 'LeftForeArm', 'RightForeArm', 'LeftHand', 'RightHand']
Loading cached dataset from: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftUpperArm_RightUpperArm_LeftForeArm_RightForeArm_LeftHand_RightHand__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (UpperArm+ForeArm+Hand) dataset loaded.
Dataset shape: (14521, 240, 18)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 18)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3958 train_acc=0.2469 | val_loss=1.6894 val_acc=0.3465 | test_loss=1.5089 test_acc=0.3580
Epoch 02 | train_loss=1.1606 train_acc=0.5622 | val_loss=1.1206 val_acc=0.5611 | test_loss=0.9158 test_acc=0.6112
Epoch 03 | train_loss=0.7673 train_acc=0.7520 | val_loss=0.8709 val_acc=0.7148 | test_loss=0.6671 test_acc=0.6872
Epoch 04 | train_loss=0.5695 train_acc=0.8353 | val_loss=0.7679 val_acc=0.7677 | test_loss=0.5155 test_acc=0.7776
Epoch 05 | train_loss=0.4503 train_acc=0.8710 | val_loss=0.6967 val_acc=0.7971 | test_loss=0.4253 test_acc=0.7975
Epoch 06 | train_loss=0.3672 train_acc=0.8957 | val_loss=0.6980 val_acc=0.7924 | test_loss=0.3489 test_acc=0.8391
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.3111 train_acc=0.9128 | val_loss=0.6862 val_acc=0.8082 | test_loss=0.3715 test_acc=0.8318
Epoch 08 | train_loss=0.2671 train_acc=0.9235 | val_loss=0.5961 val_acc=0.8249 | test_loss=0.3399 test_acc=0.8481
Epoch 09 | train_loss=0.2320 train_acc=0.9360 | val_loss=0.5971 val_acc=0.8189 | test_loss=0.3814 test_acc=0.8409
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2032 train_acc=0.9446 | val_loss=0.6318 val_acc=0.8266 | test_loss=0.3489 test_acc=0.8608
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.1811 train_acc=0.9487 | val_loss=0.6448 val_acc=0.8175 | test_loss=0.3012 test_acc=0.8608
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 12 | train_loss=0.1606 train_acc=0.9558 | val_loss=0.6098 val_acc=0.8222 | test_loss=0.3235 test_acc=0.8608
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 13 | train_loss=0.1390 train_acc=0.9630 | val_loss=0.6761 val_acc=0.8209 | test_loss=0.3371 test_acc=0.8698
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 13.
Fold 1 complete | subject=H01 | test_acc=0.8481 | test_macro_f1=0.8115
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3385 train_acc=0.2652 | val_loss=1.6539 val_acc=0.3259 | test_loss=1.3675 test_acc=0.3346
Epoch 02 | train_loss=1.1309 train_acc=0.5575 | val_loss=1.1144 val_acc=0.5046 | test_loss=0.6792 test_acc=0.5827
Epoch 03 | train_loss=0.7576 train_acc=0.7194 | val_loss=0.9315 val_acc=0.6494 | test_loss=0.4613 test_acc=0.7218
Epoch 04 | train_loss=0.5647 train_acc=0.8255 | val_loss=0.9004 val_acc=0.7104 | test_loss=0.3971 test_acc=0.7556
Epoch 05 | train_loss=0.4388 train_acc=0.8720 | val_loss=0.7466 val_acc=0.7477 | test_loss=0.2245 test_acc=0.9135
Epoch 06 | train_loss=0.3578 train_acc=0.8951 | val_loss=0.8178 val_acc=0.7526 | test_loss=0.2337 test_acc=0.9248
Epoch 07 | train_loss=0.3015 train_acc=0.9144 | val_loss=0.7653 val_acc=0.7572 | test_loss=0.1593 test_acc=0.9624
Epoch 08 | train_loss=0.2559 train_acc=0.9250 | val_loss=0.7021 val_acc=0.7792 | test_loss=0.1378 test_acc=0.9586
Epoch 09 | train_loss=0.2207 train_acc=0.9356 | val_loss=0.7742 val_acc=0.7987 | test_loss=0.1590 test_acc=0.9474
Epoch 10 | train_loss=0.1886 train_acc=0.9471 | val_loss=0.6657 val_acc=0.8232 | test_loss=0.2272 test_acc=0.9173
Epoch 11 | train_loss=0.1691 train_acc=0.9491 | val_loss=0.7374 val_acc=0.7749 | test_loss=0.1395 test_acc=0.9624
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.1490 train_acc=0.9588 | val_loss=0.6827 val_acc=0.7966 | test_loss=0.1447 test_acc=0.9398
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.1359 train_acc=0.9635 | val_loss=0.7106 val_acc=0.8088 | test_loss=0.1636 test_acc=0.9323
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 14 | train_loss=0.1185 train_acc=0.9695 | val_loss=0.7494 val_acc=0.8027 | test_loss=0.1375 test_acc=0.9398
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 15 | train_loss=0.1047 train_acc=0.9719 | val_loss=0.6093 val_acc=0.8109 | test_loss=0.1047 test_acc=0.9624
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 15.
Fold 2 complete | subject=H02 | test_acc=0.9173 | test_macro_f1=0.8776
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4713 train_acc=0.2841 | val_loss=1.6349 val_acc=0.3390 | test_loss=1.0744 test_acc=0.5480
Epoch 02 | train_loss=1.1544 train_acc=0.5834 | val_loss=1.2326 val_acc=0.5189 | test_loss=0.5033 test_acc=0.7471
Epoch 03 | train_loss=0.8009 train_acc=0.7165 | val_loss=0.9972 val_acc=0.6356 | test_loss=0.3433 test_acc=0.8806
Epoch 04 | train_loss=0.6162 train_acc=0.8101 | val_loss=0.9408 val_acc=0.7242 | test_loss=0.2758 test_acc=0.8806
Epoch 05 | train_loss=0.4855 train_acc=0.8512 | val_loss=0.7867 val_acc=0.7276 | test_loss=0.2175 test_acc=0.8970
Epoch 06 | train_loss=0.3920 train_acc=0.8867 | val_loss=0.7670 val_acc=0.7654 | test_loss=0.1729 test_acc=0.9321
Epoch 07 | train_loss=0.3252 train_acc=0.9042 | val_loss=0.7899 val_acc=0.7761 | test_loss=0.1495 test_acc=0.9555
Epoch 08 | train_loss=0.2796 train_acc=0.9162 | val_loss=0.7038 val_acc=0.7850 | test_loss=0.1420 test_acc=0.9461
Epoch 09 | train_loss=0.2437 train_acc=0.9278 | val_loss=0.6563 val_acc=0.8094 | test_loss=0.1060 test_acc=0.9766
Epoch 10 | train_loss=0.2061 train_acc=0.9382 | val_loss=0.6152 val_acc=0.8051 | test_loss=0.1179 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.1839 train_acc=0.9458 | val_loss=0.6097 val_acc=0.8146 | test_loss=0.1022 test_acc=0.9696
Epoch 12 | train_loss=0.1586 train_acc=0.9550 | val_loss=0.7345 val_acc=0.7993 | test_loss=0.1077 test_acc=0.9555
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.1427 train_acc=0.9594 | val_loss=0.6355 val_acc=0.8244 | test_loss=0.0833 test_acc=0.9742
Epoch 14 | train_loss=0.1281 train_acc=0.9634 | val_loss=0.7444 val_acc=0.8067 | test_loss=0.0990 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.1134 train_acc=0.9665 | val_loss=0.5775 val_acc=0.8280 | test_loss=0.0606 test_acc=0.9742
Epoch 16 | train_loss=0.1023 train_acc=0.9745 | val_loss=0.6601 val_acc=0.8302 | test_loss=0.1327 test_acc=0.9555
Epoch 17 | train_loss=0.0890 train_acc=0.9778 | val_loss=0.6685 val_acc=0.8143 | test_loss=0.0708 test_acc=0.9742
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 18 | train_loss=0.0791 train_acc=0.9809 | val_loss=0.6775 val_acc=0.8311 | test_loss=0.0663 test_acc=0.9742
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 19 | train_loss=0.0709 train_acc=0.9834 | val_loss=0.7915 val_acc=0.8070 | test_loss=0.0869 test_acc=0.9649
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 20 | train_loss=0.0652 train_acc=0.9832 | val_loss=0.7294 val_acc=0.8091 | test_loss=0.0711 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 4/5
Fold 3 complete | subject=H03 | test_acc=0.9555 | test_macro_f1=0.9436
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3339 train_acc=0.2304 | val_loss=1.6838 val_acc=0.3097 | test_loss=1.4948 test_acc=0.3540
Epoch 02 | train_loss=1.1480 train_acc=0.5697 | val_loss=1.1969 val_acc=0.5214 | test_loss=0.7639 test_acc=0.7372
Epoch 03 | train_loss=0.7868 train_acc=0.7062 | val_loss=0.8895 val_acc=0.6732 | test_loss=0.4348 test_acc=0.8723
Epoch 04 | train_loss=0.5874 train_acc=0.8048 | val_loss=0.8074 val_acc=0.7086 | test_loss=0.2753 test_acc=0.9161
Epoch 05 | train_loss=0.4599 train_acc=0.8528 | val_loss=0.8309 val_acc=0.7440 | test_loss=0.2029 test_acc=0.9562
Epoch 06 | train_loss=0.3736 train_acc=0.8856 | val_loss=0.6983 val_acc=0.7926 | test_loss=0.1456 test_acc=0.9672
Epoch 07 | train_loss=0.3103 train_acc=0.9060 | val_loss=0.7461 val_acc=0.7795 | test_loss=0.1439 test_acc=0.9635
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.2658 train_acc=0.9181 | val_loss=0.7371 val_acc=0.8088 | test_loss=0.1117 test_acc=0.9781
Epoch 09 | train_loss=0.2330 train_acc=0.9292 | val_loss=0.6738 val_acc=0.8079 | test_loss=0.1136 test_acc=0.9781
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2009 train_acc=0.9369 | val_loss=0.6472 val_acc=0.8238 | test_loss=0.0889 test_acc=0.9854
Epoch 11 | train_loss=0.1792 train_acc=0.9451 | val_loss=0.7962 val_acc=0.7972 | test_loss=0.1407 test_acc=0.9599
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.1584 train_acc=0.9531 | val_loss=0.5776 val_acc=0.8308 | test_loss=0.0789 test_acc=0.9854
Epoch 13 | train_loss=0.1435 train_acc=0.9578 | val_loss=0.7067 val_acc=0.8042 | test_loss=0.1131 test_acc=0.9745
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.1254 train_acc=0.9637 | val_loss=0.7243 val_acc=0.8189 | test_loss=0.0823 test_acc=0.9854
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.1102 train_acc=0.9694 | val_loss=0.6953 val_acc=0.8290 | test_loss=0.0836 test_acc=0.9854
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 16 | train_loss=0.1000 train_acc=0.9721 | val_loss=0.6567 val_acc=0.8415 | test_loss=0.0618 test_acc=0.9854
Epoch 17 | train_loss=0.0905 train_acc=0.9752 | val_loss=0.7105 val_acc=0.8189 | test_loss=0.0690 test_acc=0.9854
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 18 | train_loss=0.0816 train_acc=0.9775 | val_loss=0.8583 val_acc=0.7963 | test_loss=0.0955 test_acc=0.9818
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 19 | train_loss=0.0742 train_acc=0.9797 | val_loss=0.7879 val_acc=0.8213 | test_loss=0.0843 test_acc=0.9854
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 20 | train_loss=0.0677 train_acc=0.9818 | val_loss=0.7780 val_acc=0.8198 | test_loss=0.0688 test_acc=0.9818
  No validation improvement greater than 0.0020. Patience: 4/5
Fold 4 complete | subject=H04 | test_acc=0.9854 | test_macro_f1=0.9748
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3030 train_acc=0.2244 | val_loss=1.6662 val_acc=0.3009 | test_loss=1.3936 test_acc=0.3844
Epoch 02 | train_loss=1.1660 train_acc=0.5270 | val_loss=1.2429 val_acc=0.4539 | test_loss=0.8497 test_acc=0.5487
Epoch 03 | train_loss=0.8017 train_acc=0.7003 | val_loss=1.1067 val_acc=0.5721 | test_loss=0.7159 test_acc=0.5905
Epoch 04 | train_loss=0.6061 train_acc=0.8053 | val_loss=0.9102 val_acc=0.7208 | test_loss=0.6331 test_acc=0.6992
Epoch 05 | train_loss=0.4766 train_acc=0.8573 | val_loss=0.7814 val_acc=0.7520 | test_loss=0.5575 test_acc=0.7382
Epoch 06 | train_loss=0.3879 train_acc=0.8852 | val_loss=0.8956 val_acc=0.7376 | test_loss=0.7037 test_acc=0.6852
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.3253 train_acc=0.9058 | val_loss=0.7399 val_acc=0.7584 | test_loss=0.5311 test_acc=0.7772
Epoch 08 | train_loss=0.2734 train_acc=0.9167 | val_loss=0.7395 val_acc=0.7779 | test_loss=0.5533 test_acc=0.7632
Epoch 09 | train_loss=0.2404 train_acc=0.9358 | val_loss=0.6550 val_acc=0.7929 | test_loss=0.4445 test_acc=0.8162
Epoch 10 | train_loss=0.2099 train_acc=0.9378 | val_loss=0.6827 val_acc=0.7951 | test_loss=0.5108 test_acc=0.7716
Epoch 11 | train_loss=0.1827 train_acc=0.9483 | val_loss=0.7305 val_acc=0.7920 | test_loss=0.4697 test_acc=0.8050
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.1628 train_acc=0.9529 | val_loss=0.6704 val_acc=0.7963 | test_loss=0.4806 test_acc=0.7994
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.1440 train_acc=0.9592 | val_loss=0.6827 val_acc=0.7847 | test_loss=0.4885 test_acc=0.7883
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 14 | train_loss=0.1284 train_acc=0.9637 | val_loss=0.8467 val_acc=0.7761 | test_loss=0.5580 test_acc=0.7437
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 15 | train_loss=0.1134 train_acc=0.9715 | val_loss=0.7193 val_acc=0.8036 | test_loss=0.3653 test_acc=0.8357
Epoch 16 | train_loss=0.1036 train_acc=0.9720 | val_loss=0.6771 val_acc=0.7972 | test_loss=0.4145 test_acc=0.7827
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.0902 train_acc=0.9776 | val_loss=0.7149 val_acc=0.8131 | test_loss=0.4043 test_acc=0.8189
Epoch 18 | train_loss=0.0790 train_acc=0.9807 | val_loss=0.6708 val_acc=0.8015 | test_loss=0.3319 test_acc=0.8273
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 19 | train_loss=0.0765 train_acc=0.9805 | val_loss=0.7152 val_acc=0.8106 | test_loss=0.3851 test_acc=0.8384
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 20 | train_loss=0.0666 train_acc=0.9825 | val_loss=0.7740 val_acc=0.8100 | test_loss=0.3979 test_acc=0.8468
  No validation improvement greater than 0.0020. Patience: 3/5
Fold 5 complete | subject=H05 | test_acc=0.8189 | test_macro_f1=0.8556
==========================================================================================
LOSO fold 6/25 | test subject: P02
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('P02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,13,0.824908,0.848101,0.811516
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,15,0.823152,0.917293,0.877598
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,20,0.830177,0.955504,0.943574
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,20,0.841478,0.985401,0.974838
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,20,0.813073,0.818942,0.855565
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,20,0.843922,0.903509,0.898889
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,20,0.838729,0.970976,0.971549
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,16,0.827428,0.910448,0.914643
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,20,0.830177,0.492669,0.489762
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,20,0.711815,0.860227,0.829014
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,20,0.720330,0.599251,0.324558
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,13,0.719798,0.769640,0.788540
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,16,0.715856,0.959135,0.944515
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,15,0.691913,0.820513,0.787633
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,15,0.696799,0.861386,0.808300
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,20,0.692890,0.776021,0.780952
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,20,0.700220,0.987705,0.995483
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,20,0.752057,0.663793,0.665235
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,20,0.742695,0.961694,0.952928
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,13,0.724765,0.838499,0.805545
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,20,0.719484,0.925125,0.875806
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,16,0.735622,0.946721,0.966834
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,20,0.747066,0.738230,0.739782
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,15,0.750000,0.938725,0.952072
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,14,0.749120,0.831776,0.791275

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.8157
Overall window-level macro F1: 0.8063
Mean fold accuracy: 0.8513 ± 0.1248
Mean fold macro F1: 0.8299 ± 0.1548
Saved summary CSV: experiment_results/segment_combination_study__combo-UpperArm__ForeArm__Hand__nseg-3__win-4s__step-0.5s__20260407_170137__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-UpperArm__ForeArm__Hand__nseg-3__win-4s__step-0.5s__20260407_170137__folds.csv

====================================================================================================
Combination run 12/15
Canonical combo: ['UpperArm', 'ForeArm', 'Shoulder']
Selected segment labels: ['LeftUpperArm', 'RightUpperArm', 'LeftForeArm', 'RightForeArm', 'LeftShoulder', 'RightShoulder']
Loading cached dataset from: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftUpperArm_RightUpperArm_LeftForeArm_RightForeArm_LeftShoulder_RightShoulder__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (UpperArm+ForeArm+Shoulder) dataset loaded.
Dataset shape: (14521, 240, 18)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 18)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4212 train_acc=0.3389 | val_loss=1.8387 val_acc=0.3703 | test_loss=1.8436 test_acc=0.3110
Epoch 02 | train_loss=1.1988 train_acc=0.5729 | val_loss=1.2120 val_acc=0.4854 | test_loss=1.1974 test_acc=0.4213
Epoch 03 | train_loss=0.8076 train_acc=0.7242 | val_loss=1.0072 val_acc=0.6461 | test_loss=0.9878 test_acc=0.5335
Epoch 04 | train_loss=0.6208 train_acc=0.7973 | val_loss=0.9417 val_acc=0.6856 | test_loss=1.0295 test_acc=0.5696
Epoch 05 | train_loss=0.4970 train_acc=0.8451 | val_loss=0.9968 val_acc=0.6639 | test_loss=1.0168 test_acc=0.5660
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 06 | train_loss=0.4095 train_acc=0.8698 | val_loss=0.8976 val_acc=0.7198 | test_loss=1.0982 test_acc=0.5389
Epoch 07 | train_loss=0.3427 train_acc=0.8918 | val_loss=0.8078 val_acc=0.7412 | test_loss=0.7778 test_acc=0.6582
Epoch 08 | train_loss=0.2957 train_acc=0.9086 | val_loss=0.8185 val_acc=0.7245 | test_loss=0.8046 test_acc=0.6438
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2561 train_acc=0.9204 | val_loss=0.9429 val_acc=0.7087 | test_loss=1.0900 test_acc=0.5678
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 10 | train_loss=0.2192 train_acc=0.9340 | val_loss=0.8536 val_acc=0.7128 | test_loss=0.9987 test_acc=0.5986
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 11 | train_loss=0.1907 train_acc=0.9432 | val_loss=0.8404 val_acc=0.7449 | test_loss=0.9183 test_acc=0.6293
Epoch 12 | train_loss=0.1688 train_acc=0.9513 | val_loss=0.9047 val_acc=0.7282 | test_loss=0.9599 test_acc=0.6528
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.1479 train_acc=0.9563 | val_loss=0.9202 val_acc=0.7466 | test_loss=1.0589 test_acc=0.6130
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.1355 train_acc=0.9612 | val_loss=0.7851 val_acc=0.7573 | test_loss=0.8672 test_acc=0.7034
Epoch 15 | train_loss=0.1170 train_acc=0.9690 | val_loss=0.7865 val_acc=0.7847 | test_loss=0.8158 test_acc=0.6872
Epoch 16 | train_loss=0.1084 train_acc=0.9684 | val_loss=0.7907 val_acc=0.7871 | test_loss=0.7403 test_acc=0.7468
Epoch 17 | train_loss=0.0917 train_acc=0.9771 | val_loss=0.9421 val_acc=0.7670 | test_loss=1.0422 test_acc=0.6528
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 18 | train_loss=0.0854 train_acc=0.9775 | val_loss=0.9761 val_acc=0.7479 | test_loss=1.0316 test_acc=0.6438
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 19 | train_loss=0.0779 train_acc=0.9811 | val_loss=0.8772 val_acc=0.7636 | test_loss=0.8951 test_acc=0.6618
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 20 | train_loss=0.0729 train_acc=0.9805 | val_loss=0.8829 val_acc=0.7727 | test_loss=0.9965 test_acc=0.6510
  No validation improvement greater than 0.0020. Patience: 4/5
Fold 1 complete | subject=H01 | test_acc=0.7468 | test_macro_f1=0.7164
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2477 train_acc=0.2764 | val_loss=1.6898 val_acc=0.3039 | test_loss=1.4081 test_acc=0.5564
Epoch 02 | train_loss=1.2151 train_acc=0.5548 | val_loss=1.2342 val_acc=0.5034 | test_loss=0.7966 test_acc=0.6617
Epoch 03 | train_loss=0.8303 train_acc=0.7179 | val_loss=1.0948 val_acc=0.6045 | test_loss=0.4832 test_acc=0.8459
Epoch 04 | train_loss=0.6323 train_acc=0.7946 | val_loss=0.9775 val_acc=0.6833 | test_loss=0.3820 test_acc=0.8722
Epoch 05 | train_loss=0.5014 train_acc=0.8437 | val_loss=0.9306 val_acc=0.6988 | test_loss=0.4199 test_acc=0.8308
Epoch 06 | train_loss=0.4140 train_acc=0.8725 | val_loss=0.8857 val_acc=0.7144 | test_loss=0.3906 test_acc=0.8534
Epoch 07 | train_loss=0.3394 train_acc=0.8992 | val_loss=0.9112 val_acc=0.7147 | test_loss=0.3049 test_acc=0.8759
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.2896 train_acc=0.9152 | val_loss=1.0343 val_acc=0.6833 | test_loss=0.1731 test_acc=0.9586
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.2516 train_acc=0.9256 | val_loss=0.9788 val_acc=0.6897 | test_loss=0.1624 test_acc=0.9511
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 10 | train_loss=0.2168 train_acc=0.9344 | val_loss=1.0511 val_acc=0.7065 | test_loss=0.2172 test_acc=0.9286
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 11 | train_loss=0.1905 train_acc=0.9430 | val_loss=0.9163 val_acc=0.7520 | test_loss=0.2719 test_acc=0.9135
Epoch 12 | train_loss=0.1674 train_acc=0.9506 | val_loss=1.0443 val_acc=0.7364 | test_loss=0.3294 test_acc=0.8797
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.1496 train_acc=0.9583 | val_loss=0.8725 val_acc=0.7425 | test_loss=0.2077 test_acc=0.9286
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.1304 train_acc=0.9629 | val_loss=0.7990 val_acc=0.7529 | test_loss=0.2952 test_acc=0.9023
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 15 | train_loss=0.1176 train_acc=0.9704 | val_loss=0.8072 val_acc=0.7743 | test_loss=0.3136 test_acc=0.8947
Epoch 16 | train_loss=0.1034 train_acc=0.9731 | val_loss=0.9108 val_acc=0.7560 | test_loss=0.2638 test_acc=0.9135
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.0923 train_acc=0.9763 | val_loss=1.0666 val_acc=0.7364 | test_loss=0.2786 test_acc=0.9023
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.0872 train_acc=0.9759 | val_loss=1.0451 val_acc=0.7251 | test_loss=0.1299 test_acc=0.9511
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 19 | train_loss=0.0756 train_acc=0.9821 | val_loss=1.1567 val_acc=0.7425 | test_loss=0.2939 test_acc=0.9023
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 20 | train_loss=0.0709 train_acc=0.9824 | val_loss=0.8902 val_acc=0.7547 | test_loss=0.1928 test_acc=0.9398
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 20.
Fold 2 complete | subject=H02 | test_acc=0.8947 | test_macro_f1=0.9133
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2095 train_acc=0.2455 | val_loss=1.7309 val_acc=0.2798 | test_loss=1.1632 test_acc=0.4496
Epoch 02 | train_loss=1.1682 train_acc=0.5571 | val_loss=1.2379 val_acc=0.4710 | test_loss=0.6912 test_acc=0.6721
Epoch 03 | train_loss=0.8094 train_acc=0.7023 | val_loss=1.0329 val_acc=0.6054 | test_loss=0.4418 test_acc=0.8290
Epoch 04 | train_loss=0.6144 train_acc=0.7896 | val_loss=1.0719 val_acc=0.6252 | test_loss=0.3723 test_acc=0.8689
Epoch 05 | train_loss=0.4931 train_acc=0.8436 | val_loss=0.9959 val_acc=0.6796 | test_loss=0.3704 test_acc=0.8876
Epoch 06 | train_loss=0.4093 train_acc=0.8733 | val_loss=0.8772 val_acc=0.6802 | test_loss=0.2549 test_acc=0.9251
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.3403 train_acc=0.8957 | val_loss=0.8818 val_acc=0.6988 | test_loss=0.2418 test_acc=0.9274
Epoch 08 | train_loss=0.2915 train_acc=0.9103 | val_loss=0.8559 val_acc=0.7120 | test_loss=0.2239 test_acc=0.9321
Epoch 09 | train_loss=0.2557 train_acc=0.9183 | val_loss=1.0433 val_acc=0.6875 | test_loss=0.2419 test_acc=0.9133
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2216 train_acc=0.9327 | val_loss=0.8569 val_acc=0.7428 | test_loss=0.2282 test_acc=0.9204
Epoch 11 | train_loss=0.1933 train_acc=0.9420 | val_loss=0.8920 val_acc=0.7502 | test_loss=0.2170 test_acc=0.9344
Epoch 12 | train_loss=0.1671 train_acc=0.9514 | val_loss=0.8931 val_acc=0.7016 | test_loss=0.2604 test_acc=0.9087
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.1485 train_acc=0.9585 | val_loss=0.8795 val_acc=0.7340 | test_loss=0.2436 test_acc=0.9157
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.1312 train_acc=0.9628 | val_loss=0.8385 val_acc=0.7413 | test_loss=0.2040 test_acc=0.9321
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 15 | train_loss=0.1194 train_acc=0.9681 | val_loss=0.7972 val_acc=0.7740 | test_loss=0.1014 test_acc=0.9649
Epoch 16 | train_loss=0.1055 train_acc=0.9732 | val_loss=0.9086 val_acc=0.7135 | test_loss=0.2461 test_acc=0.9180
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.0920 train_acc=0.9773 | val_loss=0.8516 val_acc=0.7364 | test_loss=0.2211 test_acc=0.9227
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.0854 train_acc=0.9765 | val_loss=0.8015 val_acc=0.7676 | test_loss=0.1323 test_acc=0.9485
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 19 | train_loss=0.0764 train_acc=0.9809 | val_loss=1.0603 val_acc=0.7126 | test_loss=0.1833 test_acc=0.9180
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 20 | train_loss=0.0708 train_acc=0.9804 | val_loss=0.8766 val_acc=0.7517 | test_loss=0.1215 test_acc=0.9368
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 20.
Fold 3 complete | subject=H03 | test_acc=0.9649 | test_macro_f1=0.9629
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4194 train_acc=0.1932 | val_loss=1.8413 val_acc=0.2963 | test_loss=1.6297 test_acc=0.3394
Epoch 02 | train_loss=1.1732 train_acc=0.5322 | val_loss=1.1915 val_acc=0.5241 | test_loss=0.8650 test_acc=0.6314
Epoch 03 | train_loss=0.7831 train_acc=0.6924 | val_loss=1.0631 val_acc=0.5901 | test_loss=0.6248 test_acc=0.7591
Epoch 04 | train_loss=0.6032 train_acc=0.7782 | val_loss=0.9484 val_acc=0.6610 | test_loss=0.4850 test_acc=0.8248
Epoch 05 | train_loss=0.4840 train_acc=0.8396 | val_loss=0.9636 val_acc=0.6723 | test_loss=0.4116 test_acc=0.8796
Epoch 06 | train_loss=0.4000 train_acc=0.8758 | val_loss=0.9891 val_acc=0.6894 | test_loss=0.3846 test_acc=0.9051
Epoch 07 | train_loss=0.3350 train_acc=0.8969 | val_loss=0.8917 val_acc=0.7230 | test_loss=0.3310 test_acc=0.9489
Epoch 08 | train_loss=0.2878 train_acc=0.9102 | val_loss=1.0126 val_acc=0.7150 | test_loss=0.3562 test_acc=0.9416
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2494 train_acc=0.9245 | val_loss=1.0791 val_acc=0.7153 | test_loss=0.3842 test_acc=0.9197
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 10 | train_loss=0.2203 train_acc=0.9345 | val_loss=0.9869 val_acc=0.7318 | test_loss=0.2865 test_acc=0.9453
Epoch 11 | train_loss=0.1922 train_acc=0.9404 | val_loss=1.1692 val_acc=0.6924 | test_loss=0.3575 test_acc=0.9307
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.1697 train_acc=0.9479 | val_loss=1.1004 val_acc=0.7040 | test_loss=0.3124 test_acc=0.9343
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.1523 train_acc=0.9555 | val_loss=1.0068 val_acc=0.7425 | test_loss=0.2926 test_acc=0.9197
Epoch 14 | train_loss=0.1362 train_acc=0.9605 | val_loss=1.1863 val_acc=0.6738 | test_loss=0.2678 test_acc=0.9380
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.1203 train_acc=0.9656 | val_loss=1.1693 val_acc=0.7193 | test_loss=0.3031 test_acc=0.9453
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 16 | train_loss=0.1109 train_acc=0.9678 | val_loss=1.0799 val_acc=0.7211 | test_loss=0.2616 test_acc=0.9635
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 17 | train_loss=0.0989 train_acc=0.9745 | val_loss=0.9990 val_acc=0.7263 | test_loss=0.2134 test_acc=0.9708
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 18 | train_loss=0.0894 train_acc=0.9764 | val_loss=1.0333 val_acc=0.7404 | test_loss=0.2853 test_acc=0.9489
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 18.
Fold 4 complete | subject=H04 | test_acc=0.9197 | test_macro_f1=0.8647
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3510 train_acc=0.1848 | val_loss=1.7423 val_acc=0.2740 | test_loss=1.3569 test_acc=0.3370
Epoch 02 | train_loss=1.1855 train_acc=0.5278 | val_loss=1.2538 val_acc=0.4194 | test_loss=0.9553 test_acc=0.5014
Epoch 03 | train_loss=0.8134 train_acc=0.7005 | val_loss=1.0811 val_acc=0.5648 | test_loss=0.7129 test_acc=0.6379
Epoch 04 | train_loss=0.6264 train_acc=0.7850 | val_loss=0.9903 val_acc=0.6182 | test_loss=0.7246 test_acc=0.6462
Epoch 05 | train_loss=0.5055 train_acc=0.8384 | val_loss=0.9087 val_acc=0.6591 | test_loss=0.7666 test_acc=0.6657
Epoch 06 | train_loss=0.4187 train_acc=0.8736 | val_loss=0.9404 val_acc=0.7059 | test_loss=0.5500 test_acc=0.7911
Epoch 07 | train_loss=0.3540 train_acc=0.8952 | val_loss=1.0184 val_acc=0.6857 | test_loss=0.6624 test_acc=0.7409
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.3069 train_acc=0.9075 | val_loss=0.9647 val_acc=0.7306 | test_loss=0.5168 test_acc=0.8022
Epoch 09 | train_loss=0.2630 train_acc=0.9189 | val_loss=1.0283 val_acc=0.7187 | test_loss=0.4830 test_acc=0.8078
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2277 train_acc=0.9329 | val_loss=1.0031 val_acc=0.7022 | test_loss=0.5730 test_acc=0.7660
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.2019 train_acc=0.9397 | val_loss=0.9427 val_acc=0.7187 | test_loss=0.5219 test_acc=0.7577
  No validation improvement greater than 0.0020. Patience: 3/5

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,20,0.787077,0.746835,0.716429
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,20,0.774282,0.894737,0.913324
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,20,0.773977,0.964871,0.962897
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,18,0.742517,0.919708,0.864685
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,18,0.759927,0.821727,0.836278
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,16,0.739462,0.858187,0.843294
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,16,0.746793,0.889182,0.880567
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,16,0.744655,0.929104,0.928619
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,13,0.741906,0.405425,0.421651
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,17,0.661522,0.725000,0.689649
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,16,0.675625,0.430712,0.242915
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,17,0.691325,0.760320,0.733030
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,20,0.690936,0.963942,0.965350
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,18,0.665527,0.775978,0.767240
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,15,0.661129,0.805281,0.719238
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,13,0.680674,0.740448,0.754449
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,15,0.677010,0.983607,0.986118
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,15,0.700142,0.637931,0.572795
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,16,0.701277,0.905242,0.885851
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,20,0.710681,0.763458,0.730414
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,19,0.715376,0.896839,0.860645
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,20,0.696890,0.901639,0.904971
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,20,0.695423,0.755179,0.771474
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,20,0.696890,0.960784,0.973448
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,20,0.735622,0.717757,0.642599

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.7690
Overall window-level macro F1: 0.7558
Mean fold accuracy: 0.8062 ± 0.1497
Mean fold macro F1: 0.7827 ± 0.1762
Saved summary CSV: experiment_results/segment_combination_study__combo-UpperArm__ForeArm__Shoulder__nseg-3__win-4s__step-0.5s__20260407_171319__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-UpperArm__ForeArm__Shoulder__nseg-3__win-4s__step-0.5s__20260407_171319__folds.csv

====================================================================================================
Combination run 13/15
Canonical combo: ['UpperArm', 'Hand', 'Shoulder']
Selected segment labels: ['LeftUpperArm', 'RightUpperArm', 'LeftHand', 'RightHand', 'LeftShoulder', 'RightShoulder']
Loading cached dataset from: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftUpperArm_RightUpperArm_LeftHand_RightHand_LeftShoulder_RightShoulder__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (UpperArm+Hand+Shoulder) dataset loaded.
Dataset shape: (14521, 240, 18)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 18)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3371 train_acc=0.2460 | val_loss=1.8073 val_acc=0.2618 | test_loss=1.5652 test_acc=0.3363
Epoch 02 | train_loss=1.2029 train_acc=0.5350 | val_loss=1.1681 val_acc=0.5755 | test_loss=0.9231 test_acc=0.5280
Epoch 03 | train_loss=0.8212 train_acc=0.7330 | val_loss=0.9520 val_acc=0.6860 | test_loss=0.6509 test_acc=0.6727
Epoch 04 | train_loss=0.6028 train_acc=0.8202 | val_loss=0.8741 val_acc=0.7409 | test_loss=0.5015 test_acc=0.7414
Epoch 05 | train_loss=0.4621 train_acc=0.8615 | val_loss=0.9342 val_acc=0.7359 | test_loss=0.5419 test_acc=0.7450
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 06 | train_loss=0.3770 train_acc=0.8884 | val_loss=1.0245 val_acc=0.7218 | test_loss=0.6234 test_acc=0.7233
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 07 | train_loss=0.3113 train_acc=0.9046 | val_loss=0.7736 val_acc=0.7854 | test_loss=0.3913 test_acc=0.7902
Epoch 08 | train_loss=0.2693 train_acc=0.9194 | val_loss=0.8396 val_acc=0.7613 | test_loss=0.4668 test_acc=0.7432
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2330 train_acc=0.9304 | val_loss=0.7799 val_acc=0.8011 | test_loss=0.4302 test_acc=0.7740
Epoch 10 | train_loss=0.1995 train_acc=0.9404 | val_loss=0.9692 val_acc=0.7687 | test_loss=0.6387 test_acc=0.7559
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.1741 train_acc=0.9468 | val_loss=0.8573 val_acc=0.7877 | test_loss=0.4858 test_acc=0.7523
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.1526 train_acc=0.9545 | val_loss=0.8307 val_acc=0.7941 | test_loss=0.4932 test_acc=0.7396
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 13 | train_loss=0.1343 train_acc=0.9616 | val_loss=0.9226 val_acc=0.7918 | test_loss=0.4743 test_acc=0.7848
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 14 | train_loss=0.1189 train_acc=0.9679 | val_loss=0.8302 val_acc=0.8048 | test_loss=0.3544 test_acc=0.8047
Epoch 15 | train_loss=0.1063 train_acc=0.9711 | val_loss=0.8143 val_acc=0.8038 | test_loss=0.3814 test_acc=0.8065
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.0951 train_acc=0.9740 | val_loss=0.8697 val_acc=0.8055 | test_loss=0.4049 test_acc=0.8246
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 17 | train_loss=0.0834 train_acc=0.9774 | val_loss=0.9279 val_acc=0.7944 | test_loss=0.5384 test_acc=0.8101
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 18 | train_loss=0.0745 train_acc=0.9812 | val_loss=0.8301 val_acc=0.8088 | test_loss=0.3715 test_acc=0.8517
Epoch 19 | train_loss=0.0697 train_acc=0.9842 | val_loss=0.9767 val_acc=0.7985 | test_loss=0.5624 test_acc=0.7740
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 20 | train_loss=0.0630 train_acc=0.9863 | val_loss=0.9010 val_acc=0.8018 | test_loss=0.4911 test_acc=0.7740
  No validation improvement greater than 0.0020. Patience: 2/5
Fold 1 complete | subject=H01 | test_acc=0.8517 | test_macro_f1=0.8235
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.4944 train_acc=0.3126 | val_loss=1.9380 val_acc=0.2981 | test_loss=1.4095 test_acc=0.4737
Epoch 02 | train_loss=1.2648 train_acc=0.5395 | val_loss=1.2525 val_acc=0.4511 | test_loss=0.6488 test_acc=0.7030
Epoch 03 | train_loss=0.8456 train_acc=0.7108 | val_loss=1.1422 val_acc=0.6109 | test_loss=0.4885 test_acc=0.7782
Epoch 04 | train_loss=0.6350 train_acc=0.7926 | val_loss=1.0480 val_acc=0.6830 | test_loss=0.4017 test_acc=0.8045
Epoch 05 | train_loss=0.5061 train_acc=0.8371 | val_loss=0.8844 val_acc=0.7337 | test_loss=0.3511 test_acc=0.8158
Epoch 06 | train_loss=0.4136 train_acc=0.8653 | val_loss=0.9750 val_acc=0.7056 | test_loss=0.3282 test_acc=0.8233
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.3425 train_acc=0.8889 | val_loss=0.8384 val_acc=0.7337 | test_loss=0.2761 test_acc=0.9098
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 08 | train_loss=0.2864 train_acc=0.9091 | val_loss=0.8257 val_acc=0.7392 | test_loss=0.3527 test_acc=0.8158
Epoch 09 | train_loss=0.2444 train_acc=0.9230 | val_loss=0.8286 val_acc=0.7508 | test_loss=0.2645 test_acc=0.8910
Epoch 10 | train_loss=0.2120 train_acc=0.9334 | val_loss=0.7525 val_acc=0.7831 | test_loss=0.2892 test_acc=0.9135
Epoch 11 | train_loss=0.1880 train_acc=0.9417 | val_loss=0.7286 val_acc=0.7792 | test_loss=0.2514 test_acc=0.9361
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.1632 train_acc=0.9503 | val_loss=0.8498 val_acc=0.7416 | test_loss=0.2011 test_acc=0.9436
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.1468 train_acc=0.9547 | val_loss=0.8692 val_acc=0.7621 | test_loss=0.2200 test_acc=0.9398
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 14 | train_loss=0.1272 train_acc=0.9608 | val_loss=0.7236 val_acc=0.8070 | test_loss=0.2648 test_acc=0.9361
Epoch 15 | train_loss=0.1108 train_acc=0.9673 | val_loss=0.7419 val_acc=0.7859 | test_loss=0.3064 test_acc=0.9361
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.1000 train_acc=0.9687 | val_loss=0.7838 val_acc=0.7844 | test_loss=0.2351 test_acc=0.9436
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 17 | train_loss=0.0909 train_acc=0.9735 | val_loss=0.9749 val_acc=0.7401 | test_loss=0.2475 test_acc=0.9361
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 18 | train_loss=0.0829 train_acc=0.9773 | val_loss=0.9166 val_acc=0.7532 | test_loss=0.2501 test_acc=0.9398
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 19 | train_loss=0.0718 train_acc=0.9800 | val_loss=0.7328 val_acc=0.7938 | test_loss=0.2864 test_acc=0.9361
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 19.
Fold 2 complete | subject=H02 | test_acc=0.9361 | test_macro_f1=0.9428
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3966 train_acc=0.3596 | val_loss=1.8737 val_acc=0.2789 | test_loss=1.3802 test_acc=0.4052
Epoch 02 | train_loss=1.2453 train_acc=0.5325 | val_loss=1.2012 val_acc=0.4768 | test_loss=0.6268 test_acc=0.6838
Epoch 03 | train_loss=0.8279 train_acc=0.6925 | val_loss=0.9797 val_acc=0.6701 | test_loss=0.3494 test_acc=0.8454
Epoch 04 | train_loss=0.6126 train_acc=0.8011 | val_loss=0.9272 val_acc=0.7175 | test_loss=0.2504 test_acc=0.9063
Epoch 05 | train_loss=0.4817 train_acc=0.8497 | val_loss=0.9186 val_acc=0.7013 | test_loss=0.2221 test_acc=0.9180
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 06 | train_loss=0.3924 train_acc=0.8792 | val_loss=0.9834 val_acc=0.6891 | test_loss=0.2195 test_acc=0.8923
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 07 | train_loss=0.3280 train_acc=0.9018 | val_loss=0.8158 val_acc=0.7398 | test_loss=0.1818 test_acc=0.9321
Epoch 08 | train_loss=0.2825 train_acc=0.9131 | val_loss=0.9397 val_acc=0.7095 | test_loss=0.1840 test_acc=0.9344
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2428 train_acc=0.9260 | val_loss=0.9508 val_acc=0.7153 | test_loss=0.1646 test_acc=0.9133
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 10 | train_loss=0.2129 train_acc=0.9383 | val_loss=0.8151 val_acc=0.7688 | test_loss=0.1421 test_acc=0.9415
Epoch 11 | train_loss=0.1868 train_acc=0.9440 | val_loss=0.9176 val_acc=0.7327 | test_loss=0.1075 test_acc=0.9578
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.1648 train_acc=0.9524 | val_loss=0.9925 val_acc=0.7346 | test_loss=0.1318 test_acc=0.9391
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 13 | train_loss=0.1460 train_acc=0.9609 | val_loss=0.9109 val_acc=0.7392 | test_loss=0.1409 test_acc=0.9297
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 14 | train_loss=0.1286 train_acc=0.9641 | val_loss=0.8030 val_acc=0.7795 | test_loss=0.0889 test_acc=0.9508
Epoch 15 | train_loss=0.1154 train_acc=0.9682 | val_loss=1.0548 val_acc=0.7236 | test_loss=0.1666 test_acc=0.9227
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.1030 train_acc=0.9721 | val_loss=0.8481 val_acc=0.7663 | test_loss=0.1482 test_acc=0.9297
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 17 | train_loss=0.0908 train_acc=0.9778 | val_loss=0.8537 val_acc=0.7847 | test_loss=0.1374 test_acc=0.9251
Epoch 18 | train_loss=0.0820 train_acc=0.9790 | val_loss=0.8514 val_acc=0.7865 | test_loss=0.0809 test_acc=0.9485
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 19 | train_loss=0.0759 train_acc=0.9809 | val_loss=0.9125 val_acc=0.7569 | test_loss=0.1143 test_acc=0.9415
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 20 | train_loss=0.0680 train_acc=0.9848 | val_loss=0.8076 val_acc=0.7993 | test_loss=0.0997 test_acc=0.9532
Fold 3 complete | subject=H03 | test_acc=0.9532 | test_macro_f1=0.9537
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3621 train_acc=0.2472 | val_loss=1.8997 val_acc=0.2648 | test_loss=1.6456 test_acc=0.3467
Epoch 02 | train_loss=1.2399 train_acc=0.5282 | val_loss=1.2266 val_acc=0.4853 | test_loss=0.7926 test_acc=0.6715
Epoch 03 | train_loss=0.8288 train_acc=0.7256 | val_loss=0.9856 val_acc=0.6478 | test_loss=0.4185 test_acc=0.8796
Epoch 04 | train_loss=0.6039 train_acc=0.8169 | val_loss=0.9314 val_acc=0.6912 | test_loss=0.2571 test_acc=0.9197
Epoch 05 | train_loss=0.4716 train_acc=0.8599 | val_loss=0.8115 val_acc=0.7425 | test_loss=0.2012 test_acc=0.9234
Epoch 06 | train_loss=0.3813 train_acc=0.8887 | val_loss=0.8246 val_acc=0.7309 | test_loss=0.1599 test_acc=0.9307
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.3205 train_acc=0.9056 | val_loss=0.7549 val_acc=0.7605 | test_loss=0.1172 test_acc=0.9562
Epoch 08 | train_loss=0.2668 train_acc=0.9224 | val_loss=0.7123 val_acc=0.7602 | test_loss=0.1054 test_acc=0.9818
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2322 train_acc=0.9327 | val_loss=0.7563 val_acc=0.7819 | test_loss=0.0916 test_acc=0.9854
Epoch 10 | train_loss=0.1995 train_acc=0.9413 | val_loss=0.7834 val_acc=0.7382 | test_loss=0.1123 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.1761 train_acc=0.9508 | val_loss=0.7306 val_acc=0.7957 | test_loss=0.0823 test_acc=0.9818
Epoch 12 | train_loss=0.1519 train_acc=0.9581 | val_loss=0.7950 val_acc=0.7410 | test_loss=0.0768 test_acc=0.9854
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.1331 train_acc=0.9619 | val_loss=0.7836 val_acc=0.7627 | test_loss=0.0568 test_acc=0.9964
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 14 | train_loss=0.1188 train_acc=0.9698 | val_loss=0.9369 val_acc=0.6906 | test_loss=0.1236 test_acc=0.9270
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 15 | train_loss=0.1031 train_acc=0.9728 | val_loss=0.7584 val_acc=0.7972 | test_loss=0.0571 test_acc=0.9891
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 16 | train_loss=0.0934 train_acc=0.9773 | val_loss=0.7533 val_acc=0.7630 | test_loss=0.0608 test_acc=0.9818
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 16.
Fold 4 complete | subject=H04 | test_acc=0.9818 | test_macro_f1=0.9732
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3757 train_acc=0.3217 | val_loss=1.7541 val_acc=0.3503 | test_loss=1.4470 test_acc=0.3120
Epoch 02 | train_loss=1.1922 train_acc=0.5786 | val_loss=1.1166 val_acc=0.5269 | test_loss=0.9022 test_acc=0.5487
Epoch 03 | train_loss=0.7932 train_acc=0.7396 | val_loss=0.9748 val_acc=0.6115 | test_loss=0.7129 test_acc=0.6240
Epoch 04 | train_loss=0.5993 train_acc=0.8078 | val_loss=0.9355 val_acc=0.6735 | test_loss=0.7000 test_acc=0.6407
Epoch 05 | train_loss=0.4748 train_acc=0.8515 | val_loss=0.8192 val_acc=0.7279 | test_loss=0.6192 test_acc=0.6852
Epoch 06 | train_loss=0.3893 train_acc=0.8743 | val_loss=0.7670 val_acc=0.7593 | test_loss=0.6123 test_acc=0.7270
Epoch 07 | train_loss=0.3208 train_acc=0.8988 | val_loss=0.7887 val_acc=0.7248 | test_loss=0.7143 test_acc=0.6880
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.2752 train_acc=0.9149 | val_loss=0.7299 val_acc=0.7569 | test_loss=0.7423 test_acc=0.7047
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.2365 train_acc=0.9273 | val_loss=0.8917 val_acc=0.7181 | test_loss=0.6939 test_acc=0.6741
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 10 | train_loss=0.2079 train_acc=0.9342 | val_loss=0.7888 val_acc=0.7581 | test_loss=0.6219 test_acc=0.7409
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 11 | train_loss=0.1814 train_acc=0.9466 | val_loss=0.7869 val_acc=0.7856 | test_loss=0.5988 test_acc=0.7521
Epoch 12 | train_loss=0.1600 train_acc=0.9512 | val_loss=0.8512 val_acc=0.7621 | test_loss=0.6962 test_acc=0.7382
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.1426 train_acc=0.9595 | val_loss=0.7649 val_acc=0.7779 | test_loss=0.5851 test_acc=0.7939
  No validation improvement greater than 0.0020. Patience: 2/5

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,20,0.808838,0.851718,0.823489
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,19,0.806964,0.936090,0.942777
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,20,0.799328,0.953162,0.953714
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,16,0.795663,0.981752,0.973181
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,20,0.799939,0.807799,0.834367
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,16,0.788638,0.837719,0.848916
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,18,0.817654,0.976253,0.976233
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,11,0.760843,0.908582,0.911432
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,14,0.796885,0.509531,0.525752
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,20,0.718467,0.790909,0.759494
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,20,0.694784,0.468165,0.300257
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,20,0.703832,0.770972,0.729401
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,14,0.698510,0.963942,0.956689
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,12,0.662839,0.812416,0.804128
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,13,0.630833,0.900990,0.793488
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,20,0.690691,0.770751,0.749179
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,15,0.686538,0.979508,0.983831
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,15,0.695887,0.629310,0.660606
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,20,0.723404,0.993952,0.994895
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,16,0.727113,0.822186,0.750382
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,19,0.734448,0.881864,0.847298
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,18,0.748533,0.971311,0.973540
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,19,0.749120,0.774953,0.822578
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,20,0.754401,0.941176,0.958248
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,20,0.756162,0.743925,0.678513

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.8058
Overall window-level macro F1: 0.8003
Mean fold accuracy: 0.8392 ± 0.1409
Mean fold macro F1: 0.8221 ± 0.1626
Saved summary CSV: experiment_results/segment_combination_study__combo-UpperArm__Hand__Shoulder__nseg-3__win-4s__step-0.5s__20260407_172454__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-UpperArm__Hand__Shoulder__nseg-3__win-4s__step-0.5s__20260407_172454__folds.csv

====================================================================================================
Combination run 14/15
Canonical combo: ['ForeArm', 'Hand', 'Shoulder']
Selected segment labels: ['LeftForeArm', 'RightForeArm', 'LeftHand', 'RightHand', 'LeftShoulder', 'RightShoulder']
Loading cached dataset from: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftForeArm_RightForeArm_LeftHand_RightHand_LeftShoulder_RightShoulder__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (ForeArm+Hand+Shoulder) dataset loaded.
Dataset shape: (14521, 240, 18)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 18)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3308 train_acc=0.2030 | val_loss=1.8107 val_acc=0.2685 | test_loss=1.6657 test_acc=0.2821
Epoch 02 | train_loss=1.2159 train_acc=0.5464 | val_loss=1.1980 val_acc=0.4710 | test_loss=1.0418 test_acc=0.3996
Epoch 03 | train_loss=0.7977 train_acc=0.7299 | val_loss=0.9607 val_acc=0.6957 | test_loss=0.8493 test_acc=0.5949
Epoch 04 | train_loss=0.5875 train_acc=0.8183 | val_loss=0.8758 val_acc=0.7238 | test_loss=0.7057 test_acc=0.6040
Epoch 05 | train_loss=0.4541 train_acc=0.8605 | val_loss=0.9029 val_acc=0.7399 | test_loss=0.6467 test_acc=0.6618
Epoch 06 | train_loss=0.3751 train_acc=0.8888 | val_loss=0.8641 val_acc=0.7523 | test_loss=0.6129 test_acc=0.6618
Epoch 07 | train_loss=0.3188 train_acc=0.9037 | val_loss=0.8099 val_acc=0.7747 | test_loss=0.5402 test_acc=0.7450
Epoch 08 | train_loss=0.2719 train_acc=0.9142 | val_loss=0.7467 val_acc=0.7951 | test_loss=0.4126 test_acc=0.8174
Epoch 09 | train_loss=0.2356 train_acc=0.9275 | val_loss=0.7634 val_acc=0.8045 | test_loss=0.4421 test_acc=0.7776
Epoch 10 | train_loss=0.2081 train_acc=0.9359 | val_loss=0.7790 val_acc=0.7841 | test_loss=0.4332 test_acc=0.7884
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.1788 train_acc=0.9414 | val_loss=0.7397 val_acc=0.7971 | test_loss=0.4179 test_acc=0.7902
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.1608 train_acc=0.9498 | val_loss=0.6934 val_acc=0.7981 | test_loss=0.4293 test_acc=0.8065
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 13 | train_loss=0.1419 train_acc=0.9557 | val_loss=0.8331 val_acc=0.7770 | test_loss=0.5042 test_acc=0.7288
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 14 | train_loss=0.1247 train_acc=0.9633 | val_loss=0.8458 val_acc=0.7978 | test_loss=0.4354 test_acc=0.8137
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 14.
Fold 1 complete | subject=H01 | test_acc=0.7776 | test_macro_f1=0.8018
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2079 train_acc=0.2777 | val_loss=1.5681 val_acc=0.3320 | test_loss=1.1008 test_acc=0.5451
Epoch 02 | train_loss=1.1206 train_acc=0.5450 | val_loss=1.1973 val_acc=0.4285 | test_loss=0.6385 test_acc=0.6880
Epoch 03 | train_loss=0.7580 train_acc=0.7147 | val_loss=0.8880 val_acc=0.6460 | test_loss=0.4247 test_acc=0.8684
Epoch 04 | train_loss=0.5631 train_acc=0.8077 | val_loss=0.8562 val_acc=0.6952 | test_loss=0.2853 test_acc=0.9323
Epoch 05 | train_loss=0.4394 train_acc=0.8582 | val_loss=0.7800 val_acc=0.7462 | test_loss=0.2590 test_acc=0.9211
Epoch 06 | train_loss=0.3569 train_acc=0.8855 | val_loss=0.7281 val_acc=0.7587 | test_loss=0.2486 test_acc=0.9135
Epoch 07 | train_loss=0.2974 train_acc=0.9022 | val_loss=0.9208 val_acc=0.7086 | test_loss=0.1829 test_acc=0.9398
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.2547 train_acc=0.9169 | val_loss=0.8077 val_acc=0.7318 | test_loss=0.1079 test_acc=0.9737
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.2218 train_acc=0.9274 | val_loss=0.6902 val_acc=0.7798 | test_loss=0.1280 test_acc=0.9662
Epoch 10 | train_loss=0.1950 train_acc=0.9355 | val_loss=0.6328 val_acc=0.7850 | test_loss=0.1217 test_acc=0.9474
Epoch 11 | train_loss=0.1709 train_acc=0.9447 | val_loss=0.6296 val_acc=0.7908 | test_loss=0.1144 test_acc=0.9511
Epoch 12 | train_loss=0.1522 train_acc=0.9522 | val_loss=0.6453 val_acc=0.8009 | test_loss=0.0905 test_acc=0.9549
Epoch 13 | train_loss=0.1325 train_acc=0.9572 | val_loss=0.7068 val_acc=0.8024 | test_loss=0.0971 test_acc=0.9586
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.1190 train_acc=0.9620 | val_loss=0.7505 val_acc=0.7828 | test_loss=0.0737 test_acc=0.9812
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.1069 train_acc=0.9672 | val_loss=0.6058 val_acc=0.8106 | test_loss=0.1225 test_acc=0.9511
Epoch 16 | train_loss=0.0958 train_acc=0.9679 | val_loss=0.7476 val_acc=0.7981 | test_loss=0.1724 test_acc=0.9286
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 17 | train_loss=0.0849 train_acc=0.9755 | val_loss=0.6735 val_acc=0.8109 | test_loss=0.1018 test_acc=0.9586
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 18 | train_loss=0.0781 train_acc=0.9773 | val_loss=0.8845 val_acc=0.7648 | test_loss=0.0583 test_acc=0.9812
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 19 | train_loss=0.0721 train_acc=0.9787 | val_loss=0.5983 val_acc=0.8219 | test_loss=0.1853 test_acc=0.9211
Epoch 20 | train_loss=0.0634 train_acc=0.9811 | val_loss=0.6946 val_acc=0.8183 | test_loss=0.2097 test_acc=0.9060
  No validation improvement greater than 0.0020. Patience: 1/5
Fold 2 complete | subject=H02 | test_acc=0.9211 | test_macro_f1=0.8808
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.5150 train_acc=0.1692 | val_loss=1.9755 val_acc=0.2746 | test_loss=1.5459 test_acc=0.4309
Epoch 02 | train_loss=1.2611 train_acc=0.4968 | val_loss=1.2561 val_acc=0.4346 | test_loss=0.6847 test_acc=0.6651
Epoch 03 | train_loss=0.8430 train_acc=0.6612 | val_loss=1.0368 val_acc=0.6344 | test_loss=0.4569 test_acc=0.7635
Epoch 04 | train_loss=0.6284 train_acc=0.7928 | val_loss=0.8732 val_acc=0.7358 | test_loss=0.3363 test_acc=0.8735
Epoch 05 | train_loss=0.4875 train_acc=0.8440 | val_loss=0.7860 val_acc=0.7535 | test_loss=0.2409 test_acc=0.9251
Epoch 06 | train_loss=0.3974 train_acc=0.8744 | val_loss=0.7855 val_acc=0.7557 | test_loss=0.1949 test_acc=0.9204
Epoch 07 | train_loss=0.3333 train_acc=0.8977 | val_loss=0.7388 val_acc=0.7703 | test_loss=0.1666 test_acc=0.9508
Epoch 08 | train_loss=0.2878 train_acc=0.9058 | val_loss=0.7954 val_acc=0.7498 | test_loss=0.1879 test_acc=0.9110
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2469 train_acc=0.9224 | val_loss=0.6576 val_acc=0.7993 | test_loss=0.1221 test_acc=0.9555
Epoch 10 | train_loss=0.2150 train_acc=0.9301 | val_loss=0.7716 val_acc=0.7834 | test_loss=0.1247 test_acc=0.9555
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.1900 train_acc=0.9372 | val_loss=0.6618 val_acc=0.7969 | test_loss=0.1153 test_acc=0.9555
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.1707 train_acc=0.9468 | val_loss=0.8011 val_acc=0.7602 | test_loss=0.1078 test_acc=0.9555
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 13 | train_loss=0.1460 train_acc=0.9539 | val_loss=0.7242 val_acc=0.7883 | test_loss=0.1158 test_acc=0.9532
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 14 | train_loss=0.1356 train_acc=0.9567 | val_loss=0.6477 val_acc=0.8064 | test_loss=0.0787 test_acc=0.9602
Epoch 15 | train_loss=0.1187 train_acc=0.9633 | val_loss=0.7060 val_acc=0.8021 | test_loss=0.1008 test_acc=0.9532
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.1071 train_acc=0.9660 | val_loss=0.6614 val_acc=0.8057 | test_loss=0.0787 test_acc=0.9602
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 17 | train_loss=0.0990 train_acc=0.9699 | val_loss=0.5738 val_acc=0.8204 | test_loss=0.0745 test_acc=0.9555
Epoch 18 | train_loss=0.0863 train_acc=0.9742 | val_loss=0.8125 val_acc=0.7789 | test_loss=0.1189 test_acc=0.9508
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 19 | train_loss=0.0791 train_acc=0.9766 | val_loss=0.7133 val_acc=0.8115 | test_loss=0.0783 test_acc=0.9625
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 20 | train_loss=0.0705 train_acc=0.9824 | val_loss=0.8020 val_acc=0.7941 | test_loss=0.1359 test_acc=0.9485
  No validation improvement greater than 0.0020. Patience: 3/5
Fold 3 complete | subject=H03 | test_acc=0.9555 | test_macro_f1=0.9603
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3328 train_acc=0.2155 | val_loss=1.7654 val_acc=0.2508 | test_loss=1.5416 test_acc=0.3321
Epoch 02 | train_loss=1.1745 train_acc=0.5247 | val_loss=1.3468 val_acc=0.4059 | test_loss=0.9408 test_acc=0.6496
Epoch 03 | train_loss=0.8194 train_acc=0.7086 | val_loss=1.0904 val_acc=0.5984 | test_loss=0.5194 test_acc=0.9015
Epoch 04 | train_loss=0.6127 train_acc=0.8066 | val_loss=1.1645 val_acc=0.6197 | test_loss=0.3845 test_acc=0.8942
Epoch 05 | train_loss=0.4732 train_acc=0.8512 | val_loss=0.9481 val_acc=0.7196 | test_loss=0.2391 test_acc=0.9672
Epoch 06 | train_loss=0.3828 train_acc=0.8839 | val_loss=0.9487 val_acc=0.7013 | test_loss=0.2460 test_acc=0.9453
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.3221 train_acc=0.9053 | val_loss=0.7650 val_acc=0.7425 | test_loss=0.2045 test_acc=0.9380
Epoch 08 | train_loss=0.2678 train_acc=0.9231 | val_loss=0.8809 val_acc=0.7471 | test_loss=0.1556 test_acc=0.9672
Epoch 09 | train_loss=0.2327 train_acc=0.9294 | val_loss=0.8931 val_acc=0.7364 | test_loss=0.1550 test_acc=0.9599
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2006 train_acc=0.9410 | val_loss=0.9007 val_acc=0.7321 | test_loss=0.1677 test_acc=0.9562
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.1754 train_acc=0.9491 | val_loss=0.8582 val_acc=0.7541 | test_loss=0.1427 test_acc=0.9635
Epoch 12 | train_loss=0.1535 train_acc=0.9555 | val_loss=0.9305 val_acc=0.7187 | test_loss=0.1841 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.1383 train_acc=0.9605 | val_loss=0.7744 val_acc=0.7767 | test_loss=0.1170 test_acc=0.9672
Epoch 14 | train_loss=0.1224 train_acc=0.9639 | val_loss=0.8185 val_acc=0.7700 | test_loss=0.1331 test_acc=0.9562
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.1100 train_acc=0.9707 | val_loss=0.8698 val_acc=0.7453 | test_loss=0.1586 test_acc=0.9562
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 16 | train_loss=0.1001 train_acc=0.9717 | val_loss=0.9236 val_acc=0.7486 | test_loss=0.1925 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 17 | train_loss=0.0885 train_acc=0.9764 | val_loss=1.0192 val_acc=0.7349 | test_loss=0.1440 test_acc=0.9708
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 18 | train_loss=0.0780 train_acc=0.9809 | val_loss=1.0036 val_acc=0.7395 | test_loss=0.1277 test_acc=0.9781
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 18.
Fold 4 complete | subject=H04 | test_acc=0.9672 | test_macro_f1=0.9638
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2523 train_acc=0.2711 | val_loss=1.7313 val_acc=0.2563 | test_loss=1.4660 test_acc=0.2925
Epoch 02 | train_loss=1.1880 train_acc=0.5166 | val_loss=1.3244 val_acc=0.4117 | test_loss=1.1574 test_acc=0.4123
Epoch 03 | train_loss=0.8351 train_acc=0.6976 | val_loss=1.0139 val_acc=0.6338 | test_loss=0.8396 test_acc=0.6435
Epoch 04 | train_loss=0.6324 train_acc=0.7951 | val_loss=0.8772 val_acc=0.7071 | test_loss=0.7516 test_acc=0.6518
Epoch 05 | train_loss=0.4943 train_acc=0.8418 | val_loss=0.8713 val_acc=0.6927 | test_loss=0.6967 test_acc=0.6713
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 06 | train_loss=0.3982 train_acc=0.8746 | val_loss=0.7197 val_acc=0.7563 | test_loss=0.5306 test_acc=0.7883
Epoch 07 | train_loss=0.3292 train_acc=0.8947 | val_loss=0.7848 val_acc=0.7502 | test_loss=0.5392 test_acc=0.8106
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.2783 train_acc=0.9137 | val_loss=0.7487 val_acc=0.7611 | test_loss=0.4478 test_acc=0.8357
Epoch 09 | train_loss=0.2424 train_acc=0.9231 | val_loss=0.8455 val_acc=0.7443 | test_loss=0.5618 test_acc=0.8273
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.2056 train_acc=0.9344 | val_loss=0.7992 val_acc=0.7456 | test_loss=0.5414 test_acc=0.7716
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.1789 train_acc=0.9451 | val_loss=0.7262 val_acc=0.7825 | test_loss=0.3960 test_acc=0.8830
Epoch 12 | train_loss=0.1605 train_acc=0.9480 | val_loss=0.9224 val_acc=0.7389 | test_loss=0.6447 test_acc=0.7688
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 13 | train_loss=0.1419 train_acc=0.9546 | val_loss=0.7161 val_acc=0.7981 | test_loss=0.4714 test_acc=0.8162
Epoch 14 | train_loss=0.1264 train_acc=0.9602 | val_loss=0.7296 val_acc=0.8009 | test_loss=0.4288 test_acc=0.8942
Epoch 15 | train_loss=0.1135 train_acc=0.9657 | val_loss=0.8766 val_acc=0.7685 | test_loss=0.4649 test_acc=0.8691
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.1015 train_acc=0.9693 | val_loss=0.7912 val_acc=0.7880 | test_loss=0.4916 test_acc=0.8719
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 17 | train_loss=0.0899 train_acc=0.9735 | val_loss=0.7172 val_acc=0.8155 | test_loss=0.4431 test_acc=0.8663
Epoch 18 | train_loss=0.0841 train_acc=0.9751 | val_loss=0.8121 val_acc=0.7908 | test_loss=0.4737 test_acc=0.8719
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 19 | train_loss=0.0726 train_acc=0.9804 | val_loss=0.7790 val_acc=0.8183 | test_loss=0.5042 test_acc=0.8607
Epoch 20 | train_loss=0.0634 train_acc=0.9819 | val_loss=0.8182 val_acc=0.7859 | test_loss=0.5965 test_acc=0.8329
  No validation improvement greater than 0.0020. Patience: 1/5

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,14,0.804486,0.777577,0.801845
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,20,0.821930,0.921053,0.880764
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,20,0.820403,0.955504,0.960329
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,18,0.776726,0.967153,0.963763
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,20,0.818265,0.860724,0.859081
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,20,0.776726,0.845029,0.859381
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,20,0.799023,0.944591,0.934835
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,18,0.811851,0.955224,0.958012
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,12,0.789249,0.481672,0.437086
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,20,0.687866,0.788636,0.741884
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,20,0.701437,0.520599,0.339376
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,20,0.713411,0.814913,0.806206
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,20,0.712436,0.985577,0.978132
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,20,0.699243,0.850202,0.824350
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,14,0.668214,0.856436,0.801375
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,19,0.702663,0.823452,0.831440
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,15,0.690203,0.971311,0.838643
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,15,0.711489,0.679803,0.623279
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,20,0.735887,0.961694,0.958006
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,20,0.750587,0.830343,0.796352
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,20,0.718603,0.921797,0.891570
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,17,0.732394,0.944672,0.973346
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,20,0.760563,0.753296,0.776005
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,20,0.759096,0.965686,0.975679
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,18,0.728873,0.710280,0.620931

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.8095
Overall window-level macro F1: 0.7996
Mean fold accuracy: 0.8435 ± 0.1347
Mean fold macro F1: 0.8173 ± 0.1636
Saved summary CSV: experiment_results/segment_combination_study__combo-ForeArm__Hand__Shoulder__nseg-3__win-4s__step-0.5s__20260407_173706__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-ForeArm__Hand__Shoulder__nseg-3__win-4s__step-0.5s__20260407_173706__folds.csv

====================================================================================================
Combination run 15/15
Canonical combo: ['UpperArm', 'ForeArm', 'Hand', 'Shoulder']
Selected segment labels: ['LeftUpperArm', 'RightUpperArm', 'LeftForeArm', 'RightForeArm', 'LeftHand', 'RightHand', 'LeftShoulder', 'RightShoulder']
No cached dataset found. Building dataset from MVNX files...
Kept files: 1420 | Skipped files (allowed but failed): 88
X: (14521, 240, 24) y: (14521,) groups: (14521,)
Saved dataset cache to: cached_datasets/dataset_ULF_in_ADL__ch-angularVelocity_sensorFreeAcceleration__seg-LeftUpperArm_RightUpperArm_LeftForeArm_RightForeArm_LeftHand_RightHand_LeftShoulder_RightShoulder__win-4s__step-0.5s__tasks-11-12-13-16-20-21-23-24-28-29.npz
Segment combo (UpperArm+ForeArm+Hand+Shoulder) dataset loaded.
Dataset shape: (14521, 240, 24)
Unique subjects: 25
Class counts: {np.str_('answer_phone'): np.int64(883), np.str_('brush_teeth'): np.int64(1313), np.str_('drink_from_glass'): np.int64(1148), np.str_('eat_apple'): np.int64(580), np.str_('lift_suitcase_to_floor'): np.int64(917), np.str_('open_door'): np.int64(485), np.str_('open_laptop'): np.int64(2781), np.str_('place_ball_in_basket'): np.int64(467), np.str_('pour_water'): np.int64(4606), np.str_('use_key_unlock'): np.int64(1341)}
Example window shape (T,C): (240, 24)
Total LOSO folds to run: 25
Classes: [np.str_('answer_phone'), np.str_('brush_teeth'), np.str_('drink_from_glass'), np.str_('eat_apple'), np.str_('lift_suitcase_to_floor'), np.str_('open_door'), np.str_('open_laptop'), np.str_('place_ball_in_basket'), np.str_('pour_water'), np.str_('use_key_unlock')]
Subjects: [np.str_('H01'), np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P06'), np.str_('P08'), np.str_('P09'), np.str_('P10'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P20'), np.str_('P21'), np.str_('P22'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
==========================================================================================
LOSO fold 1/25 | test subject: H01
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H02'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H01')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3905 train_acc=0.2273 | val_loss=1.7560 val_acc=0.3113 | test_loss=1.5787 test_acc=0.2875
Epoch 02 | train_loss=1.1132 train_acc=0.5302 | val_loss=1.1414 val_acc=0.4479 | test_loss=0.9880 test_acc=0.4322
Epoch 03 | train_loss=0.7365 train_acc=0.6668 | val_loss=0.9324 val_acc=0.6106 | test_loss=0.7619 test_acc=0.5931
Epoch 04 | train_loss=0.5546 train_acc=0.7715 | val_loss=0.9886 val_acc=0.6113 | test_loss=0.8459 test_acc=0.5606
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 05 | train_loss=0.4392 train_acc=0.8470 | val_loss=0.7976 val_acc=0.7405 | test_loss=0.6039 test_acc=0.6817
Epoch 06 | train_loss=0.3549 train_acc=0.8911 | val_loss=0.7658 val_acc=0.7707 | test_loss=0.6345 test_acc=0.6872
Epoch 07 | train_loss=0.2863 train_acc=0.9139 | val_loss=0.8216 val_acc=0.7827 | test_loss=0.6775 test_acc=0.6998
Epoch 08 | train_loss=0.2424 train_acc=0.9298 | val_loss=0.7128 val_acc=0.8152 | test_loss=0.5616 test_acc=0.7631
Epoch 09 | train_loss=0.2003 train_acc=0.9449 | val_loss=0.7771 val_acc=0.8052 | test_loss=0.6527 test_acc=0.7505
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.1716 train_acc=0.9526 | val_loss=0.7448 val_acc=0.8135 | test_loss=0.5525 test_acc=0.7957
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.1500 train_acc=0.9587 | val_loss=0.8626 val_acc=0.8028 | test_loss=0.7720 test_acc=0.7143
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 12 | train_loss=0.1294 train_acc=0.9636 | val_loss=0.7414 val_acc=0.8139 | test_loss=0.6345 test_acc=0.7631
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 13 | train_loss=0.1138 train_acc=0.9695 | val_loss=0.7340 val_acc=0.8373 | test_loss=0.4484 test_acc=0.8409
Epoch 14 | train_loss=0.0991 train_acc=0.9737 | val_loss=0.9326 val_acc=0.8015 | test_loss=0.8871 test_acc=0.7288
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 15 | train_loss=0.0895 train_acc=0.9773 | val_loss=0.7862 val_acc=0.8326 | test_loss=0.5947 test_acc=0.7902
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 16 | train_loss=0.0782 train_acc=0.9798 | val_loss=0.9298 val_acc=0.7968 | test_loss=0.7647 test_acc=0.6962
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 17 | train_loss=0.0712 train_acc=0.9821 | val_loss=0.7782 val_acc=0.8346 | test_loss=0.5613 test_acc=0.8264
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 18 | train_loss=0.0617 train_acc=0.9852 | val_loss=0.8144 val_acc=0.8259 | test_loss=0.5410 test_acc=0.7993
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 18.
Fold 1 complete | subject=H01 | test_acc=0.8409 | test_macro_f1=0.8119
==========================================================================================
LOSO fold 2/25 | test subject: H02
Train subjects: [np.str_('H03'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H02')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.1897 train_acc=0.2983 | val_loss=1.6048 val_acc=0.3177 | test_loss=1.2091 test_acc=0.4624
Epoch 02 | train_loss=1.1080 train_acc=0.5644 | val_loss=1.1965 val_acc=0.4753 | test_loss=0.6566 test_acc=0.6992
Epoch 03 | train_loss=0.7487 train_acc=0.7223 | val_loss=0.8882 val_acc=0.6350 | test_loss=0.3857 test_acc=0.8383
Epoch 04 | train_loss=0.5548 train_acc=0.8220 | val_loss=0.8265 val_acc=0.7019 | test_loss=0.2679 test_acc=0.9023
Epoch 05 | train_loss=0.4231 train_acc=0.8693 | val_loss=0.7783 val_acc=0.7560 | test_loss=0.2335 test_acc=0.9173
Epoch 06 | train_loss=0.3440 train_acc=0.8954 | val_loss=0.7821 val_acc=0.7639 | test_loss=0.2353 test_acc=0.9173
Epoch 07 | train_loss=0.2842 train_acc=0.9142 | val_loss=0.7006 val_acc=0.7841 | test_loss=0.1769 test_acc=0.9398
Epoch 08 | train_loss=0.2361 train_acc=0.9298 | val_loss=0.7232 val_acc=0.8018 | test_loss=0.1932 test_acc=0.9173
Epoch 09 | train_loss=0.2060 train_acc=0.9359 | val_loss=0.7480 val_acc=0.7996 | test_loss=0.1997 test_acc=0.9248
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 10 | train_loss=0.1773 train_acc=0.9448 | val_loss=0.7528 val_acc=0.7526 | test_loss=0.1167 test_acc=0.9586
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 11 | train_loss=0.1532 train_acc=0.9544 | val_loss=0.7366 val_acc=0.7697 | test_loss=0.0941 test_acc=0.9662
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 12 | train_loss=0.1323 train_acc=0.9611 | val_loss=0.7751 val_acc=0.7721 | test_loss=0.1021 test_acc=0.9737
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 13 | train_loss=0.1179 train_acc=0.9672 | val_loss=0.7115 val_acc=0.8070 | test_loss=0.1303 test_acc=0.9586
Epoch 14 | train_loss=0.1029 train_acc=0.9706 | val_loss=0.7036 val_acc=0.8103 | test_loss=0.1467 test_acc=0.9586
Epoch 15 | train_loss=0.0897 train_acc=0.9761 | val_loss=0.8280 val_acc=0.7673 | test_loss=0.0635 test_acc=0.9737
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 16 | train_loss=0.0820 train_acc=0.9796 | val_loss=0.6823 val_acc=0.8210 | test_loss=0.1182 test_acc=0.9624
Epoch 17 | train_loss=0.0717 train_acc=0.9834 | val_loss=0.7128 val_acc=0.8091 | test_loss=0.1566 test_acc=0.9549
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 18 | train_loss=0.0634 train_acc=0.9848 | val_loss=0.6307 val_acc=0.8302 | test_loss=0.1602 test_acc=0.9511
Epoch 19 | train_loss=0.0595 train_acc=0.9840 | val_loss=0.8477 val_acc=0.7957 | test_loss=0.1177 test_acc=0.9624
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 20 | train_loss=0.0496 train_acc=0.9887 | val_loss=0.6164 val_acc=0.8464 | test_loss=0.1516 test_acc=0.9549
Fold 2 complete | subject=H02 | test_acc=0.9549 | test_macro_f1=0.9672
==========================================================================================
LOSO fold 3/25 | test subject: H03
Train subjects: [np.str_('H02'), np.str_('H04'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H03')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3706 train_acc=0.2535 | val_loss=1.6792 val_acc=0.3317 | test_loss=1.1321 test_acc=0.5550
Epoch 02 | train_loss=1.1554 train_acc=0.5437 | val_loss=1.1449 val_acc=0.4490 | test_loss=0.5090 test_acc=0.7213
Epoch 03 | train_loss=0.7744 train_acc=0.6761 | val_loss=1.0055 val_acc=0.5916 | test_loss=0.3320 test_acc=0.8220
Epoch 04 | train_loss=0.5736 train_acc=0.7944 | val_loss=0.8589 val_acc=0.6891 | test_loss=0.2432 test_acc=0.8852
Epoch 05 | train_loss=0.4421 train_acc=0.8534 | val_loss=0.8492 val_acc=0.7306 | test_loss=0.2189 test_acc=0.8852
Epoch 06 | train_loss=0.3531 train_acc=0.8834 | val_loss=0.7765 val_acc=0.7315 | test_loss=0.1919 test_acc=0.9087
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 07 | train_loss=0.2908 train_acc=0.9067 | val_loss=0.8193 val_acc=0.7440 | test_loss=0.1648 test_acc=0.9133
Epoch 08 | train_loss=0.2446 train_acc=0.9244 | val_loss=1.0179 val_acc=0.6823 | test_loss=0.1983 test_acc=0.9344
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 09 | train_loss=0.2093 train_acc=0.9389 | val_loss=0.8078 val_acc=0.7428 | test_loss=0.1175 test_acc=0.9344
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 10 | train_loss=0.1766 train_acc=0.9506 | val_loss=0.7485 val_acc=0.7676 | test_loss=0.1192 test_acc=0.9391
Epoch 11 | train_loss=0.1544 train_acc=0.9555 | val_loss=0.8355 val_acc=0.7404 | test_loss=0.1412 test_acc=0.9321
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 12 | train_loss=0.1334 train_acc=0.9647 | val_loss=0.7337 val_acc=0.7862 | test_loss=0.1076 test_acc=0.9368
Epoch 13 | train_loss=0.1172 train_acc=0.9693 | val_loss=0.8468 val_acc=0.7645 | test_loss=0.1431 test_acc=0.9368
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.1025 train_acc=0.9739 | val_loss=0.9259 val_acc=0.7495 | test_loss=0.1122 test_acc=0.9344
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.0941 train_acc=0.9753 | val_loss=0.8903 val_acc=0.7532 | test_loss=0.1263 test_acc=0.9368
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 16 | train_loss=0.0807 train_acc=0.9798 | val_loss=0.8244 val_acc=0.7816 | test_loss=0.0891 test_acc=0.9508
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 17 | train_loss=0.0725 train_acc=0.9835 | val_loss=0.8121 val_acc=0.7789 | test_loss=0.0778 test_acc=0.9578
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 17.
Fold 3 complete | subject=H03 | test_acc=0.9368 | test_macro_f1=0.9400
==========================================================================================
LOSO fold 4/25 | test subject: H04
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H05'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H04')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.2100 train_acc=0.2329 | val_loss=1.6836 val_acc=0.3232 | test_loss=1.4539 test_acc=0.4489
Epoch 02 | train_loss=1.1273 train_acc=0.5504 | val_loss=1.1154 val_acc=0.4753 | test_loss=0.7601 test_acc=0.6423
Epoch 03 | train_loss=0.7617 train_acc=0.6857 | val_loss=0.9660 val_acc=0.5476 | test_loss=0.4787 test_acc=0.7555
Epoch 04 | train_loss=0.5611 train_acc=0.7966 | val_loss=0.8993 val_acc=0.6698 | test_loss=0.3292 test_acc=0.9051
Epoch 05 | train_loss=0.4321 train_acc=0.8627 | val_loss=0.7544 val_acc=0.7492 | test_loss=0.2399 test_acc=0.9270
Epoch 06 | train_loss=0.3362 train_acc=0.8980 | val_loss=0.7775 val_acc=0.7712 | test_loss=0.2160 test_acc=0.9562
Epoch 07 | train_loss=0.2759 train_acc=0.9193 | val_loss=0.7719 val_acc=0.7602 | test_loss=0.1964 test_acc=0.9489
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.2300 train_acc=0.9318 | val_loss=0.7460 val_acc=0.7648 | test_loss=0.1915 test_acc=0.9562
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.1998 train_acc=0.9405 | val_loss=0.7643 val_acc=0.7789 | test_loss=0.1867 test_acc=0.9599
Epoch 10 | train_loss=0.1704 train_acc=0.9502 | val_loss=0.8506 val_acc=0.7642 | test_loss=0.1922 test_acc=0.9380
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 11 | train_loss=0.1466 train_acc=0.9572 | val_loss=0.7223 val_acc=0.7807 | test_loss=0.1375 test_acc=0.9672
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 12 | train_loss=0.1314 train_acc=0.9657 | val_loss=0.6724 val_acc=0.7987 | test_loss=0.1036 test_acc=0.9891
Epoch 13 | train_loss=0.1144 train_acc=0.9672 | val_loss=0.7959 val_acc=0.7896 | test_loss=0.1300 test_acc=0.9781
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 14 | train_loss=0.1002 train_acc=0.9740 | val_loss=0.8859 val_acc=0.7575 | test_loss=0.1582 test_acc=0.9599
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 15 | train_loss=0.0890 train_acc=0.9772 | val_loss=0.8506 val_acc=0.7773 | test_loss=0.1199 test_acc=0.9745
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 16 | train_loss=0.0772 train_acc=0.9807 | val_loss=0.7317 val_acc=0.7804 | test_loss=0.0880 test_acc=0.9891
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 17 | train_loss=0.0711 train_acc=0.9828 | val_loss=0.6856 val_acc=0.8079 | test_loss=0.0935 test_acc=0.9818
Epoch 18 | train_loss=0.0634 train_acc=0.9853 | val_loss=0.7603 val_acc=0.8067 | test_loss=0.0791 test_acc=0.9891
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 19 | train_loss=0.0552 train_acc=0.9864 | val_loss=0.6885 val_acc=0.8109 | test_loss=0.0854 test_acc=0.9818
Epoch 20 | train_loss=0.0493 train_acc=0.9896 | val_loss=0.7145 val_acc=0.8079 | test_loss=0.1109 test_acc=0.9745
  No validation improvement greater than 0.0020. Patience: 1/5
Fold 4 complete | subject=H04 | test_acc=0.9818 | test_macro_f1=0.9699
==========================================================================================
LOSO fold 5/25 | test subject: H05
Train subjects: [np.str_('H02'), np.str_('H03'), np.str_('H04'), np.str_('P02'), np.str_('P03'), np.str_('P04'), np.str_('P05'), np.str_('P08'), np.str_('P09'), np.str_('P12'), np.str_('P16'), np.str_('P17'), np.str_('P19'), np.str_('P21'), np.str_('P24'), np.str_('P25'), np.str_('P28'), np.str_('P29'), np.str_('P30')]
Val subjects:   [np.str_('H01'), np.str_('P06'), np.str_('P10'), np.str_('P20'), np.str_('P22')]
Test subject:   [np.str_('H05')]
No subject overlap detected between train and val.
Identical windows in train/val: 0
No subject overlap detected between train and test.
Identical windows in train/test: 0
No subject overlap detected between val and test.
Identical windows in val/test: 0
Epoch 01 | train_loss=2.3094 train_acc=0.2577 | val_loss=1.8717 val_acc=0.2749 | test_loss=1.5214 test_acc=0.3649
Epoch 02 | train_loss=1.1902 train_acc=0.5702 | val_loss=1.1453 val_acc=0.5034 | test_loss=0.7716 test_acc=0.5933
Epoch 03 | train_loss=0.7296 train_acc=0.7567 | val_loss=0.8699 val_acc=0.7007 | test_loss=0.6316 test_acc=0.7019
Epoch 04 | train_loss=0.5303 train_acc=0.8418 | val_loss=0.8850 val_acc=0.7398 | test_loss=0.5353 test_acc=0.7187
Epoch 05 | train_loss=0.4138 train_acc=0.8830 | val_loss=0.9867 val_acc=0.6964 | test_loss=0.6499 test_acc=0.6880
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 06 | train_loss=0.3338 train_acc=0.9055 | val_loss=0.7893 val_acc=0.7633 | test_loss=0.5827 test_acc=0.7549
Epoch 07 | train_loss=0.2784 train_acc=0.9194 | val_loss=0.8129 val_acc=0.7581 | test_loss=0.5649 test_acc=0.7716
  No validation improvement greater than 0.0020. Patience: 1/5
Epoch 08 | train_loss=0.2305 train_acc=0.9347 | val_loss=0.7966 val_acc=0.7645 | test_loss=0.6056 test_acc=0.7103
  No validation improvement greater than 0.0020. Patience: 2/5
Epoch 09 | train_loss=0.1950 train_acc=0.9467 | val_loss=0.9075 val_acc=0.7306 | test_loss=0.6473 test_acc=0.7242
  No validation improvement greater than 0.0020. Patience: 3/5
Epoch 10 | train_loss=0.1665 train_acc=0.9570 | val_loss=1.0030 val_acc=0.7129 | test_loss=0.6776 test_acc=0.7047
  No validation improvement greater than 0.0020. Patience: 4/5
Epoch 11 | train_loss=0.1442 train_acc=0.9615 | val_loss=0.8486 val_acc=0.7486 | test_loss=0.7318 test_acc=0.6908
  No validation improvement greater than 0.0020. Patience: 5/5
Early stopping triggered at epoch 11.
Fold 5 complete | subject=H05 | test_acc=0.7549 | test_macro_f1=0.7881
==========================================================================================
LOSO fold 6/25 | test subject: P02

,fold,test_subject,win_len_s,step_s,overlap_fraction,n_train_windows,n_val_windows,n_test_windows,n_train_subjects,n_val_subjects,epochs_ran,best_val_acc,test_acc,test_macro_f1
0,1,H01,4.0,0.5,0.875,10981,2987,553,19,5,18,0.837295,0.840868,0.811912
1,2,H02,4.0,0.5,0.875,10981,3274,266,19,5,20,0.846365,0.954887,0.967218
2,3,H03,4.0,0.5,0.875,10820,3274,427,19,5,17,0.786194,0.936768,0.939991
3,4,H04,4.0,0.5,0.875,10973,3274,274,19,5,20,0.810935,0.981752,0.969936
4,5,H05,4.0,0.5,0.875,10888,3274,359,19,5,11,0.763286,0.754875,0.788100
5,6,P02,4.0,0.5,0.875,10563,3274,684,19,5,19,0.803299,0.837719,0.845408
6,7,P03,4.0,0.5,0.875,10868,3274,379,19,5,15,0.813684,0.976253,0.977903
7,8,P04,4.0,0.5,0.875,10711,3274,536,19,5,20,0.803604,0.925373,0.928633
8,9,P05,4.0,0.5,0.875,9883,3274,1364,19,5,18,0.840257,0.502933,0.526390
9,10,P06,4.0,0.5,0.875,9883,3758,880,19,5,20,0.718201,0.837500,0.803116
10,11,P08,4.0,0.5,0.875,10496,3758,267,19,5,20,0.722725,0.573034,0.318878
11,12,P09,4.0,0.5,0.875,10012,3758,751,19,5,20,0.720330,0.747004,0.793018
12,13,P10,4.0,0.5,0.875,10012,4093,416,19,5,20,0.734180,0.987981,0.987156
13,14,P12,4.0,0.5,0.875,9687,4093,741,19,5,20,0.714879,0.842105,0.825753
14,15,P16,4.0,0.5,0.875,9822,4093,606,19,5,12,0.666259,0.861386,0.825879
15,16,P17,4.0,0.5,0.875,9669,4093,759,19,5,20,0.689226,0.845850,0.842535
16,17,P19,4.0,0.5,0.875,10184,4093,244,19,5,14,0.698510,0.987705,0.987618
17,18,P20,4.0,0.5,0.875,10184,3525,812,19,5,16,0.738723,0.662562,0.638766
18,19,P21,4.0,0.5,0.875,10500,3525,496,19,5,15,0.735603,0.963710,0.962474
19,20,P22,4.0,0.5,0.875,10500,3408,613,19,5,18,0.738850,0.859706,0.814182
20,21,P24,4.0,0.5,0.875,10512,3408,601,19,5,20,0.758803,0.918469,0.882277
21,22,P25,4.0,0.5,0.875,10625,3408,488,19,5,20,0.732101,0.934426,0.942980
22,23,P28,4.0,0.5,0.875,10051,3408,1062,19,5,10,0.722711,0.778719,0.822210
23,24,P29,4.0,0.5,0.875,10705,3408,408,19,5,20,0.754988,0.980392,0.981953
24,25,P30,4.0,0.5,0.875,10578,3408,535,19,5,20,0.763498,0.728972,0.661531

==========================================================================================
LOSO SUMMARY
Overall window-level accuracy: 0.8156
Overall window-level macro F1: 0.8114
Mean fold accuracy: 0.8488 ± 0.1306
Mean fold macro F1: 0.8338 ± 0.1595
Saved summary CSV: experiment_results/segment_combination_study__combo-UpperArm__ForeArm__Hand__Shoulder__nseg-4__win-4s__step-0.5s__20260407_175728__summary.csv
Saved per-fold CSV: experiment_results/segment_combination_study__combo-UpperArm__ForeArm__Hand__Shoulder__nseg-4__win-4s__step-0.5s__20260407_175728__folds.csv

####################################################################################################
SEGMENT COMBINATION STUDY COMPLETE
Saved combination summary CSV: experiment_results/segment_combination_study__segment_combination_summary__win-4s__step-0.5s.csv

,study_name,win_len_s,step_s,overlap_fraction,channels_used,selected_segments,n_total_windows,n_subjects,n_classes,cache_path,...,mean_fold_acc,std_fold_acc,mean_fold_macro_f1,std_fold_macro_f1,mean_epochs_ran,mean_best_val_acc,combo_size,canonical_combo,n_segment_labels_used,dataset_cache_path
0,segment_combination_study__combo-UpperArm__For...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftForeArm|RightFo...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.848838,0.130640,0.833833,0.159519,17.72,0.756580,4,UpperArm|ForeArm|Hand|Shoulder,8,cached_datasets/dataset_ULF_in_ADL__ch-angular...
1,segment_combination_study__combo-ForeArm__Hand...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftForeArm|RightForeArm|LeftHand|RightHand,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.848253,0.129302,0.832085,0.149077,17.76,0.753312,2,ForeArm|Hand,4,cached_datasets/dataset_ULF_in_ADL__ch-angular...
2,segment_combination_study__combo-UpperArm__For...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftForeArm|RightFo...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.851251,0.124753,0.829856,0.154842,17.64,0.761739,3,UpperArm|ForeArm|Hand,6,cached_datasets/dataset_ULF_in_ADL__ch-angular...
3,segment_combination_study__combo-UpperArm__Han...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftHand|RightHand,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.845866,0.133322,0.826431,0.151865,18.96,0.751370,2,UpperArm|Hand,4,cached_datasets/dataset_ULF_in_ADL__ch-angular...
4,segment_combination_study__combo-UpperArm__Han...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftHand|RightHand|...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.839157,0.140892,0.822096,0.162597,17.40,0.742013,3,UpperArm|Hand|Shoulder,6,cached_datasets/dataset_ULF_in_ADL__ch-angular...
5,segment_combination_study__combo-ForeArm__Hand...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftForeArm|RightForeArm|LeftHand|RightHand|Le...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.843489,0.134701,0.817267,0.163556,18.40,0.747665,3,ForeArm|Hand|Shoulder,6,cached_datasets/dataset_ULF_in_ADL__ch-angular...
6,segment_combination_study__combo-Hand__Shoulde...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftHand|RightHand|LeftShoulder|RightShoulder,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.832986,0.143584,0.811776,0.162273,17.40,0.728861,2,Hand|Shoulder,4,cached_datasets/dataset_ULF_in_ADL__ch-angular...
7,segment_combination_study__combo-UpperArm__For...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftForeArm|RightFo...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.823499,0.138518,0.809050,0.163078,16.72,0.717321,2,UpperArm|ForeArm,4,cached_datasets/dataset_ULF_in_ADL__ch-angular...
8,segment_combination_study__combo-Hand__nseg-1,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftHand|RightHand,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.829016,0.158770,0.807537,0.172987,18.52,0.736329,1,Hand,2,cached_datasets/dataset_ULF_in_ADL__ch-angular...
9,segment_combination_study__combo-ForeArm__Shou...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftForeArm|RightForeArm|LeftShoulder|RightSho...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.817622,0.141808,0.798547,0.163425,18.72,0.707770,2,ForeArm|Shoulder,4,cached_datasets/dataset_ULF_in_ADL__ch-angular...
10,segment_combination_study__combo-ForeArm__nseg-1,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftForeArm|RightForeArm,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.813922,0.145975,0.785600,0.162888,19.16,0.711629,1,ForeArm,2,cached_datasets/dataset_ULF_in_ADL__ch-angular...
11,segment_combination_study__combo-UpperArm__For...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftForeArm|RightFo...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.806156,0.149702,0.782717,0.176223,17.52,0.714666,3,UpperArm|ForeArm|Shoulder,6,cached_datasets/dataset_ULF_in_ADL__ch-angular...
12,segment_combination_study__combo-UpperArm__Sho...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftShoulder|RightS...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.723177,0.154810,0.661190,0.167745,18.52,0.639905,2,UpperArm|Shoulder,4,cached_datasets/dataset_ULF_in_ADL__ch-angular...
13,segment_combination_study__combo-UpperArm__nseg-1,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.704822,0.144758,0.652976,0.161048,18.00,0.631426,1,UpperArm,2,cached_datasets/dataset_ULF_in_ADL__ch-angular...
14,segment_combination_study__combo-Shoulder__nseg-1,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftShoulder|RightShoulder,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.586725,0.121306,0.521004,0.136403,17.68,0.531267,1,Shoulder,2,cached_datasets/dataset_ULF_in_ADL__ch-angular...

Segment combination study complete.

,study_name,win_len_s,step_s,overlap_fraction,channels_used,selected_segments,n_total_windows,n_subjects,n_classes,cache_path,...,mean_fold_acc,std_fold_acc,mean_fold_macro_f1,std_fold_macro_f1,mean_epochs_ran,mean_best_val_acc,combo_size,canonical_combo,n_segment_labels_used,dataset_cache_path
0,segment_combination_study__combo-UpperArm__For...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftForeArm|RightFo...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.848838,0.130640,0.833833,0.159519,17.72,0.756580,4,UpperArm|ForeArm|Hand|Shoulder,8,cached_datasets/dataset_ULF_in_ADL__ch-angular...
1,segment_combination_study__combo-ForeArm__Hand...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftForeArm|RightForeArm|LeftHand|RightHand,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.848253,0.129302,0.832085,0.149077,17.76,0.753312,2,ForeArm|Hand,4,cached_datasets/dataset_ULF_in_ADL__ch-angular...
2,segment_combination_study__combo-UpperArm__For...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftForeArm|RightFo...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.851251,0.124753,0.829856,0.154842,17.64,0.761739,3,UpperArm|ForeArm|Hand,6,cached_datasets/dataset_ULF_in_ADL__ch-angular...
3,segment_combination_study__combo-UpperArm__Han...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftHand|RightHand,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.845866,0.133322,0.826431,0.151865,18.96,0.751370,2,UpperArm|Hand,4,cached_datasets/dataset_ULF_in_ADL__ch-angular...
4,segment_combination_study__combo-UpperArm__Han...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftHand|RightHand|...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.839157,0.140892,0.822096,0.162597,17.40,0.742013,3,UpperArm|Hand|Shoulder,6,cached_datasets/dataset_ULF_in_ADL__ch-angular...
5,segment_combination_study__combo-ForeArm__Hand...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftForeArm|RightForeArm|LeftHand|RightHand|Le...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.843489,0.134701,0.817267,0.163556,18.40,0.747665,3,ForeArm|Hand|Shoulder,6,cached_datasets/dataset_ULF_in_ADL__ch-angular...
6,segment_combination_study__combo-Hand__Shoulde...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftHand|RightHand|LeftShoulder|RightShoulder,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.832986,0.143584,0.811776,0.162273,17.40,0.728861,2,Hand|Shoulder,4,cached_datasets/dataset_ULF_in_ADL__ch-angular...
7,segment_combination_study__combo-UpperArm__For...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftForeArm|RightFo...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.823499,0.138518,0.809050,0.163078,16.72,0.717321,2,UpperArm|ForeArm,4,cached_datasets/dataset_ULF_in_ADL__ch-angular...
8,segment_combination_study__combo-Hand__nseg-1,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftHand|RightHand,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.829016,0.158770,0.807537,0.172987,18.52,0.736329,1,Hand,2,cached_datasets/dataset_ULF_in_ADL__ch-angular...
9,segment_combination_study__combo-ForeArm__Shou...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftForeArm|RightForeArm|LeftShoulder|RightSho...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.817622,0.141808,0.798547,0.163425,18.72,0.707770,2,ForeArm|Shoulder,4,cached_datasets/dataset_ULF_in_ADL__ch-angular...
10,segment_combination_study__combo-ForeArm__nseg-1,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftForeArm|RightForeArm,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.813922,0.145975,0.785600,0.162888,19.16,0.711629,1,ForeArm,2,cached_datasets/dataset_ULF_in_ADL__ch-angular...
11,segment_combination_study__combo-UpperArm__For...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftForeArm|RightFo...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.806156,0.149702,0.782717,0.176223,17.52,0.714666,3,UpperArm|ForeArm|Shoulder,6,cached_datasets/dataset_ULF_in_ADL__ch-angular...
12,segment_combination_study__combo-UpperArm__Sho...,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm|LeftShoulder|RightS...,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.723177,0.154810,0.661190,0.167745,18.52,0.639905,2,UpperArm|Shoulder,4,cached_datasets/dataset_ULF_in_ADL__ch-angular...
13,segment_combination_study__combo-UpperArm__nseg-1,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftUpperArm|RightUpperArm,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.704822,0.144758,0.652976,0.161048,18.00,0.631426,1,UpperArm,2,cached_datasets/dataset_ULF_in_ADL__ch-angular...
14,segment_combination_study__combo-Shoulder__nseg-1,4.0,0.5,0.875,angularVelocity|sensorFreeAcceleration,LeftShoulder|RightShoulder,14521,25,10,cached_datasets/dataset_ULF_in_ADL__ch-angular...,...,0.586725,0.121306,0.521004,0.136403,17.68,0.531267,1,Shoulder,2,cached_datasets/dataset_ULF_in_ADL__ch-angular...